### ISSUE TITLE
Unable to click list webelement using pagefactory class

### ISSUE THREAD

**Issue by logakarthi** [appium/java-client#1012]
## Description

Unable to click list web element using page factory class and getting "java.lang.reflect.InvocationTargetException" and "java.lang.IndexOutOfBoundsException: Index: 4, Size: 4" exception.  List webelement sizes are showing well, but couldn't click based on the index value. I used the below code but no luck for me.

## Environment

* Appium server version or git revision if you use some shapshot: 1.7.2
* Desktop OS/version used to run Appium if necessary: MAC
* Mobile platform/version under test: ANDROID 6.0.1
* Real device or emulator/simulator: Real device

## Code To Reproduce Issue [ Good To Have ]
Tried syntax 1:
 @FindAll ({
        @FindBy(how = How.CSS, using ="li.response-row div.display-text")
        @FindBy(css = "li.response-row:nth-child(1) div.display-text"),
        @FindBy(css = "li.response-row:nth-child(2) div.display-text"),
        @FindBy(css = "li.response-row:nth-child(3) div.display-text"),
        @FindBy(css = "li.response-row:nth-child(4) div.display-text"),
    })
    private List<WebElement> multipleChoiceField;
    
Syntax : 2
    @FindBy(css = "li.response-row div.display-text")
    private WebElement multipleChoiceField;

Finding the webelement size, but unable to click it with the below code,

 multipleChoiceField.get(1).click();

Exception :
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at 
io.appium.java_client.pagefactory.ElementListInterceptor.intercept(ElementListInterceptor.java:35)
        at $java.util.ArrayList$$EnhancerByCGLIB$$8dd1e6a5.get(<generated>)
        at Pages.PracticePage.validateMultipleChoiceQuestion(PracticePage.java:373)
        at Pages.PracticePage.attemptPractice(PracticePage.java:270)
        at Tests.LandingPageTest.launcherPage(LandingPageTest.java:56)
Caused by: java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        ... 43 more

**Comment by logakarthi** [comment]
@mykola-mokhnach

**Comment by SrinivasanTarget** [comment]
@logakarthi please raise questions in discuss forum
