### ISSUE TITLE
Longpress doesn't work after adding java-client 6.1.0

### ISSUE THREAD

**Issue by hieutrandn9889** [appium/java-client#1033]
Hello all,

TouchActions action = new TouchActions(driverAppium);
		MobileElement ele = driverAppium.findElementById("com.android.messaging:id/swipeableContent");
		action.longPress(ele);
		action.perform();

Exception:
Sep 22, 2018 12:54:07 PM io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0
INFO: Detected dialect: W3C
Exception in thread "main" java.lang.ClassCastException: io.appium.java_client.android.AndroidDriver cannot be cast to org.openqa.selenium.interactions.HasTouchScreen
	at org.openqa.selenium.interactions.touch.TouchActions.<init>(TouchActions.java:38)
	at test.anPhimLau.longPress(anPhimLau.java:43)
	at test.anPhimLau.main(anPhimLau.java:73)

**Comment by saikrishna321** [comment]
@hieutrandn9889 Please ask questions in discuss.appium.io 

https://discuss.appium.io/t/no-suitable-method-found-for-longpress/23632
