### ISSUE TITLE
TouchAction.perform not working since upgrading to Appium 1.8.X (Unhandled endpoint ... /wda/touch/perform)

### ISSUE THREAD

**Issue by Hiti3** [appium/java-client#1038]
## Description

Since upgrading Appium from 1.7 to 1.8.1 or 1.9 the touch events does not work anymore on iOS. I have seen numerous people stating newest WDA server pull solved the issue, others stating full reinstall of appium, clearing of Xcode, etc.. I have tried the solutions provided by other users, but simply I can not get the issue resolved.
I have downloaded the newest WDA server version, installed latest appium version (1.9) and If I try to upgrade the java client to 6.1.0 and when done the last I get unhandled endpoint error when obtaining the session... 
Nothing at all seems to be working for me. I would appreciate help on resolving this ambiguous issue.

## Environment

java client build version: 5.0.4
Appium server version: 1.8.1
Last Appium version that it was working: 1.7.2
OS version: MacOS 10.13.6
Node.js version: v10.5.0
Mobile platform/version under test: iOS 11.2.1
Real device: iPhone 6
Java version is: 1.8.0_172

## Details

TouchAction.perform() is throwing unhandled endpoint since upgrading Appium to 1.8.X.  

## Code To Reproduce Issue [ Good To Have ]

```
    public static void performTouch(@NotNull DeviceDriver deviceDriver, int x, int y) {
        new TouchAction(deviceDriver.getDriver())
                .tap(x, y)
                .release()
                .perform();
    }
```

## Ecxeption stacktraces
```
2018-10-04 12:25:09:653 - [HTTP] --> POST /wd/hub/session/db253fee-c5d0-45b2-9f10-8b1658dfc808/touch/perform
2018-10-04 12:25:09:654 - [HTTP] {"actions":[{"action":"tap","options":{"x":1,"y":1}},{"action":"release","options":{}}]}
2018-10-04 12:25:09:656 - [debug] [W3C] Calling AppiumDriver.performTouch() with args: [[{"action":"tap","options":{"x":1,"y":1}},{"action":"release","options":{}}],"db253fee-c5d0-45b2-9f10-8b1658dfc808"]
2018-10-04 12:25:09:656 - [debug] [XCUITest] Executing command 'performTouch'
2018-10-04 12:25:09:659 - [debug] [XCUITest] Received the following touch action: tap(options={"x":1,"y":1})-release(options={})
2018-10-04 12:25:09:659 - [debug] [JSONWP Proxy] Proxying [POST /wda/touch/perform] to [POST http://127.0.0.1:11600/session/76F406B4-238C-4270-B028-5C7B3BC2AA91/wda/touch/perform] with body: {"actions":[{"action":"tap","options":{"x":1,"y":1}},{"action":"release","options":{}}]}
2018-10-04 12:25:09:676 - [debug] [JSONWP Proxy] Got response with status 200: {"value":"Unhandled endpoint: /session/76F406B4-238C-4270-B028-5C7B3BC2AA91/wda/touch/perform -- http://127.0.0.1:11600/ with parameters {\n    wildcards =     (\n        \"session/76F406B4-238C-4270-B028-5C7B3BC2AA91/wda/touch/perform\"\n    );\n}","sessionId":"76F406B4-238C-4270-B028-5C7B3BC2AA91","status":1}
2018-10-04 12:25:09:679 - [MJSONWP] Encountered internal error running command: Error: An error occurred
2018-10-04 12:25:09:680 - [MJSONWP]     at JWProxy.command$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:176:15)
2018-10-04 12:25:09:680 - [MJSONWP]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
2018-10-04 12:25:09:680 - [MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
2018-10-04 12:25:09:680 - [MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
2018-10-04 12:25:09:680 - [MJSONWP]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
2018-10-04 12:25:09:681 - [HTTP] <-- POST /wd/hub/session/db253fee-c5d0-45b2-9f10-8b1658dfc808/touch/perform 500 27 ms - 188
```

## Link to Appium logs

https://gist.github.com/Hiti3/2e4db4c23f1653ea4973f24d5c3fb2f4

**Comment by mykola-mokhnach** [comment]
Delete the cahced webdriveragent binary from the device and clear xcode caches

**Comment by Hiti3** [comment]
> Delete the cahced webdriveragent binary from the device and clear xcode caches

I have removed the WDA from the device manually and cleared the xcode caches as suggested from other posts. It has no effect. Or is there any other way of clearing webdriveragent binary from the device?

**Comment by mykola-mokhnach** [comment]
Form the log it is visible you use WDA build, which is not compatible with the current server version. the one, which is compatible, should be built from https://github.com/appium/WebDriverAgent fork. Other forks, including the original one from FB won't work.

**Comment by Hiti3** [comment]
Oh, I did not know I was always downloading the wrong facebook fork of the agent. The provided WebDriverAgent works as expected. Thank you!

**Comment by 18akshay8** [comment]
I tried the same solution for Appium - 2.5.1 but it still didnt work for me and i am getting the error - 

org.openqa.selenium.UnsupportedCommandException: Unhandled endpoint: /session/6C7B8124-3CA2-4EBC-963D-7763ED766FB9/wda/touch/perform -- http://127.0.0.1:8100/ with parameters {
    wildcards =     (
        "session/6C7B8124-3CA2-4EBC-963D-7763ED766FB9/wda/touch/perform"
    );
}
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'QB-TP3-3039.local', ip: 'fe80:0:0:0:10dc:713e:ba86:c97%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_202'
Driver info: io.appium.java_client.ios.IOSDriver
Session ID: 32a33eb9-4170-4a24-aa0a-8a407d1b980b
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at io.appium.java_client.PerformsTouchActions.performTouchAction(PerformsTouchActions.java:41)
	at io.appium.java_client.TouchAction.perform(TouchAction.java:187)
	at pages.app.SelectScheduleTypePage.selectStart(SelectScheduleTypePage.java:307)
	at tests.app20.LockFullsuite.setLimitByDateScheduleType(LockFullsuite.java:1408)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:770)
	at org.testng.TestRunner.run(TestRunner.java:591)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1175)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1175)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
	at org.testng.TestNG.runSuites(TestNG.java:1032)
	at org.testng.TestNG.run(TestNG.java:1000)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77

**Comment by kb150802** [comment]
I am facing this same issue.
How can we now do long press on an element

**Comment by valfirst** [comment]
@kb150802 https://github.com/appium/java-client/blob/master/docs/v7-to-v8-migration-guide.md#touch-actions

**Comment by biauyteeszercik** [comment]
Use Press in ur alghoritm instead of Tap.

**Comment by biauyteeszercik** [comment]
Using Press instead of a Tap was a solution for me.
