### ISSUE TITLE
Unable to launch Native/Hybrid app on real device getting an error when running script uncaughtException: Android bootstrap socket crashed: Error: getaddrinfo ENOENT u ndefined:4724

### ISSUE THREAD

**Issue by testfortest06** [appium/java-client#1049]
## Description
When i was running my script then Unable to launch Native/Hybrid app on real device getting an error when running script uncaughtException: Android bootstrap socket crashed: Error: getaddrinfo ENOENT u ndefined:4724

## Environment

* java client build version : 6.1.0
* Appium server version : 1.9.1
* Desktop OS/version used to run Appium :Windows 7
* Node.js version : 8.12.0
* Mobile platform/version under test: Android/8.1.0
* Real device or emulator/simulator: Real Device

## Details
Unable to launch Native Hybrid App, when i was running my script then getting an error and appium server automatically closed.

## Code To Reproduce Issue [ Good To Have ]

public class launchApp {

    AndroidDriver<AndroidElement> driver;

    @BeforeMethod
    public void beforeClass() throws MalformedURLException, InterruptedException {
        DesiredCapabilities capabilities = new DesiredCapabilities();

        capabilities.setCapability("deviceName", "Redmi Note 5");
        capabilities.setCapability("udid", "35924c6f0804");
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("platformVersion", "8.1.0");
        capabilities.setCapability("appPackage", "com.miui.calculator");
        capabilities.setCapability("appActivity", "com.miui.calculator.cal.CalculatorActivity");
        driver = new AndroidDriver<AndroidElement>(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);
       Thread.sleep(5000);

    }

    @Test
    public void m1() throws InterruptedException {
        System.out.println("Test");
        Thread.sleep(2000);

    }
}

## Ecxeption stacktraces

org.openqa.selenium.WebDriverException: It is impossible to create a new session because 'createSession' which takes HttpClient, InputStream and long was not found or it is not accessible
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'

## Link to Appium logs

C:\Users\Office>appium
[Appium] Welcome to Appium v1.9.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"appActivity":"com.miui.calculator.cal.Calculator
Activity","appPackage":"com.miui.calculator","platformVersion":"8.1.0","platform
Name":"Android","udid":"35924c6f0804","deviceName":"Redmi Note 5"},"capabilities
":{"alwaysMatch":{"appium:appActivity":"com.miui.calculator.cal.CalculatorActivi
ty","appium:appPackage":"com.miui.calculator","appium:deviceName":"Redmi Note 5"
,"platformName":"android","appium:platformVersion":"8.1.0","appium:udid":"35924c
6f0804"},"firstMatch":[{}]}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"appActivity":"c
om.miui.calculator.cal.CalculatorActivity","appPackage":"com.miui.calculator","p
latformVersion":"8.1.0","platformName":"Android","udid":"35924c6f0804","deviceNa
me":"Redmi Note 5"},null,{"alwaysMatch":{"appium:appActivity":"com.miui.calculat
or.cal.CalculatorActivity","appium:appPackage":"com.miui.calculator","appium:dev
iceName":"Redmi Note 5","platformName":"android","appium:platformVersion":"8.1.0
","appium:udid":"35924c6f0804"},"firstMatch":[{}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1540366983984 (13:13:
03 GMT+0530 (India Standard Time))
[Appium] Consider setting 'automationName' capability to 'UiAutomator2' on Andro
id >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.

[Appium] Creating new AndroidDriver (v4.1.1) session
[Appium] Capabilities:
[Appium]   platformName: android
[Appium]   appActivity: com.miui.calculator.cal.CalculatorActivity
[Appium]   appPackage: com.miui.calculator
[Appium]   deviceName: Redmi Note 5
[Appium]   platformVersion: 8.1.0
[Appium]   udid: 35924c6f0804
[debug] [BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP
 desired capabilities {"appActivity":"com.miui.ca... were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"pl
atformNa...
[BaseDriver] Session created with session id: 7b0dffe7-22e4-4811-a07c-c0af7981cf
99
[AndroidDriver] Java version is: 1.8.0_91
[ADB] Checking whether adb is present
[ADB] Found 2 'build-tools' folders under 'C:\Users\Office\AppData\Local\Android
\Sdk' (newest first):
[ADB]     C:/Users/Office/AppData/Local/Android/Sdk/build-tools/28.0.3
[ADB]     C:/Users/Office/AppData/Local/Android/Sdk/build-tools/28.0.2
[ADB] Using adb.exe from C:\Users\Office\AppData\Local\Android\Sdk\platform-tool
s\adb.exe
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Using device: 35924c6f0804
[debug] [ADB] Setting device id to 35924c6f0804
[debug] [ADB] Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\
adb.exe -P 5037 -s 35924c6f0804 shell getprop ro.build.version.sdk'
[debug] [ADB] Current device property 'ro.build.version.sdk': 27
[debug] [ADB] Device API level: 27
[AndroidDriver] Consider setting 'automationName' capability to 'uiautomator2' o
n Android >= 6, since UIAutomator framework is not maintained anymore by the OS
vendor.
[AndroidDriver] App file was not listed, instead we're going to run com.miui.cal
culator directly on the device
[debug] [AndroidDriver] Checking whether package is present on the device
[debug] [ADB] Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\
adb.exe -P 5037 -s 35924c6f0804 shell pm list packages com.miui.calculator'
[AndroidDriver] Starting Android session
[debug] [ADB] Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\
adb.exe -P 5037 -s 35924c6f0804 wait-for-device'
[debug] [ADB] Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\
adb.exe -P 5037 -s 35924c6f0804 shell echo ping'
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\
adb.exe -P 5037 -s 35924c6f0804 shell pm list packages io.appium.settings'
[debug] [ADB] App is installed
[debug] [ADB] Getting package info for 'io.appium.settings'
[debug] [ADB] Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\
adb.exe -P 5037 -s 35924c6f0804 shell dumpsys package io.appium.settings'
[ADB] Checking whether aapt is present
[ADB] Using aapt.exe from C:\Users\Office\AppData\Local\Android\Sdk\build-tools\
28.0.3\aapt.exe
[debug] [ADB] The installed 'io.appium.settings' package does not require upgrad
e ('2.3.0' >= '2.3.0')
[debug] [ADB] Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\
adb.exe -P 5037 -s 35924c6f0804 shell ps'
[debug] [ADB] Device API level: 27
[debug] [ADB] Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\
adb.exe -P 5037 -s 35924c6f0804 shell am start -W -n io.appium.settings/.Setting
s -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x1020000
0'
[debug] [ADB] Device API level: 27
[debug] [ADB] Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\
adb.exe -P 5037 -s 35924c6f0804 shell appops set io.appium.settings android\:moc
k_location allow'
[AndroidDriver] setDeviceLanguageCountry requires language or country.
[AndroidDriver] Got language: 'null' and country: 'null'
[debug] [Logcat] Starting logcat capture
[debug] [AndroidDriver] Pushing unlock helper app to device...
[debug] [ADB] Getting install status for io.appium.unlock
[debug] [ADB] Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\
adb.exe -P 5037 -s 35924c6f0804 shell pm list packages io.appium.unlock'
[debug] [ADB] App is installed
[debug] [ADB] Getting package info for 'io.appium.unlock'
[debug] [ADB] Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\
adb.exe -P 5037 -s 35924c6f0804 shell dumpsys package io.appium.unlock'
[debug] [ADB] The installed 'io.appium.unlock' package does not require upgrade
('2.0.0' >= '2.0.0')
[ADB] Getting device platform version
[debug] [ADB] Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\
adb.exe -P 5037 -s 35924c6f0804 shell getprop ro.build.version.release'
[debug] [ADB] Current device property 'ro.build.version.release': 8.1.0
[debug] [ADB] Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\
adb.exe -P 5037 -s 35924c6f0804 shell wm size'
[debug] [ADB] Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\
adb.exe -P 5037 -s 35924c6f0804 shell getprop ro.product.model'
[debug] [ADB] Current device property 'ro.product.model': Redmi Note 5
[debug] [ADB] Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\
adb.exe -P 5037 -s 35924c6f0804 shell getprop ro.product.manufacturer'
[debug] [ADB] Current device property 'ro.product.manufacturer': Xiaomi
[AndroidDriver] No app sent in, not parsing package/activity
[debug] [AndroidDriver] No app capability. Assuming it is already on the device
[debug] [ADB] Getting install status for com.miui.calculator
[debug] [ADB] Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\
adb.exe -P 5037 -s 35924c6f0804 shell pm list packages com.miui.calculator'
[debug] [ADB] App is installed
[debug] [ADB] Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\
adb.exe -P 5037 -s 35924c6f0804 shell am force-stop com.miui.calculator'
[debug] [ADB] Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\
adb.exe -P 5037 -s 35924c6f0804 shell pm clear com.miui.calculator'
[debug] [AndroidDriver] Performed fast reset on the installed 'com.miui.calculat
or' application (stop and clear)
[debug] [AndroidBootstrap] Watching for bootstrap disconnect
[debug] [ADB] Forwarding system: 4724 to device: 4724
[debug] [ADB] Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\
adb.exe -P 5037 -s 35924c6f0804 forward tcp\:4724 tcp\:4724'
[debug] [UiAutomator] Starting UiAutomator
[debug] [UiAutomator] Moving to state 'starting'
[debug] [UiAutomator] Parsing uiautomator jar
[debug] [UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[debug] [ADB] Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\
adb.exe -P 5037 -s 35924c6f0804 push C\:\\Users\\Office\\AppData\\Roaming\\npm\\
node_modules\\appium\\node_modules\\appium-android-driver\\bootstrap\\bin\\Appiu
mBootstrap.jar /data/local/tmp/'
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\
adb.exe -P 5037 -s 35924c6f0804 shell ps'
[ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Starting UIAutomator
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","35924c6f0804",
"shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bo
otstrap.Bootstrap","-e","pkg","com.miui.calculator","-e","disableAndroidWatchers
",false,"-e","acceptSslCerts",false]
[debug] [UiAutomator] Moving to state 'online'
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Registered crash watchers.
uncaughtException: Android bootstrap socket crashed: Error: getaddrinfo ENOENT u
ndefined:4724
        {"date":"Wed Oct 24 2018 13:13:14 GMT+0530 (India Standard Time)","proce
ss":{"pid":6296,"uid":null,"gid":null,"cwd":"C:\\Users\\Office","execPath":"C:\\
Program Files\\nodejs\\node.exe","version":"v8.12.0","argv":["C:\\Program Files\
\nodejs\\node.exe","C:\\Users\\Office\\AppData\\Roaming\\npm\\node_modules\\appi
um\\build\\lib\\main.js"],"memoryUsage":{"rss":142438400,"heapTotal":117452800,"
heapUsed":86677192,"external":1589859}},"os":{"loadavg":[0,0,0],"uptime":9296.91
70149},"trace":[{"column":21,"file":"C:\\Users\\Office\\AppData\\Roaming\\npm\\n
ode_modules\\appium\\node_modules\\appium-android-driver\\lib\\bootstrap.js","fu
nction":null,"line":97,"method":null,"native":false},{"column":13,"file":"events
.js","function":"emitOne","line":116,"method":null,"native":false},{"column":7,"
file":"events.js","function":"Socket.emit","line":211,"method":"emit","native":f
alse},{"column":8,"file":"internal/streams/destroy.js","function":"emitErrorNT",
"line":66,"method":null,"native":false},{"column":11,"file":"internal/process/ne
xt_tick.js","function":"_combinedTickCallback","line":139,"method":null,"native"
:false},{"column":9,"file":"internal/process/next_tick.js","function":"process._
tickCallback","line":181,"method":"_tickCallback","native":false}],"stack":["Err
or: Android bootstrap socket crashed: Error: getaddrinfo ENOENT undefined:4724",
"    at Socket.<anonymous> (C:\\Users\\Office\\AppData\\Roaming\\npm\\node_modul
es\\appium\\node_modules\\appium-android-driver\\lib\\bootstrap.js:97:21)","
at emitOne (events.js:116:13)","    at Socket.emit (events.js:211:7)","    at em
itErrorNT (internal/streams/destroy.js:66:8)","    at _combinedTickCallback (int
ernal/process/next_tick.js:139:11)","    at process._tickCallback (internal/proc
ess/next_tick.js:181:9)"]}

**Comment by SrinivasanTarget** [comment]
Try UIA2 mode or Espresso mode as automation name
