### ISSUE TITLE
Exception in thread "main" java.lang.AbstractMethodError: 

### ISSUE THREAD

**Issue by kigkrazy** [appium/java-client#1052]
## Description
error
```
Exception in thread "main" java.lang.AbstractMethodError: org.openqa.selenium.remote.DesiredCapabilities.is(Ljava/lang/String;)Z
	at org.openqa.selenium.remote.RemoteWebDriver.init(RemoteWebDriver.java:163)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:123)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:93)
	at com.reizx.register.App.initAppiumEnv(App.java:44)
	at com.reizx.register.App.main(App.java:18)
```

## Environment
dependencies :
```
dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile('com.google.guava:guava:21.0')
    compile 'com.reizx:jor:0.1.1'
    compile group: 'org.jooq', name: 'joor-java-6', version: '0.9.8'
    compile 'com.google.code.gson:gson:2.8.5'
    compile 'cn.hutool:hutool-all:4.1.19'
    compileOnly 'org.projectlombok:lombok:1.18.2'
    apt 'org.projectlombok:lombok:1.18.2'

    //appium 环境包
    // https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-server-standalone
    compile group: 'org.seleniumhq.selenium', name: 'selenium-server-standalone', version: '2.53.0'
    // https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java
    compile group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '3.14.0'
    // https://mvnrepository.com/artifact/io.appium/java-client
    compile group: 'io.appium', name: 'java-client', version: '6.1.0'
}
```

App.java
```
    public static void initAppiumEnv() throws MalformedURLException {
        String apkPath = App.class.getClassLoader().getResource("asf.apk").getPath();//APK路径
        String chromeDriver = App.class.getClassLoader().getResource("driver/2.14/chromedriver.exe").getPath();//驱动路径

        DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
//        desiredCapabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.3");
        desiredCapabilities.setCapability("chromedriverExecutable", "F:\\tools\\Android\\chrome_driver\\2.14\\chromedriver.exe");
        //desiredCapabilities.setCapability("chromedriverExecutable", chromeDriver);
        desiredCapabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
//        desiredCapabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Android");
        desiredCapabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "UiAutomator2");
        desiredCapabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 300);

        //APP信息设置
        desiredCapabilities.setCapability(MobileCapabilityType.APP, "D:\\tmp\\asf.apk");
//        desiredCapabilities.setCapability(MobileCapabilityType.APP, apkPath);
        desiredCapabilities.setCapability("appPackage", "com.reizx.asf");
        desiredCapabilities.setCapability("appActivity", "com.reizx.asf.view.MainActivity");
        URL url = new URL("http://127.0.0.1:4723/wd/hub");
        //设置全局信息
        App.driver = new AndroidDriver(url, desiredCapabilities);
        App.context = AppContext.getAppContext();
        context.setDriver(App.driver);
    }
```
* java client build version or git revision if you use some shapshot:
* Appium server version or git revision if you use some shapshot:
* Desktop OS/version used to run Appium if necessary:
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test:
* Real device or emulator/simulator:

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.
You can git clone https://github.com/appium/sample-code or https://github.com/appium/sample-code/tree/master/sample-code/apps and reproduce an issue using Java and sample apps.
Also you can create a [gist](https://gist.github.com) with pasted java code sample or put it here using markdown. About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and 
[Writing on GitHub](https://help.github.com/categories/writing-on-github/)

## Ecxeption stacktraces

Please create a [gist](https://gist.github.com) with pasted stacktrace of exception thrown by java.

## Link to Appium logs

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly. 
`

**Comment by kigkrazy** [comment]
I solved it!!!
The solution is as follows: remove `selenium-server-standalone` and `selenium-java` dependences.
```
    //appium 环境包
    // https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-server-standalone
    //compile group: 'org.seleniumhq.selenium', name: 'selenium-server-standalone', version: '2.53.0'
    // https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java
    //compile group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '3.14.0'
    // https://mvnrepository.com/artifact/io.appium/java-client
    compile group: 'io.appium', name: 'java-client', version: '6.1.0'
```
