### ISSUE TITLE
hit org.openqa.selenium.UnsupportedCommandException: isKeyboardShown on ios simulator

### ISSUE THREAD

**Issue by helenren** [appium/java-client#1057]
## Description

isKeyboardShown does not work on ios simulator. 

Also tried driver.hideKeyboard(HideKeyboardStrategy.PRESS_KEY, "Done"); while the keyboard did not get closed. 

call stack:

at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:218)
	at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:117)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:152)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:231)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at io.appium.java_client.CommandExecutionHelper.execute(CommandExecutionHelper.java:27)
	at io.appium.java_client.HasOnScreenKeyboard.isKeyboardShown(HasOnScreenKeyboard.java:13)
	at com.salesforce.mobiletest.webdriver.IOSDriverUtilImpl.hideSoftKeyboard(IOSDriverUtilImpl.java:253)

## Environment

* java client build version or git revision if you use some shapshot: 6.1.0
* Appium server version or git revision if you use some shapshot: 1.9.2-beta.2
* Desktop OS/version used to run Appium if necessary:
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: ios 11.4
* Real device or emulator/simulator: simulator

my code is: driver.isKeyboardShown()

**Comment by saikrishna321** [comment]
post server logs pls

**Comment by helenren** [comment]
Here is the logs. While notice that seems call isKeyboardShown not reach the endpoint: /wd/hub/session/:session_id/appium/device/is_keyboard_shown. @saikrishna321 
[appiumlogs.txt](https://github.com/appium/java-client/files/2582482/appiumlogs.txt)

**Comment by helenren** [comment]
any hint? @saikrishna321

**Comment by saikrishna321** [comment]
@helenren please try with latest appium version and also make sure you have the latest WDA installed from appium module. 

FYI: i don't see any is_keyboard_shown call in the logs
