### ISSUE TITLE
Problem with running getClipboardText() method on Android Emulator.

### ISSUE THREAD

**Issue by mszumilas** [appium/java-client#1072]
## Description

Method ((HasClipboard) driver).getClipboardText() is not working on Android Emulator. During running I get org.openqa.selenium.UnsupportedCommandException: Method has not yet been implemented

## Environment

* java client build version or git revision if you use some shapshot: 6.1.0
* Appium server version or git revision if you use some shapshot: Appium v1.10.0
* Desktop OS/version used to run Appium if necessary: macOS Mojave v. 10.14.1 
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: node v8.9.4, 
* Mobile platform/version under test: Android 8.1
* Real device or emulator/simulator: emulator

## Details

On iOS Simulator it works just fine. The problem occurs when I run the same tests on Android Emulator.

## Code To Reproduce Issue 

String result = ((HasClipboard) driver).getClipboardText();
        System.out.println(result);

## Exception stacktrace

`org.openqa.selenium.UnsupportedCommandException: Method has not yet been implemented
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'Main-Mac-mini.local', ip: '', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.1', java.version: '1.8.0_191'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {app: appPath, appActivity: appActivity , appPackage: appPackage, appWaitActivity: appWaitActivity, appWaitPackage: appWaitPackage, databaseEnabled: false, desired: {app: app, appWaitActivity: appWaitActivity, deviceName: Android Emulator, platformName: android, platformVersion: 8.1}, deviceManufacturer: Google, deviceModel: Android SDK built for x86, deviceName: emulator-5554, deviceScreenSize: 1080x1920, deviceUDID: emulator-5554, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, platform: LINUX, platformName: Android, platformVersion: 8.1.0, takesScreenshot: true, warnings: {}, webStorageEnabled: false}
Session ID:

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:231)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at io.appium.java_client.CommandExecutionHelper.execute(CommandExecutionHelper.java:27)
	at io.appium.java_client.clipboard.HasClipboard.getClipboard(HasClipboard.java:53)
	at io.appium.java_client.clipboard.HasClipboard.getClipboardText(HasClipboard.java:76)
        at screens.Screen.getTextFromClipboard(AccountNumbersScreen.java:116)`

## Link to Appium logs

**Comment by mykola-mokhnach** [comment]
The method is only available for UIA2 backend
