### ISSUE TITLE
A node test that matches either NCName:* or QName was expected.

### ISSUE THREAD

**Issue by rajkumar-cp** [appium/java-client#1104]
## Description

Not able to locate an element using the xpath

## Environment

* java client build version or git revision if you use some shapshot: 1.8
* Appium server version or git revision if you use some shapshot:1.10
* Desktop OS/version used to run Appium if necessary:
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: android 7
* Real device or emulator/simulator: emulator

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.
You can git clone https://github.com/appium/sample-code or https://github.com/appium/sample-code/tree/master/sample-code/apps and reproduce an issue using Java and sample apps.
Also you can create a [gist](https://gist.github.com) with pasted java code sample or put it here using markdown. About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and 
[Writing on GitHub](https://help.github.com/categories/writing-on-github/)

## Ecxeption stacktraces
 An unknown server-side error occurred while processing the command. Original error: Cannot get screenshot data because of 'The size of the taken screenshot equals to zero.'. Make sure the 'LayoutParams.FLAG_SECURE' is not set for the current view (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 3.47 seconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'Aspire1931', ip: '10.8.19.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_161'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{appPackage=com.mfiles.mobile, deviceName=emulator-5556, platform=LINUX, deviceUDID=emulator-5556, noHistory=true, androidInstallTimeout=180000, desired={appPackage=com.mfiles.mobile, app=C:/Applications/develop-2018-12-28_22-39.apk, rotatable=true, deviceName=emulator-5556, appActivity=com.mfiles.mobile.activity.SplashActivity, noHistory=true, androidInstallTimeout=180000, platformVersion=7.0, adbExecTimeout=180000, autoGrantPermissions=true, unicodeKeyboard=true, udid=emulator-5556, platformName=Android, LAUNCH_TIMEOUT=1000000, device=Android, autoAcceptAlerts=true}, platformVersion=7.0, webStorageEnabled=false, takesScreenshot=true, javascriptEnabled=true, unicodeKeyboard=true, udid=emulator-5556, platformName=Android, deviceManufacturer=unknown, app=C:/Applications/develop-2018-12-28_22-39.apk, rotatable=true, deviceScreenSize=1024x600, networkConnectionEnabled=true, warnings={}, databaseEnabled=false, appActivity=com.mfiles.mobile.activity.SplashActivity, adbExecTimeout=180000, locationContextEnabled=false, autoGrantPermissions=true, deviceModel=sdk_phone_armv7, LAUNCH_TIMEOUT=1000000, device=Android, autoAcceptAlerts=true}]
Session ID: e5553d58-5b87-4982-ab07-3a782c93d6db
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:51)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:268)
	at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:335)
	at genericLibrary.Log.exception(Log.java:509)
	at MFMA.Tests.CompilanceKit.editStartDateofTask(CompilanceKit.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
08-Feb-2019 10:53:56:063 FATAL [main] Exception at ObjectProperties.setInfo : Exception at ObjectProperties.setProperty : javax.xml.transform.TransformerException: A node test that matches either NCName:* or QName was expected. (WARNING: The server did not provide any stacktrace information) 
java.lang.Exception: Exception at ObjectProperties.setInfo : Exception at ObjectProperties.setProperty : javax.xml.transform.TransformerException: A node test that matches either NCName:* or QName was expected. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 193 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'Aspire1931', ip: '10.8.19.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_161'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{appPackage=com.mfiles.mobile, deviceName=emulator-5556, platform=LINUX, deviceUDID=emulator-5556, noHistory=true, androidInstallTimeout=180000, desired={appPackage=com.mfiles.mobile, app=C:/Applications/develop-2018-12-28_22-39.apk, rotatable=true, deviceName=emulator-5556, appActivity=com.mfiles.mobile.activity.SplashActivity, noHistory=true, androidInstallTimeout=180000, platformVersion=7.0, adbExecTimeout=180000, autoGrantPermissions=true, unicodeKeyboard=true, udid=emulator-5556, platformName=Android, LAUNCH_TIMEOUT=1000000, device=Android, autoAcceptAlerts=true}, platformVersion=7.0, webStorageEnabled=false, takesScreenshot=true, javascriptEnabled=true, unicodeKeyboard=true, udid=emulator-5556, platformName=Android, deviceManufacturer=unknown, app=C:/Applications/develop-2018-12-28_22-39.apk, rotatable=true, deviceScreenSize=1024x600, networkConnectionEnabled=true, warnings={}, databaseEnabled=false, appActivity=com.mfiles.mobile.activity.SplashActivity, adbExecTimeout=180000, locationContextEnabled=false, autoGrantPermissions=true, deviceModel=sdk_phone_armv7, LAUNCH_TIMEOUT=1000000, device=Android, autoAcceptAlerts=true}]
Session ID: e5553d58-5b87-4982-ab07-3a782c93d6db
*** Element info: {Using=xpath, value=//*[contains(@text,'ACTIVATION')]/following-sibling::[@class='android.widget.LinearLayout']}
	at MFMA.Factories.ObjectProperties.setInfo(ObjectProperties.java:2384)
	at MFMA.Tests.CompilanceKit.editStartDateofTask(CompilanceKit.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.Exception: Exception at ObjectProperties.setProperty : javax.xml.transform.TransformerException: A node test that matches either NCName:* or QName was expected. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 193 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'Aspire1931', ip: '10.8.19.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_161'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{appPackage=com.mfiles.mobile, deviceName=emulator-5556, platform=LINUX, deviceUDID=emulator-5556, noHistory=true, androidInstallTimeout=180000, desired={appPackage=com.mfiles.mobile, app=C:/Applications/develop-2018-12-28_22-39.apk, rotatable=true, deviceName=emulator-5556, appActivity=com.mfiles.mobile.activity.SplashActivity, noHistory=true, androidInstallTimeout=180000, platformVersion=7.0, adbExecTimeout=180000, autoGrantPermissions=true, unicodeKeyboard=true, udid=emulator-5556, platformName=Android, LAUNCH_TIMEOUT=1000000, device=Android, autoAcceptAlerts=true}, platformVersion=7.0, webStorageEnabled=false, takesScreenshot=true, javascriptEnabled=true, unicodeKeyboard=true, udid=emulator-5556, platformName=Android, deviceManufacturer=unknown, app=C:/Applications/develop-2018-12-28_22-39.apk, rotatable=true, deviceScreenSize=1024x600, networkConnectionEnabled=true, warnings={}, databaseEnabled=false, appActivity=com.mfiles.mobile.activity.SplashActivity, adbExecTimeout=180000, locationContextEnabled=false, autoGrantPermissions=true, deviceModel=sdk_phone_armv7, LAUNCH_TIMEOUT=1000000, device=Android, autoAcceptAlerts=true}]
Session ID: e5553d58-5b87-4982-ab07-3a782c93d6db
*** Element info: {Using=xpath, value=//*[contains(@text,'ACTIVATION')]/following-sibling::[@class='android.widget.LinearLayout']}
	at MFMA.Factories.ObjectProperties.setProperty(ObjectProperties.java:2785)
	at MFMA.Factories.ObjectProperties.setInfo(ObjectProperties.java:2380)
	... 25 more
Caused by: org.openqa.selenium.InvalidSelectorException: javax.xml.transform.TransformerException: A node test that matches either NCName:* or QName was expected. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 193 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'Aspire1931', ip: '10.8.19.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_161'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{appPackage=com.mfiles.mobile, deviceName=emulator-5556, platform=LINUX, deviceUDID=emulator-5556, noHistory=true, androidInstallTimeout=180000, desired={appPackage=com.mfiles.mobile, app=C:/Applications/develop-2018-12-28_22-39.apk, rotatable=true, deviceName=emulator-5556, appActivity=com.mfiles.mobile.activity.SplashActivity, noHistory=true, androidInstallTimeout=180000, platformVersion=7.0, adbExecTimeout=180000, autoGrantPermissions=true, unicodeKeyboard=true, udid=emulator-5556, platformName=Android, LAUNCH_TIMEOUT=1000000, device=Android, autoAcceptAlerts=true}, platformVersion=7.0, webStorageEnabled=false, takesScreenshot=true, javascriptEnabled=true, unicodeKeyboard=true, udid=emulator-5556, platformName=Android, deviceManufacturer=unknown, app=C:/Applications/develop-2018-12-28_22-39.apk, rotatable=true, deviceScreenSize=1024x600, networkConnectionEnabled=true, warnings={}, databaseEnabled=false, appActivity=com.mfiles.mobile.activity.SplashActivity, adbExecTimeout=180000, locationContextEnabled=false, autoGrantPermissions=true, deviceModel=sdk_phone_armv7, LAUNCH_TIMEOUT=1000000, device=Android, autoAcceptAlerts=true}]
Session ID: e5553d58-5b87-4982-ab07-3a782c93d6db
*** Element info: {Using=xpath, value=//*[contains(@text,'ACTIVATION')]/following-sibling::[@class='android.widget.LinearLayout']}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:51)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:67)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:500)
	at io.appium.java_client.DefaultGenericMobileDriver.findElementByXPath(DefaultGenericMobileDriver.java:145)
	at io.appium.java_client.AppiumDriver.findElementByXPath(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElementByXPath(AndroidDriver.java:1)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:63)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
	at MFMA.Factories.ObjectProperties.setProperty(ObjectProperties.java:2508)
	... 26 more

## Link to Appium logs

[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 1000 ms for condition
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//*[contains(@text,'ACTIVATION')]/following-sibling::[@class='android.widget.LinearLayout']","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//*[contains(@text,'ACTIVATION')]/following-sibling::[@class='android.widget.LinearLayout']","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding '//*[contains(@text,'ACTIVATION')]/following-sibling::[@class='android.widget.LinearLayout']' using 'XPATH' with the contextId: '' multiple: false
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":32,"value":"javax.xml.transform.TransformerException: A node test that matches either NCName:* or QName was expected."}

**Comment by saikrishna321** [comment]
Please use _automationName_ as UIAutomator2

**Comment by rajkumar-cp** [comment]
@saikrishna321 
i have added that capability.

Could you please refer to https://github.com/appium/appium/issues/12589
