### ISSUE TITLE
Getting "Method has not yet been implemented" error when try to do a vertical swipe.

### ISSUE THREAD

**Issue by srikantharuban** [appium/java-client#1116]
Java-client - 7.0.0
Appium server - 11

Executed code 

 private static void verticalSwipe(String locator) throws InterruptedException {
	        System.out.println(androiddriver.getContext());
	        
		  	Thread.sleep(3000);
	        AndroidElement slider = androiddriver.findElementById(locator);
	        Point source = slider.getCenter();
	        
	        PointerInput finger = new PointerInput(PointerInput.Kind.TOUCH, "finger");
	        Sequence dragNDrop = new Sequence(finger, 1);
	        dragNDrop.addAction(finger.createPointerMove(Duration.ofMillis(0),
	                PointerInput.Origin.viewport(),
	                source.x +400, source.y/2));
	        dragNDrop.addAction(finger.createPointerDown(PointerInput.MouseButton.MIDDLE.asArg()));
	        dragNDrop.addAction(finger.createPointerMove(Duration.ofMillis(600),
	                PointerInput.Origin.viewport(), source.getX() +400, source.y / 2));
	        dragNDrop.addAction(finger.createPointerUp(PointerInput.MouseButton.MIDDLE.asArg()));
	        androiddriver.context("NATIVE_APP");
	        
	        androiddriver.perform(Arrays.asList(dragNDrop)); - Error generated in this line
	        
	        
	    }

Generated error 

Mar 08, 2019 12:30:45 PM io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0
INFO: Detected dialect: W3C
NATIVE_APP
Mar 08, 2019 12:30:55 PM org.openqa.selenium.remote.ErrorCodes toStatus
INFO: HTTP Status: '404' -> incorrect JSON status mapping for 'unknown method' (405 expected)
Exception in thread "main" org.openqa.selenium.UnsupportedCommandException: Method has not yet been implemented
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Srikantharubans-MacBook-Pro.local', ip: 'fe80:0:0:0:1898:1221:f740:9f2b%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.3', java.version: '10'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {appActivity: com.google.android.apps.mes..., appPackage: com.google.android.apps.mes..., autoAcceptAlerts: true, autoGrantPermissions: true, avd: Nexus_5X_API_28, databaseEnabled: false, desired: {appActivity: com.google.android.apps.mes..., appPackage: com.google.android.apps.mes..., autoAcceptAlerts: true, autoGrantPermissions: true, avd: Nexus_5X_API_28, deviceName: Android, platformName: android}, deviceManufacturer: Google, deviceModel: Android SDK built for x86, deviceName: emulator-5554, deviceScreenSize: 1080x1920, deviceUDID: emulator-5554, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, platform: LINUX, platformName: Android, platformVersion: 9, takesScreenshot: true, warnings: {}, webStorageEnabled: false}
Session ID: fef0600b-7916-4e97-b22c-7725532c26f3
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.perform(RemoteWebDriver.java:618)
	at com.qa.appium.base.BaseClass.verticalSwipe(BaseClass.java:116)
	at com.qa.appium.base.BaseClass.main(BaseClass.java:89)

**Comment by srikantharuban** [comment]
Resolved the issue.

Thanks,
Srikanth.

**Comment by Mishrask637** [comment]
How the error got resolved, can you please explain?
Facing same issue on my machine.
Thanks,
Suraj
