### ISSUE TITLE
issues with java client : unable to create remote session

### ISSUE THREAD

**Issue by Krisgk1** [appium/java-client#1121]
## Description

Getting the following Exception while 

**Unable to create a new remote session. Original error: okio.BufferedSource.readUtf8LineStrict(J)Ljava/lang/String;**

In the following code

 appiumDriver = new AndroidDriver(new URL("http:/0:0:0:0:4723/wd/hub"), desiredCapabilities);

Tried localhost and 127.0.0.1 as well

**Note : The same code works fine for 4.1.2 java-client and Appium 1.9.1 but doesn't work for 7.0.0 client or 6.1.0 client**

## Environment

* java client build version or git revision if you use some shapshot:
7.0.0 and 6.1.0
* Appium server version or git revision if you use some shapshot:
1.11.1 and 1.9.1
* Desktop OS/version used to run Appium if necessary:
Mac OS Sierra and Mojave
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
11.11.0
* Mobile platform/version under test:
Android and iOS too
* Real device or emulator/simulator:
Ram device and Simulators
## Details

Please provide more details, if necessary.

Note : The same code works fine for 4.1.2 java-client
## Code To Reproduce Issue [ Good To Have ]

appiumDriver = new AndroidDriver(new URL("http:/0:0:0:0:4723/wd/hub"), desiredCapabilities);

## Ecxeption stacktraces

Please create a [gist](https://gist.github.com) with pasted stacktrace of exception thrown by java.

## Link to Appium logs

[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"app":"/android/test/app-test-10.5.1568.apk","appActivity":"com.test.activities.LauncherActivity","appPackage":"com.test.dev","automationName":"UiAutoWent to tear down
mator2","platformName":"Android","deviceName":"SamsungS7","fullReset":true},null,{"firstMatch":[{"appium:app":/android/test/app-test-10.5.1568.apk","appium:appActivity":"com.activities.LauncherActivity","appium:appPackage":"com.ttest.dev","appium:automationName":"UiAutomator2","appium:deviceName":"SamsungS7","appium:fullReset":true,"platformName":"android"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1552392797229 (12:13:17 GMT+0000 (Greenwich Mean Time))
[Appium] Creating new AndroidUiautomator2Driver (v1.29.1) session
[Appium] Capabilities:
[Appium]   platformName: android
[Appium]   app: android/test/app-test-10.5.1568.apk
[Appium]   appActivity: com.test.activities.LauncherActivity
[Appium]   appPackage: com.test.dev
[Appium]   automationName: UiAutomator2
[Appium]   deviceName: SamsungS7
[Appium]   fullReset: true

Driver info: driver.version: AndroidDriver
	at org.junit.Assert.fail(Assert.java:88)
	at drivers.Drivers.getDriver(Drivers.java:229)
	at runner.RunTest.setUp(RunTest.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:100)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

**Comment by jshinn6788** [comment]
Hi, I am having this same issue.

**Comment by amitrparmar** [comment]
I am also facing the same issue.

Xcode : 10.1
Appium: 1.12.0
Java 13
Appium Java Client : 7.2.0

**Comment by amitrparmar** [comment]
I have also tried on Appium beta but same issue

1.16.0-beta.3

**Comment by yadsandy** [comment]
I am also facing the same issue when I am using java-client 7.2.0.
Any solution please.
