### ISSUE TITLE
Unable to create HTTP client factory when starting appium server

### ISSUE THREAD

**Issue by aldochristiaan** [appium/java-client#1205]
## Description

After upgrading to java client 7.1.0, AppiumDriverLocalService is not working as expected.
It throws java.lang.ExceptionInInitializerError.

## Environment

* java client build version : 7.1.0
* Appium server version : 1.14.1

## Details

I got this error when staring appium service.

```
java.lang.ExceptionInInitializerError
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:106)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:117)
	at id.aldochristiaan.salad.Salad.start(Salad.java:85)
	at bukalapak.mitra.MitraFactory.setUp(MitraFactory.java:38)
	at bukalapak.mitra.steps.Hooks.lambda$new$0(Hooks.java:13)
	at cucumber.runtime.java8.Java8HookDefinition.lambda$execute$1(Java8HookDefinition.java:61)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.java8.Java8HookDefinition.execute(Java8HookDefinition.java:57)
	at cucumber.runner.HookDefinitionMatch.runStep(HookDefinitionMatch.java:16)
	at cucumber.runner.TestStep.executeStep(TestStep.java:65)
	at cucumber.runner.TestStep.run(TestStep.java:50)
	at cucumber.runner.TestCase.run(TestCase.java:42)
	at cucumber.runner.Runner.runPickle(Runner.java:50)
	at cucumber.runtime.Runtime$1.run(Runtime.java:104)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at cucumber.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:258)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at cucumber.runtime.Runtime.run(Runtime.java:101)
	at io.cucumber.core.cli.Main.run(Main.java:43)
	at io.cucumber.core.cli.Main.main(Main.java:14)
Caused by: java.lang.UnsupportedOperationException: Unable to create HTTP client factory
	at org.openqa.selenium.remote.http.HttpClient$Factory.createDefault(HttpClient.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.<clinit>(HttpCommandExecutor.java:48)
	... 21 more
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.remote.internal.OkHttpClient$Factory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.openqa.selenium.remote.http.HttpClient$Factory.createDefault(HttpClient.java:69)
	... 22 more
```

So I created appium java-client wrapper inside this repo : https://github.com/aldochristiaan/salad/tree/develop

Everything is working fine when I use version 7.0.0 ..

## Code To Reproduce Issue [ Good To Have ]

The code will break at this line:
https://github.com/aldochristiaan/salad/blob/develop/src/main/java/id/aldochristiaan/salad/Salad.java#L82

Did I miss something ? 
I tried to upgrade and downgrade selenium-java library inside java-client, but still can't works ..

**Comment by aldochristiaan** [comment]
After upgrading to 7.2.0 , this issue not happened again.
Some class missing in selenium-java 4-alpha-x.
Thanks @SrinivasanTarget for downgrading the library!
💯
