### ISSUE TITLE
Appium Log error - he capabilities ["no","noRest","app","automationName","deviceName","newCommandTimeout"] are not standard capabilities and should have an extension prefix

### ISSUE THREAD

**Issue by tester921** [appium/java-client#1303]
Please help me to solve below Appium log error.

C:\Users\HP>appium
[Appium] Welcome to Appium v1.16.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"C:\\Users\\HP\\eclipse-workspace\\Tutorial\\src\\ApiDemos-debug.apk","no":true,"newCommandTimeout":100000,"automationName":"uiautomator","browserName":"","platformName":"Android","deviceName":"SSAA","noRest":true},"capabilities":{"firstMatch":[{"appium:app":"C:\\Users\\HP\\eclipse-workspace\\Tutorial\\src\\ApiDemos-debug.apk","appium:automationName":"uiautomator","browserName":"","appium:deviceName":"SSAA","appium:newCommandTimeout":100000,"no":true,"noRest":true,"platformName":"android"}]}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"app":"C:\\Users\\HP\\eclipse-workspace\\Tutorial\\src\\ApiDemos-debug.apk","no":true,"newCommandTimeout":100000,"automationName":"uiautomator","browserName":"","platformName":"Android","deviceName":"SSAA","noRest":true},null,{"firstMatch":[{"appium:app":"C:\\Users\\HP\\eclipse-workspace\\Tutorial\\src\\ApiDemos-debug.apk","appium:automationName":"uiautomator","browserName":"","appium:deviceName":"SSAA","appium:newCommandTimeout":100000,"no":true,"noRest":true,"platformName":"android"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1581245684511 (16:24:44 GMT+0530 (India Standard Time))
[BaseDriver] The capabilities ["no","noRest"] are not standard capabilities and should have an extension prefix
[Appium] Could not parse W3C capabilities: 'automationName' uiautomator not part of Appium,UiAutomator2,UiAutomator1,XCUITest,YouiEngine,Espresso,Tizen,Fake,Instruments,Windows,Mac,Flutter
[Appium] Trying to fix W3C capabilities by merging them with JSONWP caps
[BaseDriver] The capabilities ["no","noRest","app","automationName","deviceName","newCommandTimeout"] are not standard capabilities and should have an extension prefix
[Appium] Could not parse fixed W3C capabilities: 'automationName' uiautomator not part of Appium,UiAutomator2,UiAutomator1,XCUITest,YouiEngine,Espresso,Tizen,Fake,Instruments,Windows,Mac,Flutter. Falling back to JSONWP protocol
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1581245684540 (16:24:44 GMT+0530 (India Standard Time))
[debug] [MJSONWP] Encountered internal error running command: Error: Could not find a driver for automationName 'uiautomator' and platformName 'Android'. Please check your desired capabilities.
[debug] [MJSONWP]     at AppiumDriver.getDriverAndVersionForCaps (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\lib\appium.js:231:11)
[debug] [MJSONWP]     at AppiumDriver.createSession (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\lib\appium.js:305:66)
[debug] [MJSONWP]     at commandExecutor (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:330:9)
[debug] [MJSONWP]     at AppiumDriver.executeCommand (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:344:15)
[debug] [MJSONWP]     at AppiumDriver.executeCommand (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\lib\appium.js:496:26)
[debug] [MJSONWP]     at asyncHandler (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:306:34)
[debug] [MJSONWP]     at C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:432:15
[debug] [MJSONWP]     at Layer.handle [as handle_request] (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[debug] [MJSONWP]     at next (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\route.js:137:13)
[debug] [MJSONWP]     at Route.dispatch (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\route.js:112:3)
[debug] [MJSONWP]     at Layer.handle [as handle_request] (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[debug] [MJSONWP]     at C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:281:22
[debug] [MJSONWP]     at Function.process_params (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:335:12)
[debug] [MJSONWP]     at next (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:275:10)
[debug] [MJSONWP]     at logger (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\morgan\index.js:144:5)[debug] [MJSONWP]     at Layer.handle [as handle_request] (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[debug] [MJSONWP]     at trim_prefix (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:317:13)
[debug] [MJSONWP]     at C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:284:7
[debug] [MJSONWP]     at Function.process_params (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:335:12)
[debug] [MJSONWP]     at next (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:275:10)
[debug] [MJSONWP]     at C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\body-parser\lib\read.js:130:5
[debug] [MJSONWP]     at invokeCallback (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\raw-body\index.js:224:16)
[HTTP] <-- POST /wd/hub/session 500 282 ms - 261

Below is the Eclispe error:

Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Could not find a driver for automationName 'uiautomator' and platformName 'Android'. Please check your desired capabilities. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 514 milliseconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'LAPTOP-FAL4RLNI', ip: '192.168.43.47', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_241'
Driver info: driver.version: AndroidDriver
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'LAPTOP-FAL4RLNI', ip: '192.168.43.47', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_241'
Driver info: driver.version: AndroidDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:336)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:98)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:94)
	at Base.main(Base.java:41)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
	... 14 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not find a driver for automationName 'uiautomator' and platformName 'Android'. Please check your desired capabilities. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 514 milliseconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'LAPTOP-FAL4RLNI', ip: '192.168.43.47', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_241'
Driver info: driver.version: AndroidDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$errorHandler$0(JsonWireProtocolResponse.java:54)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	... 19 more

**Comment by cheffey** [comment]
ignore the "not standard capabilities" log

why don't use:
 automationName: UiAutomator2

noReset is misspelled
