### ISSUE TITLE
INSTALL_FAILED_INSUFFICIENT_STORAGE

### ISSUE THREAD

**Issue by wulfihm** [appium/java-client#1359]
Hi, a really short issue. I am using the latest release v7.3.0.

This problem is related to android. See: https://stackoverflow.com/questions/4709137/solution-to-install-failed-insufficient-storage-error-on-android

I ran into this issue because I have multiple test and I am doing a fullReset after every test via the capability `cap.setCapability(MobileCapabilityType.FULL_RESET, true);`.

My workaround currently looks like this:
```
       List<String> args = Arrays.asList(
                "-rf",
                " /data/app/[package_name]-*"
        );
        Map<String, Object> cmd = ImmutableMap.of(
                "command", "rm",
                "args", args
        );
        this.executeScript("mobile: shell", cmd);
```

But I guess it would be nice if this would be build into the code that does the fullreset itself.
If anyone is willing to do this or can point me to the code where the fullreset is done I would be more than happy to do a PR.

The logs if you're interested:
```
2020-06-12 11:57:40:532 - [debug] [AndroidDriver] Running full reset on 'de.android.mycrocast' (reinstall)
2020-06-12 11:57:40:532 - [debug] [ADB] Uninstalling de.android.mycrocast
2020-06-12 11:57:40:532 - [debug] [ADB] Getting install status for de.android.mycrocast
2020-06-12 11:57:40:532 - [debug] [ADB] Running 'C:\Users\Hans\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package de.android.mycrocast'
2020-06-12 11:57:40:751 - [debug] [ADB] 'de.android.mycrocast' is installed
2020-06-12 11:57:40:751 - [debug] [ADB] Running 'C:\Users\Hans\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am force-stop de.android.mycrocast'
2020-06-12 11:57:41:031 - [debug] [ADB] Running 'C:\Users\Hans\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 uninstall de.android.mycrocast'
2020-06-12 11:57:41:317 - [debug] [ADB] 'adb uninstall de.android.mycrocast' command output: Success
2020-06-12 11:57:41:317 - [ADB] de.android.mycrocast was successfully uninstalled
2020-06-12 11:57:41:317 - [ADB] The application at 'C:\Users\hans\Documents\de.android.mycrocast.apk' will not be cached, because the device under test has confirmed the support of streamed installs
2020-06-12 11:57:41:317 - [debug] [ADB] Running 'C:\Users\Hans\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 install -r C:\\Users\\hans\\Documents\\de.android.mycrocast.apk'
2020-06-12 11:57:44:497 - [debug] [W3C (75c9bb6c)] Encountered internal error running command: Error executing adbExec. Original error: 'Command 'C:\\Users\\Hans\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 install -r C:\\Users\\hans\\Documents\\de.android.mycrocast.apk' exited with code 1'; Stderr: 'adb: failed to install C:\Users\hans\Documents\de.android.mycrocast.apk: Failure [INSTALL_FAILED_INSUFFICIENT_STORAGE]'; Code: '1'
2020-06-12 11:57:44:497 - [debug] [W3C (75c9bb6c)] Error: Command 'C:\\Users\\Hans\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 install -r C:\\Users\\hans\\Documents\\de.android.mycrocast.apk' exited with code 1
2020-06-12 11:57:44:498 - [debug] [W3C (75c9bb6c)]     at ChildProcess.<anonymous> (C:\Users\Hans\AppData\Roaming\npm\node_modules\appium\node_modules\teen_process\lib\exec.js:113:19)
2020-06-12 11:57:44:498 - [debug] [W3C (75c9bb6c)]     at ChildProcess.emit (events.js:315:20)
2020-06-12 11:57:44:498 - [debug] [W3C (75c9bb6c)]     at maybeClose (internal/child_process.js:1021:16)
2020-06-12 11:57:44:498 - [debug] [W3C (75c9bb6c)]     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
2020-06-12 11:57:44:560 - [HTTP] <-- POST /wd/hub/session/75c9bb6c-9de4-4493-b65b-9fbf2069d400/appium/app/reset 500 4389 ms - 1359
2020-06-12 11:57:44:561 - [HTTP] 
```

**Comment by wulfihm** [comment]
Nevermind, I just realized this is an appium issue and was apparently already solved in https://github.com/appium/appium/issues/13970 .
