### ISSUE TITLE
Error running on MAC - Cannot call non W3C standard command while in W3C mode 

### ISSUE THREAD

**Issue by juferz** [appium/java-client#1364]
## Hello everyone

I have my test automation script and when i run it on Windows. It works perfectly. But when i try to run it on MAC it fails with the following error:

Cannot call non W3C standard command while in W3C mode

I am running an hybrid app so I am using a chromedriver and run it as webView.

Tools Version
Appium Desktop (server): 1.17.1

Dependencies on build gradle:
    implementation 'io.appium:java-client:master-SNAPSHOT'

My properties with capabilities are:
`serenity.take.screenshots.for.tasks=AFTER_EACH_STEP
serenity.take.screenshots.for.interactions=FOR_FAILURES
serenity.take.screenshots.for.questions=BEFORE_AND_AFTER_EACH_STEP
serenity.report.encoding=UTF-8
serenity.compress.filenames=false
serenity.test.root=net.thucydides.showcase.cucumber.junit
serenity.verbose.steps=FALSE
serenity.use.unique.browser=false
feature.file.encoding=UTF-8
webdriver.timeouts.implicitlywait = 30000
webdriver.wait.for.timeout = 30000
webdriver.driver=appium
appium.platformName=Android
appium.hub=http://127.0.0.1:4723/wd/hub
appium.appPackage=com.proyecto6
appium.appActivity=com.MainActivity
appium.app=
appium.noReset=true
appium.newCommandTimeout=120
appium.autoWebview=true
appium.enablePerformanceLogging=true
appium.autoWebviewTimeout=20000
appium.chromedriverExecutable = /Users/t1qamdemac4/Documents/project/src/test/resources/driver/chromedriver
appium.adbExecTimeout = 30000
appium.platformVersion =7.0
appium.deviceName  = 85b6523638553857
`
Log

`jun 22, 2020 9:20:57 PM io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0
INFORMACIÓN: Detected dialect: W3C
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - 
           __  _____ _____ ____ _____   _____ _    ___ _     _____ ____  
  _       / / |_   _| ____/ ___|_   _| |  ___/ \  |_ _| |   | ____|  _ \ 
 (_)_____| |    | | |  _| \___ \ | |   | |_ / _ \  | || |   |  _| | | | |
  _|_____| |    | | | |___ ___) || |   |  _/ ___ \ | || |___| |___| |_| |
 (_)     | |    |_| |_____|____/ |_|   |_|/_/   \_\___|_____|_____|____/ 
          \_\                                                            

TEST FAILED WITH ERROR: Autenticacion
---------------------------------------------------------------------
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - TEST FAILED AT STEP Dado que el Actor carga los datos para la prueba
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - Could not instantiate new WebDriver instance of type class io.appium.java_client.AppiumDriver (unknown command: Cannot call non W3C standard command while in W3C mode

net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class io.appium.java_client.AppiumDriver

	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:144)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:132)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:102)
	at net.serenitybdd.core.webdriver.RemoteDriver.of(RemoteDriver.java:13)
	at net.thucydides.core.webdriver.appium.AppiumConfiguration.getTargetPlatform(AppiumConfiguration.java:49)
	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.platformFor(ElementLocatorFactorySelector.java:51)
	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.getLocatorFor(ElementLocatorFactorySelector.java:41)
	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.getLocatorFor(ElementLocatorFactorySelector.java:31)
	at net.thucydides.core.annotations.locators.SmartElementProxyCreator.proxyElements(SmartElementProxyCreator.java:21)
	at net.thucydides.core.webdriver.DefaultPageObjectInitialiser.apply(DefaultPageObjectInitialiser.java:19)
	at net.serenitybdd.core.pages.PageObject.setDriver(PageObject.java:166)
	at net.serenitybdd.core.pages.PageObject.setDriver(PageObject.java:170)
	at net.serenitybdd.core.pages.PageObject.<init>(PageObject.java:154)
	at net.serenitybdd.screenplay.abilities.BrowseTheWeb.<init>(BrowseTheWeb.java:31)
	at net.serenitybdd.screenplay.abilities.BrowseTheWeb.with(BrowseTheWeb.java:47)
	at net.serenitybdd.screenplay.actors.OnlineCast.actorNamed(OnlineCast.java:45)
	at net.serenitybdd.screenplay.actors.Stage.lambda$shineSpotlightOn$1(Stage.java:24)
	at java.util.Optional.orElseGet(Optional.java:267)
	at net.serenitybdd.screenplay.actors.Stage.shineSpotlightOn(Stage.java:24)
	at net.serenitybdd.screenplay.actors.OnStage.theActorCalled(OnStage.java:37)
	at co.com.bancolombia.certificacion.app.stepdefinitions.comunes.PreparacionEscenarioStepDefinition.queCargaLosDatosParaLaPrueba(PreparacionEscenarioStepDefinition.java:37)
	at ✽.que el Actor carga los datos para la prueba(src/test/resources/features/autenticacion/autenticacion.feature:10)
Caused by: net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate new WebDriver instance of type class io.appium.java_client.AppiumDriver (unknown command: Cannot call non W3C standard command while in W3C mode
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'T1QAMDEMAC4.local', ip: '192.168.1.68', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.4', java.version: '1.8.0_241'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {adbExecTimeout: 30000, app: , appActivity: com.todo1.bc.proyecto6.Main..., appPackage: com.todo1.bc.proyecto6, autoGrantPermissions: true, autoWebview: true, autoWebviewTimeout: 20000, chromedriverExecutable: /Users/t1qamdemac4/Document..., databaseEnabled: false, desired: {adbExecTimeout: 30000, app: , appActivity: com.todo1.bc.proyecto6.Main..., appPackage: com.todo1.bc.proyecto6, autoGrantPermissions: true, autoWebview: true, autoWebviewTimeout: 20000, chromedriverExecutable: /Users/t1qamdemac4/Document..., deviceName: 85b6523638553857, enablePerformanceLogging: true, fullReset: false, hub: http://127.0.0.1:4723/wd/hub, loggingPrefs: {}, newCommandTimeout: 120, noReset: true, platformName: android, platformVersion: 7.0}, deviceApiLevel: 24, deviceManufacturer: samsung, deviceModel: SM-G925I, deviceName: 85b6523638553857, deviceScreenDensity: 640, deviceScreenSize: 1440x2560, deviceUDID: 85b6523638553857, enablePerformanceLogging: true, fullReset: false, hub: http://127.0.0.1:4723/wd/hub, javascriptEnabled: true, locationContextEnabled: false, loggingPrefs: org.openqa.selenium.logging..., networkConnectionEnabled: true, newCommandTimeout: 120, noReset: true, pixelRatio: 4, platform: LINUX, platformName: Android, platformVersion: 7.0, statBarHeight: 96, takesScreenshot: true, viewportRect: {height: 2464, left: 0, top: 96, width: 1440}, warnings: {}, webStorageEnabled: false}
Session ID: b3525287-753a-45f0-8ddc-a56c70ca8114). See below for more details.
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:158)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:141)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:132)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:102)
	at net.serenitybdd.core.webdriver.RemoteDriver.of(RemoteDriver.java:13)
	at net.thucydides.core.webdriver.appium.AppiumConfiguration.getTargetPlatform(AppiumConfiguration.java:49)
	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.platformFor(ElementLocatorFactorySelector.java:51)
	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.getLocatorFor(ElementLocatorFactorySelector.java:41)
	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.getLocatorFor(ElementLocatorFactorySelector.java:31)
	at net.thucydides.core.annotations.locators.SmartElementProxyCreator.proxyElements(SmartElementProxyCreator.java:21)
	at net.thucydides.core.webdriver.DefaultPageObjectInitialiser.apply(DefaultPageObjectInitialiser.java:19)
	at net.serenitybdd.core.pages.PageObject.setDriver(PageObject.java:166)
	at net.serenitybdd.core.pages.PageObject.setDriver(PageObject.java:170)
	at net.serenitybdd.core.pages.PageObject.<init>(PageObject.java:154)
	at net.serenitybdd.screenplay.abilities.BrowseTheWeb.<init>(BrowseTheWeb.java:31)
	at net.serenitybdd.screenplay.abilities.BrowseTheWeb.with(BrowseTheWeb.java:47)
	at net.serenitybdd.screenplay.actors.OnlineCast.actorNamed(OnlineCast.java:45)
	at net.serenitybdd.screenplay.actors.Stage.lambda$shineSpotlightOn$1(Stage.java:24)
	at java.util.Optional.orElseGet(Optional.java:267)
	at net.serenitybdd.screenplay.actors.Stage.shineSpotlightOn(Stage.java:24)
	at net.serenitybdd.screenplay.actors.OnStage.theActorCalled(OnStage.java:37)
	at co.com.bancolombia.certificacion.app.stepdefinitions.comunes.PreparacionEscenarioStepDefinition.queCargaLosDatosParaLaPrueba(PreparacionEscenarioStepDefinition.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:31)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:25)
	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:37)
	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:40)
	at cucumber.api.TestStep.executeStep(TestStep.java:102)
	at cucumber.api.TestStep.run(TestStep.java:83)
	at cucumber.api.TestCase.run(TestCase.java:58)
	at cucumber.runner.Runner.runPickle(Runner.java:80)
	at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:140)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:118)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:56)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:127)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at co.com.bancolombia.certificacion.app.utilidades.customrunner.RunnerPersonalizado.run(RunnerPersonalizado.java:61)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.openqa.selenium.UnsupportedCommandException: unknown command: Cannot call non W3C standard command while in W3C mode
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'T1QAMDEMAC4.local', ip: '192.168.1.68', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.4', java.version: '1.8.0_241'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {adbExecTimeout: 30000, app: , appActivity: com.todo1.bc.proyecto6.Main..., appPackage: com.todo1.bc.proyecto6, autoGrantPermissions: true, autoWebview: true, autoWebviewTimeout: 20000, chromedriverExecutable: /Users/t1qamdemac4/Document..., databaseEnabled: false, desired: {adbExecTimeout: 30000, app: , appActivity: com.todo1.bc.proyecto6.Main..., appPackage: com.todo1.bc.proyecto6, autoGrantPermissions: true, autoWebview: true, autoWebviewTimeout: 20000, chromedriverExecutable: /Users/t1qamdemac4/Document..., deviceName: 85b6523638553857, enablePerformanceLogging: true, fullReset: false, hub: http://127.0.0.1:4723/wd/hub, loggingPrefs: {}, newCommandTimeout: 120, noReset: true, platformName: android, platformVersion: 7.0}, deviceApiLevel: 24, deviceManufacturer: samsung, deviceModel: SM-G925I, deviceName: 85b6523638553857, deviceScreenDensity: 640, deviceScreenSize: 1440x2560, deviceUDID: 85b6523638553857, enablePerformanceLogging: true, fullReset: false, hub: http://127.0.0.1:4723/wd/hub, javascriptEnabled: true, locationContextEnabled: false, loggingPrefs: org.openqa.selenium.logging..., networkConnectionEnabled: true, newCommandTimeout: 120, noReset: true, pixelRatio: 4, platform: LINUX, platformName: Android, platformVersion: 7.0, statBarHeight: 96, takesScreenshot: true, viewportRect: {height: 2464, left: 0, top: 96, width: 1440}, warnings: {}, webStorageEnabled: false}
Session ID: b3525287-753a-45f0-8ddc-a56c70ca8114
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:46)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at io.appium.java_client.HasSessionDetails.getSessionDetails(HasSessionDetails.java:39)
	at io.appium.java_client.HasSessionDetails.getSessionDetail(HasSessionDetails.java:56)
	at io.appium.java_client.HasSessionDetails.getPlatformName(HasSessionDetails.java:65)
	at io.appium.java_client.internal.JsonToMobileElementConverter.<init>(JsonToMobileElementConverter.java:49)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:89)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:95)
	at net.serenitybdd.core.webdriver.driverproviders.AppiumDriverProvider.newDriverUsingExternalServer(AppiumDriverProvider.java:59)
	at net.serenitybdd.core.webdriver.driverproviders.AppiumDriverProvider.newInstance(AppiumDriverProvider.java:47)
	at net.thucydides.core.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:169)
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:150)
	... 59 more

`

As i wrote at the begining on Windows it runs well but on MacOS isn`t.

Thanks if anybody can help me.

@mykola-mokhnach

**Comment by juferz** [comment]
Log 

jun 22, 2020 9:20:57 PM io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0
INFORMACIÓN: Detected dialect: W3C
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - 
           __  _____ _____ ____ _____   _____ _    ___ _     _____ ____  
  _       / / |_   _| ____/ ___|_   _| |  ___/ \  |_ _| |   | ____|  _ \ 
 (_)_____| |    | | |  _| \___ \ | |   | |_ / _ \  | || |   |  _| | | | |
  _|_____| |    | | | |___ ___) || |   |  _/ ___ \ | || |___| |___| |_| |
 (_)     | |    |_| |_____|____/ |_|   |_|/_/   \_\___|_____|_____|____/ 
          \_\                                                            

TEST FAILED WITH ERROR: Autenticacion exitosa en la aplicacion de Bancolombia OSP
---------------------------------------------------------------------
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - TEST FAILED AT STEP Dado que el Actor carga los datos para la prueba | ID | numeroDocumento | tipoDocumento | usuario | clave | segundaClave | orientacion | resultadoEsperado | | 1 | 333333302 | 1 | autotest30 | 1234 | 4321 | Acierto | NO ERROR |
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - Could not instantiate new WebDriver instance of type class io.appium.java_client.AppiumDriver (unknown command: Cannot call non W3C standard command while in W3C mode

net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class io.appium.java_client.AppiumDriver

	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:144)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:132)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:102)
	at net.serenitybdd.core.webdriver.RemoteDriver.of(RemoteDriver.java:13)
	at net.thucydides.core.webdriver.appium.AppiumConfiguration.getTargetPlatform(AppiumConfiguration.java:49)
	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.platformFor(ElementLocatorFactorySelector.java:51)
	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.getLocatorFor(ElementLocatorFactorySelector.java:41)
	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.getLocatorFor(ElementLocatorFactorySelector.java:31)
	at net.thucydides.core.annotations.locators.SmartElementProxyCreator.proxyElements(SmartElementProxyCreator.java:21)
	at net.thucydides.core.webdriver.DefaultPageObjectInitialiser.apply(DefaultPageObjectInitialiser.java:19)
	at net.serenitybdd.core.pages.PageObject.setDriver(PageObject.java:166)
	at net.serenitybdd.core.pages.PageObject.setDriver(PageObject.java:170)
	at net.serenitybdd.core.pages.PageObject.<init>(PageObject.java:154)
	at net.serenitybdd.screenplay.abilities.BrowseTheWeb.<init>(BrowseTheWeb.java:31)
	at net.serenitybdd.screenplay.abilities.BrowseTheWeb.with(BrowseTheWeb.java:47)
	at net.serenitybdd.screenplay.actors.OnlineCast.actorNamed(OnlineCast.java:45)
	at net.serenitybdd.screenplay.actors.Stage.lambda$shineSpotlightOn$1(Stage.java:24)
	at java.util.Optional.orElseGet(Optional.java:267)
	at net.serenitybdd.screenplay.actors.Stage.shineSpotlightOn(Stage.java:24)
	at net.serenitybdd.screenplay.actors.OnStage.theActorCalled(OnStage.java:37)
	at co.com.bancolombia.certificacion.app.stepdefinitions.comunes.PreparacionEscenarioStepDefinition.queCargaLosDatosParaLaPrueba(PreparacionEscenarioStepDefinition.java:37)
	at ✽.que el Actor carga los datos para la prueba(src/test/resources/features/autenticacion/autenticacion.feature:10)
Caused by: net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate new WebDriver instance of type class io.appium.java_client.AppiumDriver (unknown command: Cannot call non W3C standard command while in W3C mode
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'T1QAMDEMAC4.local', ip: '192.168.1.68', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.4', java.version: '1.8.0_241'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {adbExecTimeout: 30000, app: , appActivity: com.todo1.bc.proyecto6.Main..., appPackage: com.todo1.bc.proyecto6, autoGrantPermissions: true, autoWebview: true, autoWebviewTimeout: 20000, chromedriverExecutable: /Users/t1qamdemac4/Document..., databaseEnabled: false, desired: {adbExecTimeout: 30000, app: , appActivity: com.todo1.bc.proyecto6.Main..., appPackage: com.todo1.bc.proyecto6, autoGrantPermissions: true, autoWebview: true, autoWebviewTimeout: 20000, chromedriverExecutable: /Users/t1qamdemac4/Document..., deviceName: 85b6523638553857, enablePerformanceLogging: true, fullReset: false, hub: http://127.0.0.1:4723/wd/hub, loggingPrefs: {}, newCommandTimeout: 120, noReset: true, platformName: android, platformVersion: 7.0}, deviceApiLevel: 24, deviceManufacturer: samsung, deviceModel: SM-G925I, deviceName: 85b6523638553857, deviceScreenDensity: 640, deviceScreenSize: 1440x2560, deviceUDID: 85b6523638553857, enablePerformanceLogging: true, fullReset: false, hub: http://127.0.0.1:4723/wd/hub, javascriptEnabled: true, locationContextEnabled: false, loggingPrefs: org.openqa.selenium.logging..., networkConnectionEnabled: true, newCommandTimeout: 120, noReset: true, pixelRatio: 4, platform: LINUX, platformName: Android, platformVersion: 7.0, statBarHeight: 96, takesScreenshot: true, viewportRect: {height: 2464, left: 0, top: 96, width: 1440}, warnings: {}, webStorageEnabled: false}
Session ID: b3525287-753a-45f0-8ddc-a56c70ca8114). See below for more details.
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:158)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:141)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:132)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:102)
	at net.serenitybdd.core.webdriver.RemoteDriver.of(RemoteDriver.java:13)
	at net.thucydides.core.webdriver.appium.AppiumConfiguration.getTargetPlatform(AppiumConfiguration.java:49)
	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.platformFor(ElementLocatorFactorySelector.java:51)
	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.getLocatorFor(ElementLocatorFactorySelector.java:41)
	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.getLocatorFor(ElementLocatorFactorySelector.java:31)
	at net.thucydides.core.annotations.locators.SmartElementProxyCreator.proxyElements(SmartElementProxyCreator.java:21)
	at net.thucydides.core.webdriver.DefaultPageObjectInitialiser.apply(DefaultPageObjectInitialiser.java:19)
	at net.serenitybdd.core.pages.PageObject.setDriver(PageObject.java:166)
	at net.serenitybdd.core.pages.PageObject.setDriver(PageObject.java:170)
	at net.serenitybdd.core.pages.PageObject.<init>(PageObject.java:154)
	at net.serenitybdd.screenplay.abilities.BrowseTheWeb.<init>(BrowseTheWeb.java:31)
	at net.serenitybdd.screenplay.abilities.BrowseTheWeb.with(BrowseTheWeb.java:47)
	at net.serenitybdd.screenplay.actors.OnlineCast.actorNamed(OnlineCast.java:45)
	at net.serenitybdd.screenplay.actors.Stage.lambda$shineSpotlightOn$1(Stage.java:24)
	at java.util.Optional.orElseGet(Optional.java:267)
	at net.serenitybdd.screenplay.actors.Stage.shineSpotlightOn(Stage.java:24)
	at net.serenitybdd.screenplay.actors.OnStage.theActorCalled(OnStage.java:37)
	at co.com.bancolombia.certificacion.app.stepdefinitions.comunes.PreparacionEscenarioStepDefinition.queCargaLosDatosParaLaPrueba(PreparacionEscenarioStepDefinition.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:31)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:25)
	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:37)
	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:40)
	at cucumber.api.TestStep.executeStep(TestStep.java:102)
	at cucumber.api.TestStep.run(TestStep.java:83)
	at cucumber.api.TestCase.run(TestCase.java:58)
	at cucumber.runner.Runner.runPickle(Runner.java:80)
	at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:140)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:118)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:56)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:127)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at co.com.bancolombia.certificacion.app.utilidades.customrunner.RunnerPersonalizado.run(RunnerPersonalizado.java:61)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.openqa.selenium.UnsupportedCommandException: unknown command: Cannot call non W3C standard command while in W3C mode
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'T1QAMDEMAC4.local', ip: '192.168.1.68', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.4', java.version: '1.8.0_241'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {adbExecTimeout: 30000, app: , appActivity: com.todo1.bc.proyecto6.Main..., appPackage: com.todo1.bc.proyecto6, autoGrantPermissions: true, autoWebview: true, autoWebviewTimeout: 20000, chromedriverExecutable: /Users/t1qamdemac4/Document..., databaseEnabled: false, desired: {adbExecTimeout: 30000, app: , appActivity: com.todo1.bc.proyecto6.Main..., appPackage: com.todo1.bc.proyecto6, autoGrantPermissions: true, autoWebview: true, autoWebviewTimeout: 20000, chromedriverExecutable: /Users/t1qamdemac4/Document..., deviceName: 85b6523638553857, enablePerformanceLogging: true, fullReset: false, hub: http://127.0.0.1:4723/wd/hub, loggingPrefs: {}, newCommandTimeout: 120, noReset: true, platformName: android, platformVersion: 7.0}, deviceApiLevel: 24, deviceManufacturer: samsung, deviceModel: SM-G925I, deviceName: 85b6523638553857, deviceScreenDensity: 640, deviceScreenSize: 1440x2560, deviceUDID: 85b6523638553857, enablePerformanceLogging: true, fullReset: false, hub: http://127.0.0.1:4723/wd/hub, javascriptEnabled: true, locationContextEnabled: false, loggingPrefs: org.openqa.selenium.logging..., networkConnectionEnabled: true, newCommandTimeout: 120, noReset: true, pixelRatio: 4, platform: LINUX, platformName: Android, platformVersion: 7.0, statBarHeight: 96, takesScreenshot: true, viewportRect: {height: 2464, left: 0, top: 96, width: 1440}, warnings: {}, webStorageEnabled: false}
Session ID: b3525287-753a-45f0-8ddc-a56c70ca8114
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:46)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at io.appium.java_client.HasSessionDetails.getSessionDetails(HasSessionDetails.java:39)
	at io.appium.java_client.HasSessionDetails.getSessionDetail(HasSessionDetails.java:56)
	at io.appium.java_client.HasSessionDetails.getPlatformName(HasSessionDetails.java:65)
	at io.appium.java_client.internal.JsonToMobileElementConverter.<init>(JsonToMobileElementConverter.java:49)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:89)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:95)
	at net.serenitybdd.core.webdriver.driverproviders.AppiumDriverProvider.newDriverUsingExternalServer(AppiumDriverProvider.java:59)
	at net.serenitybdd.core.webdriver.driverproviders.AppiumDriverProvider.newInstance(AppiumDriverProvider.java:47)
	at net.thucydides.core.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:169)
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:150)
	... 59 more
