### ISSUE TITLE
(ios) scrollTo not performed，and throws Exception:com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 7

### ISSUE THREAD

**Issue by liqing380** [appium/java-client#137]
```
java-client:2.1.0
real device: ipad with ios7.1
appium:1.3.3
```

my java code:

``` java
WebElement webElement=appDriver.findElementByIosUIAutomation(".tableViews()[1].cells().withPredicate(\" any staticTexts.name == 'reg185.cn'\")");
        tap(appDriver,webElement);
        se2.waitTime(se2.sec);
        appDriver.scrollTo("nftrs@qa185.cn");
```

them scrollTo not performed，and throws Exception:

``` java
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 7
    at com.google.gson.JsonParser.parse(JsonParser.java:65)
    at com.google.gson.JsonParser.parse(JsonParser.java:45)
    at io.appium.java_client.ComplexFind.execute(ComplexFind.java:81)
    at io.appium.java_client.ComplexFind.scrollTo(ComplexFind.java:55)
    at io.appium.java_client.AppiumDriver.scrollTo(AppiumDriver.java:513)
    at com.mailtech.coremailapp.example.iosAppTest.iosAppPractice.Oab.doTest(Oab.java:202)
    at com.mailtech.coremailapp.CmTestBaseEx.testMain(CmTestBaseEx.java:51)
    at com.mailtech.coremailapp.example.iosAppTest.iosAppPractice.Oab.testOab(Oab.java:227)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 7
    at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505)
    at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1386)
    at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:531)
    at com.google.gson.stream.JsonReader.peek(JsonReader.java:414)
    at com.google.gson.JsonParser.parse(JsonParser.java:60)
    ... 35 more
```

appium log is :

``` java
info: [debug] Pushing command to appium work queue: "au.getElementByUIAutomation('.tableViews()[1].cells().withPredicate(\\\" any staticTexts.name == \\'reg185.cn\\'\\\")')"
info: [debug] Sending command to instruments: au.getElementByUIAutomation('.tableViews()[1].cells().withPredicate(\" any staticTexts.name == \'reg185.cn\'\")')
info: [debug] [INST] 2014-12-04 08:56:20 +0000 Debug: Got new command 4 from instruments: au.getElementByUIAutomation('.tableViews()[1].cells().withPredicate(\" any staticTexts.name == \'reg185.cn\'\")')
info: [debug] [INST] 2014-12-04 08:56:20 +0000 Debug: evaluating au.getElementByUIAutomation('.tableViews()[1].cells().withPredicate(\" any staticTexts.name == \'reg185.cn\'\")')
info: [debug] [INST] 2014-12-04 08:56:20 +0000 Debug: byUIAutomation: evaluating code: $.mainWindow().tableViews()[1].cells().withPredicate(" any staticTexts.name == 'reg185.cn'")
info: [debug] [INST] 2014-12-04 08:56:20 +0000 Debug: evaluation finished
info: [debug] [INST] 2014-12-04 08:56:20 +0000 Debug: Lookup returned [object UIATableCell] with the name "reg185.cn" (id: 1).
info: [debug] [INST] 2014-12-04 08:56:20 +0000 Debug: responding with:
       2014-12-04 08:56:20 +0000 Debug: Running system command #5: /Users/coremail/Downloads/node-v0.10.33-darwin-x64/bin/node /Users/coremail/Downloads/node-v0.10.33-darwin-x64/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"ELEMENT":"1"}}...
info: [debug] Socket data received (38 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"ELEMENT":"1"}}
info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"1"},"sessionId":"a2af78c1-47ba-4fe6-8bfc-29c4562c6391"}
info: <-- POST /wd/hub/session/a2af78c1-47ba-4fe6-8bfc-29c4562c6391/element 200 1114.234 ms - 87 {"status":0,"value":{"ELEMENT":"1"},"sessionId":"a2af78c1-47ba-4fe6-8bfc-29c4562c6391"}
info: --> POST /wd/hub/session/a2af78c1-47ba-4fe6-8bfc-29c4562c6391/touch/perform {"actions":[{"action":"press","options":{"element":"1"}},{"action":"wait","options":{"ms":500}},{"action":"release","options":{}}]}
info: [debug] Pushing command to appium work queue: "au.getElement('1').rect()"
info: [debug] Sending command to instruments: au.getElement('1').rect()
info: [debug] [INST] 2014-12-04 08:56:21 +0000 Debug: Got new command 5 from instruments: au.getElement('1').rect()
info: [debug] [INST] 2014-12-04 08:56:21 +0000 Debug: evaluating au.getElement('1').rect()
info: [debug] [INST] 2014-12-04 08:56:21 +0000 Debug: evaluation finished
info: [debug] [INST] 2014-12-04 08:56:21 +0000 Debug: responding with:
       2014-12-04 08:56:21 +0000 Debug: Running system command #6: /Users/coremail/Downloads/node-v0.10.33-darwin-x64/bin/node /Users/coremail/Downloads/node-v0.10.33-darwin-x64/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"origin":{"x":0,"y":64},"size":{"width":768,"height":58}}}...
info: [debug] Socket data received (81 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"origin":{"x":0,"y":64},"size":{"width":768,"height":58}}}
info: [debug] Pushing command to appium work queue: "target.touch([{\"touch\":[{\"x\":384,\"y\":93}],\"time\":0.2},{\"touch\":[{\"x\":384,\"y\":93}],\"time\":0.7}])"
info: [debug] Sending command to instruments: target.touch([{"touch":[{"x":384,"y":93}],"time":0.2},{"touch":[{"x":384,"y":93}],"time":0.7}])
info: [debug] [INST] 2014-12-04 08:56:22 +0000 Debug: Got new command 6 from instruments: target.touch([{"touch":[{"x":384,"y":93}],"time":0.2},{"touch":[{"x":384,"y":93}],"time":0.7}])
info: [debug] [INST] 2014-12-04 08:56:22 +0000 Debug: evaluating target.touch([{"touch":[{"x":384,"y":93}],"time":0.2},{"touch":[{"x":384,"y":93}],"time":0.7}])
info: [debug] [INST] 2014-12-04 08:56:22 +0000 Debug: target.touch(__NSCFArray)
info: [debug] Socket data received (25 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":""}
info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"a2af78c1-47ba-4fe6-8bfc-29c4562c6391"}
info: <-- POST /wd/hub/session/a2af78c1-47ba-4fe6-8bfc-29c4562c6391/touch/perform 200 2774.429 ms - 74 {"status":0,"value":"","sessionId":"a2af78c1-47ba-4fe6-8bfc-29c4562c6391"}
info: --> POST /wd/hub/session/a2af78c1-47ba-4fe6-8bfc-29c4562c6391/appium/app/complex_find ["scroll",[[3,"nftrs@qa185.cn"]],[[7,"nftrs@qa185.cn"]]]
info: [debug] Responding to client that we did not find a valid resource
info: <-- POST /wd/hub/session/a2af78c1-47ba-4fe6-8bfc-29c4562c6391/appium/app/complex_find 404 3.432 ms - 47 
```

**Comment by Catherine0728** [comment]
Studio 里面出现这个问题是怎么解决
