### ISSUE TITLE
'Cannot call non W3C standard command while in W3C mode' when getAvailableLogTypes

### ISSUE THREAD

**Issue by ltpquang** [appium/java-client#1416]
## Description

The following exception is thrown sometimes when I tried to call `getAvailableLogTypes()`.

```
org.openqa.selenium.UnsupportedCommandException: unknown command: Cannot call non W3C standard command while in W3C mode
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Defaultstring', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-52-generic', java.version: '1.8.0_275'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {adbExecTimeout: 60000, appActivity: vn.com.ltpquang.ui.activ..., appPackage: vn.com.ltpquang, automationName: uiAutomator2, clearDeviceLogsOnStart: true, databaseEnabled: false, desired: {adbExecTimeout: 60000, appActivity: vn.com.ltpquang.ui.activ..., appPackage: vn.com.ltpquang, automationName: uiAutomator2, clearDeviceLogsOnStart: true, fullReset: false, newCommandTimeout: 0, noReset: true, platformName: android, udid: 330055a244c72319}, deviceApiLevel: 24, deviceManufacturer: samsung, deviceModel: SM-A510F, deviceName: 330055a244c72319, deviceScreenDensity: 480, deviceScreenSize: 1080x1920, deviceUDID: 330055a244c72319, fullReset: false, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, newCommandTimeout: 0, noReset: true, pixelRatio: 3, platform: LINUX, platformName: Android, platformVersion: 7.0, statBarHeight: 72, takesScreenshot: true, udid: 330055a244c72319, viewportRect: {height: 1848, left: 0, top: 72, width: 1080}, warnings: {}, webStorageEnabled: false}
Session ID: 596e74ae-4309-40d1-a51a-e58f4e87ec2a
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at com.qaprosoft.carina.core.foundation.webdriver.listener.EventFiringAppiumCommandExecutor.execute(EventFiringAppiumCommandExecutor.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:45)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:33)
	at org.openqa.selenium.remote.RemoteLogs.getAvailableLogTypes(RemoteLogs.java:106)
```

Should #1242 fix this?

## Environment

* Java client build version or git revision if you use some snapshot: 7.3.0
* Appium server version or git revision if you use some snapshot: 1.18.3
* Desktop OS/version used to run Appium if necessary: Ubuntu 18.04
* Node.js version: 15.2.1
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device

## Link To Appium Logs

https://gist.github.com/ltpquang/b863190fb266863b773a96edd6d4fa3c

**Comment by omkarnathsingh** [comment]
https://github.com/appium/java-client/issues/1242#issuecomment-539075905

Have you put this capability? Need to set w3c as false.
