### ISSUE TITLE
Error- io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0

### ISSUE THREAD

**Issue by Kaamini1** [appium/java-client#1419]
**## Environment**

* Java client build version: 7.2.0
* Appium server version: v1.18.3
* Mobile platform/version under test: Pixel_3_API_29
* Real device or emulator/simulator: emulator

**## Details**
Pom dependencies-
<dependency>	
    <groupId>io.appium</groupId>
    <artifactId>java-client</artifactId>
    <version>7.2.0</version>
</dependency>
  	<dependency>
  		<groupId>org.seleniumhq.selenium</groupId>
  		<artifactId>selenium-java</artifactId> 
  		
  		<version>2.53.1</version>
  	</dependency>
  	<dependency>
   <groupId>org.json</groupId>
   <artifactId>json</artifactId>
   <version>20080701</version>
</dependency>

<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-remote-driver</artifactId>
    <version>3.14.0</version>
</dependency>

**## Code To Reproduce Issue**

package testRunner;

import java.net.MalformedURLException;
import java.net.URL;
import org.openqa.selenium.remote.DesiredCapabilities;
import io.appium.java_client.MobileElement;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.remote.MobileCapabilityType;

public class first_Test {
	 static AndroidDriver<MobileElement> driver;
	 public static void openApp() throws MalformedURLException, InterruptedException {
		
	DesiredCapabilities dc = new DesiredCapabilities();
        dc.setCapability(MobileCapabilityType.DEVICE_NAME, "emulator-5554");
        dc.setCapability("platformName", "android");
        dc.setCapability("appPackage", "com.massageenvy.consumer.android.pwa.qa");
        dc.setCapability("appActivity", "io.ionic.starter.MainActivity");
        dc.setCapability("appWaitDuration", 50000);
        dc.setCapability("autoWebview", true);
        dc.setCapability("autoGrantPermissions", true);
        driver = new AndroidDriver<MobileElement> (new URL("http://127.0.0.1:4723/wd/hub"),dc); 
        Thread.sleep(10000);	
	}
	 public static void main(String[] args) throws Exception {
		 openApp();
	}
	}	

**## Eclipse log-**

 ===== program started =====
Dec. 09, 2020 7:33:17 P.M. io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0
INFO: Detected dialect: W3C
Exception in thread "main" java.lang.NoSuchMethodError: 'org.openqa.selenium.Platform org.openqa.selenium.Platform.fromString(java.lang.String)'
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:230)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:86)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:96)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:94)
	at testRunner.first_Test.openApp(first_Test.java:24)
	at testRunner.first_Test.main(first_Test.java:31)

**## Link To Appium Logs**

https://gist.github.com/Kaamini1/99cd462d0816c489130e3376e32e84a0

**Comment by Kaamini1** [comment]
#1251 #1182 #1205

**Comment by valfirst** [comment]
- If you use any modern build tool (Maven, Gradle, etc.), please remove custom Selenium dependencies as Appium java client already includes them.
 - If you build the classpath manually or using custom solution please check this comment https://github.com/appium/java-client/issues/1273#issuecomment-559773917 regarding dependencies compatibility
