### ISSUE TITLE
mac2 driver instead of mac driver?

### ISSUE THREAD

**Issue by puresk** [appium/java-client#1440]
Hi

I took a look at this: [Appium Docs](http://appium.io/docs/en/drivers/mac/index.html) and found:
"_Appium has beta support for automation of OS X desktop applications. Development of this driver happens at the appium-mac-driver, and relies on a native OS X binary called AppiumForMac._"

But when i open either of project i see "_Please consider switching to appium-mac2-driver for over macOS 10.15_". And there is no app called AppiumForMac with releases like this: [releases](https://github.com/appium/appium-for-mac/releases)
So i don't know how to proceed with appium for mac **2**

Do you have any doc with step-by-step examples i can start from? Thanks!

Update:
Ok i successfully used mac2 driver instead of mac driver! :-)

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/java-client/pull/1439

**Comment by DmitryMishtal** [comment]
@mykola-mokhnach 

Hello Mykola,

Seems like something wrong with Mac2 driver (or i've made a mistake?), but if i search element through Mac2Driver<Mac2Element>, i cannot cast found element into Mac2Element and getting ClassCastException (in debug i can see RemoteWebElement was found)

For example, code:

```
By locator = By.id("LoginLoginField");
Mac2Element element = driver.findElement(locator);
```

is throwing:

```
java.lang.ClassCastException: org.openqa.selenium.remote.RemoteWebElement cannot be cast to io.appium.java_client.mac.Mac2Element
	at com.company.page.setLogin(LoginPage.java:36)
	at com.company.page.login(LoginPage.java:113)
```
