### ISSUE TITLE
Appium - NoSuchMethodException on PageFactory.initElements(new AppiumFieldDecorator(driver), this);

### ISSUE THREAD

**Issue by alanmukh12** [appium/java-client#1462]
## Description

I am seeing a NoSuchMethodException on  PageFactory.initElements(new AppiumFieldDecorator(driver), this);

Stack Trace:
java.lang.RuntimeException: java.lang.NoSuchMethodException: jdk.proxy2.$Proxy8.proxyClassLookup()

	at io.appium.java_client.pagefactory.bys.builder.AppiumByBuilder.prepareAnnotationMethods(AppiumByBuilder.java:85)
	at io.appium.java_client.pagefactory.bys.builder.AppiumByBuilder.getFilledValue(AppiumByBuilder.java:92)
	at io.appium.java_client.pagefactory.bys.builder.AppiumByBuilder.createBy(AppiumByBuilder.java:148)
	at io.appium.java_client.pagefactory.DefaultElementByBuilder.getBys(DefaultElementByBuilder.java:133)
	at io.appium.java_client.pagefactory.DefaultElementByBuilder.buildMobileNativeBy(DefaultElementByBuilder.java:170)
	at io.appium.java_client.pagefactory.DefaultElementByBuilder.buildBy(DefaultElementByBuilder.java:204)
	at io.appium.java_client.pagefactory.AppiumElementLocatorFactory.createLocator(AppiumElementLocatorFactory.java:66)
	at io.appium.java_client.pagefactory.AppiumElementLocatorFactory.createLocator(AppiumElementLocatorFactory.java:53)
	at io.appium.java_client.pagefactory.AppiumElementLocatorFactory.createLocator(AppiumElementLocatorFactory.java:1)
	at org.openqa.selenium.support.pagefactory.DefaultFieldDecorator.decorate(DefaultFieldDecorator.java:56)
	at io.appium.java_client.pagefactory.AppiumFieldDecorator.decorate(AppiumFieldDecorator.java:154)
	at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:113)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
	at Pages.BasePage.<init>(BasePage.java:21)
	at Pages.HomePage.<init>(HomePage.java:29)
	at Pages.TwitterPageFactory.homePage(TwitterPageFactory.java:15)

## Environment

abstract class BasePage {

    protected AndroidDriver<AndroidElement> driver;
    protected FluentWait wait;

    BasePage(AndroidDriver<AndroidElement> driver){
        this.driver = driver;
        PageFactory.initElements(new AppiumFieldDecorator(driver), this); //Exception occurs here
        wait = new WebDriverWait(driver, 60).ignoring(NoSuchElementException.class);
    }

    protected void wait(AndroidElement element){
        wait.until(ExpectedConditions.visibilityOf(element));
    }

    abstract void waitForPageToLoad();

}

POM:
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>TwitterAppium</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>16</maven.compiler.source>
        <maven.compiler.target>16</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>7.5.1</version>
        </dependency>
    </dependencies>

</project>

**Comment by alanmukh12** [comment]
ok I figured this out. When I changed the Project SDK to 1.8, it started working
