### ISSUE TITLE
io.appium.java_client.service.local.InvalidServerInstanceException: The main Appium script does not exist

### ISSUE THREAD

**Issue by jinmoo21** [appium/java-client#1477]
## Description
Launching custom driver that extends AppiumDriver, it raises InvalidServerInstanceException.

## Environment
* Java client build version: 7.5.1 
* Appium version: 1.21.0
* Desktop OS/version: Mac OS Big Sur
* Node.js version: 16.1.0
* Mobile platform/version under test: Android 10.0
* Real device: Galaxy S9

## Code To Reproduce Issue
```java
public class TestClass {
	AppiumDriver<WebElement> driver;
	ExtendedDriver exDriver;
	
	@BeforeSuite
	public void beforeSuite() {
		DesiredCapabilities caps = new DesiredCapabilities();
		caps.setCapability("platformName", "Android");
		caps.setCapability("browserName", "Chrome");
		caps.setCapability("deviceName", "AppiumDriver");
		caps.setCapability("automationName", "UiAutomator2");
			try {
				driver = new AndroidDriver<WebElement>(new URL("http://localhost:4723/wd/hub"), caps);
			} catch (MalformedURLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			exDriver = new ExtendedDriver(driver);
	}
	
	@AfterSuite
	public void afterSuite() {
		Optional.ofNullable(driver).ifPresent(AppiumDriver::quit);
	}
	
	@Test
	public void testMethod() {
		driver.get("https://google.com");
	}
}

class ExtendedDriver extends AppiumDriver<WebElement> {
	public ExtendedDriver(AppiumDriver<WebElement> driver) {
		super(driver.getCapabilities());	
	}
}
```

## Exception Stacktraces
```log
io.appium.java_client.service.local.InvalidServerInstanceException: The main Appium script does not exist at '/Users/user/git/JWDriver/my-webdriver/appium/build/lib/main.js'
	at io.appium.java_client.service.local.AppiumServiceBuilder.findMainScript(AppiumServiceBuilder.java:163)
	at io.appium.java_client.service.local.AppiumServiceBuilder.loadPathToMainScript(AppiumServiceBuilder.java:317)
	at io.appium.java_client.service.local.AppiumServiceBuilder.createArgs(AppiumServiceBuilder.java:373)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:358)
	at io.appium.java_client.service.local.AppiumDriverLocalService.buildService(AppiumDriverLocalService.java:91)
	at io.appium.java_client.service.local.AppiumDriverLocalService.buildDefaultService(AppiumDriverLocalService.java:87)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:134)
	at com.dove.test.ExtendedDriver.<init>(TestClass.java:49)
	at com.dove.test.TestClass.beforeSuite(TestClass.java:33)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
```

## Link To Appium Logs
```log
[UiAutomator2] Starting UIAutomator2 server 4.21.1
[UiAutomator2] Using UIAutomator2 server from '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.21.1.apk' and test from '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk'
[UiAutomator2] Waiting up to 30000ms for UiAutomator2 to be online...
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","192.168.0.17:5555","shell","am","instrument","-w","-e","disableAnalytics",true,"io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner"]
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8201/wd/hub/status] with no body
[WD Proxy] socket hang up
[debug] [Instrumentation] io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8201/wd/hub/status] with no body
[WD Proxy] socket hang up
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8201/wd/hub/status] with no body
[WD Proxy] socket hang up
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8201/wd/hub/status] with no body
[debug] [WD Proxy] Got response with status 200: {"sessionId":"None","value":{"message":"UiAutomator2 Server is ready to accept commands","ready":true}}
[debug] [UiAutomator2] The initialization of the instrumentation process took 3280ms
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8201/wd/hub/session] with body: {"capabilities":{"firstMatch":[{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"browserName":"Chrome","platformName":"android","automationName":"UiAutomator2","deviceName":"AppiumDriver"},"browserName":"Chrome","platformName":"android","automationName":"UiAutomator2","deviceName":"192.168.0.17:5555","appPackage":"com.android.chrome","appActivity":"com.google.android.apps.chrome.Main","deviceUDID":"192.168.0.17:5555"}],"alwaysMatch":{}}}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"896a49ac-aa25-4ce3-bd64-aa7e4513ee28","value":{"capabilities":{"firstMatch":[{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"browserName":"Chrome","platformName":"android","automationName":"UiAutomator2","deviceName":"AppiumDriver"},"browserName":"Chrome","platformName":"android","automationName":"UiAutomator2","deviceName":"192.168.0.17:5555","appPackage":"com.android.chrome","appActivity":"com.google.android.apps.chrome.Main","deviceUDID":"192.168.0.17:5555"}],"alwaysMatch":{}},"sessionId":"896a49ac-aa25-4ce3-bd64-aa7e4513ee28"}}
[WD Proxy] Determined the downstream protocol as 'W3C'
[debug] [WD Proxy] Proxying [GET /appium/device/info] to [GET http://127.0.0.1:8201/wd/hub/session/896a49ac-aa25-4ce3-bd64-aa7e4513ee28/appium/device/info] with no body
[debug] [WD Proxy] Got response with status 200: {"sessionId":"896a49ac-aa25-4ce3-bd64-aa7e4513ee28","value":{"androidId":"c9db676d4d965d5c","apiVersion":"29","bluetooth":{"state":"ON"},"brand":"samsung","carrierName":"KT","displayDensity":560,"locale":"ko_KR","manufacturer":"samsung","model":"SM-G965N","networks":[{"capabilities":{"SSID":null,"linkDownBandwidthKbps":30000,"linkUpstreamBandwidthKbps":15000,"networkCapabilities":"NET_CAPABILITY_IMS,NET_CAPABILITY_NOT_METERED,NET_CAPABILITY_TRUSTED,NET_CAPABILITY_NOT_VPN,NET_CAPABILITY_VALIDATED,NET_CAPABILITY_NOT_ROAMING,NET_CAPABILITY_FOREGROUND,NET_CAPABILITY_NOT_CONGESTED,NET_CAPABILITY_NOT_SUSPENDED","signalStrength":-2147483648,"transportTypes":"TRANSPORT_CELLULAR"},"detailedState":"CONNECTED","extraInfo":"IMS","isAvailable":true,"isConnected":true,"isFailover":false,"isRoaming":false,"state":"CONNECTED","subtype":13,"subtypeName":"LTE","type":0,"typeName":"MOBILE"},{"capabilities":{"SSID":null,"linkDownBandwidthKbps":1048576,"linkUpstreamBandwidthKbps":1048576,"networkCapabilities":"NET_CAPABILITY_N...
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s 192.168.0.17:5555 shell dumpsys window'
[AndroidDriver] Screen already unlocked, doing nothing
[AndroidDriver] Starting a chrome-based browser session
[debug] [AndroidDriver] A port was not given, using random free port: 8001
[debug] [AndroidDriver] Precalculated Chromedriver capabilities: {
[debug] [AndroidDriver]   "androidPackage": "com.android.chrome",
[debug] [AndroidDriver]   "androidDeviceSerial": "192.168.0.17:5555"
[debug] [AndroidDriver] }
[debug] [AndroidDriver] Before starting chromedriver, androidPackage is 'com.android.chrome'
[debug] [Chromedriver] Changed state to 'starting'
[debug] [Chromedriver] Using the static Chromedriver->Chrome mapping
[debug] [Chromedriver] The most recent known Chrome version: 89.0.4389
[debug] [Chromedriver] Found 1 executable in '/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac'
[debug] [Chromedriver] The following Chromedriver executables were found:
[debug] [Chromedriver]     '/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver_mac64_v90.0.4430.24' (version '90.0.4430.24', minimum Chrome version '90.0.0')
[debug] [ADB] Getting package info for 'com.android.chrome'
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s 192.168.0.17:5555 shell dumpsys package com.android.chrome'
[debug] [Chromedriver] Found Chrome bundle 'com.android.chrome' version '90.0.4430'
[debug] [Chromedriver] Found 1 executable capable of automating Chrome '90.0.4430'.
[debug] [Chromedriver] Choosing the most recent, '/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver_mac64_v90.0.4430.24'.
[debug] [Chromedriver] If a specific version is required, specify it with the `chromedriverExecutable`desired capability.
[Chromedriver] Set chromedriver binary as: /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver_mac64_v90.0.4430.24
[debug] [Chromedriver] Killing any old chromedrivers, running: pkill -15 -f "/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver_mac64_v90.0.4430.24.*--port=8001"
[Chromedriver] No old chromedrivers seem to exist
[debug] [Chromedriver] Cleaning this device's adb forwarded port socket connections: 192.168.0.17:5555
[debug] [ADB] List forwarding ports
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s 192.168.0.17:5555 forward --list'
[Chromedriver] Spawning chromedriver with: /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver_mac64_v90.0.4430.24 --url-base=wd/hub --port=8001 --adb-port=5037 --verbose
[debug] [Chromedriver] Chromedriver version: '90.0.4430.24'
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8001/wd/hub/status] with no body
[debug] [WD Proxy] Got response with status 200: {"value":{"build":{"version":"90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429})"},"message":"ChromeDriver ready for new sessions.","os":{"arch":"x86_64","name":"Mac OS X","version":"11.3.0"},"ready":true}}
[Chromedriver] Starting W3C Chromedriver session with capabilities: {
[Chromedriver]   "capabilities": {
[Chromedriver]     "alwaysMatch": {
[Chromedriver]       "goog:chromeOptions": {
[Chromedriver]         "androidPackage": "com.android.chrome",
[Chromedriver]         "androidDeviceSerial": "192.168.0.17:5555"
[Chromedriver]       },
[Chromedriver]       "goog:loggingPrefs": {
[Chromedriver]         "browser": "ALL"
[Chromedriver]       }
[Chromedriver]     }
[Chromedriver]   }
[Chromedriver] }
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8001/wd/hub/session] with body: {"capabilities":{"alwaysMatch":{"goog:chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"192.168.0.17:5555"},"goog:loggingPrefs":{"browser":"ALL"}}}}
[debug] [Chromedriver] Webview version: 'Chrome/90.0.4430.210'
[debug] [WD Proxy] Got response with status 200: {"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"chrome","browserVersion":"90.0.4430.210","chrome":{"chromedriverVersion":"90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429})"},"goog:chromeOptions":{"debuggerAddress":"localhost:58896"},"pageLoadStrategy":"normal","platformName":"android","proxy":{},"setWindowRect":false,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify","webauthn:extension:largeBlob":false,"webauthn:virtualAuthenticators":false},"sessionId":"fceec38a6df6ce127b4db5f1c97254af"}}
[WD Proxy] Determined the downstream protocol as 'W3C'
[debug] [Chromedriver] Changed state to 'online'
[debug] [WD Proxy] Proxying [GET /appium/device/pixel_ratio] to [GET http://127.0.0.1:8201/wd/hub/session/896a49ac-aa25-4ce3-bd64-aa7e4513ee28/appium/device/pixel_ratio] with no body
[debug] [WD Proxy] Got response with status 200: {"sessionId":"896a49ac-aa25-4ce3-bd64-aa7e4513ee28","value":3.5}
[debug] [WD Proxy] Matched '/appium/device/system_bars' to command name 'getSystemBars'
[debug] [WD Proxy] Proxying [GET /appium/device/system_bars] to [GET http://127.0.0.1:8201/wd/hub/session/896a49ac-aa25-4ce3-bd64-aa7e4513ee28/appium/device/system_bars] with no body
[debug] [WD Proxy] Got response with status 200: {"sessionId":"896a49ac-aa25-4ce3-bd64-aa7e4513ee28","value":{"statusBar":84}}
[debug] [WD Proxy] Matched '/window/current/size' to command name 'getWindowSize'
[debug] [WD Proxy] Proxying [GET /window/current/size] to [GET http://127.0.0.1:8201/wd/hub/session/896a49ac-aa25-4ce3-bd64-aa7e4513ee28/window/current/size] with no body
[debug] [WD Proxy] Got response with status 200: {"sessionId":"896a49ac-aa25-4ce3-bd64-aa7e4513ee28","value":{"height":2792,"width":1440}}
[Appium] New AndroidUiautomator2Driver session created successfully, session 9ac24c09-8dc7-4e23-88b8-6d871bcc3854 added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1622113199086 (19:59:59 GMT+0900 (대한민국 표준시))
[debug] [W3C (9ac24c09)] Cached the protocol value 'W3C' for the new session 9ac24c09-8dc7-4e23-88b8-6d871bcc3854
[debug] [W3C (9ac24c09)] Responding to client with driver.createSession() result: {"capabilities":{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"browserName":"Chrome","platformName":"android","automationName":"UiAutomator2","deviceName":"AppiumDriver"},"browserName":"Chrome","platformName":"android","automationName":"UiAutomator2","deviceName":"192.168.0.17:5555","appPackage":"com.android.chrome","appActivity":"com.google.android.apps.chrome.Main","deviceUDID":"192.168.0.17:5555","deviceApiLevel":29,"platformVersion":"10","deviceScreenSize":"1440x2960","deviceScreenDensity":560,"deviceModel":"SM-G965N","deviceManufacturer":"samsung","pixelRatio":3.5,"statBarHeight":84,"viewportRect":{"left":0,"top":84,"width":1440,"height":2708}}}
[HTTP] <-- POST /wd/hub/session 200 10741 ms - 879
[HTTP] 
[BaseDriver] Shutting down because we waited 60 seconds for a command
[Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[Appium] Removing session '57c3456d-def9-48f2-9b80-f6ecdd8d86bf' from our master session list
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [AndroidDriver] Stopping chromedriver for context CHROMIUM
[debug] [Chromedriver] Changed state to 'stopping'
[debug] [WD Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:8000/wd/hub/session/0343363c5742a06e0722d4d36a63b9ec] with no body
[debug] [WD Proxy] Got response with status 200: {"value":null}
[debug] [Chromedriver] Changed state to 'stopped'
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: 'DELETE /' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200 
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s 192.168.0.17:5555 forward --remove tcp:8200'
[UiAutomator2] Restoring hidden api policy to the device default configuration
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s 192.168.0.17\:5555 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[BaseDriver] Shutting down because we waited 60 seconds for a command
[Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[Appium] Removing session '9ac24c09-8dc7-4e23-88b8-6d871bcc3854' from our master session list
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [AndroidDriver] Stopping chromedriver for context CHROMIUM
[debug] [Chromedriver] Changed state to 'stopping'
[debug] [WD Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:8001/wd/hub/session/fceec38a6df6ce127b4db5f1c97254af] with no body
[debug] [WD Proxy] Got response with status 200: {"value":null}
[debug] [Chromedriver] Changed state to 'stopped'
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [WD Proxy] Matched '/' to command name 'deleteSession'
[debug] [WD Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:8201/wd/hub/session/896a49ac-aa25-4ce3-bd64-aa7e4513ee28] with no body
[debug] [WD Proxy] Got response with status 200: {"sessionId":"896a49ac-aa25-4ce3-bd64-aa7e4513ee28","value":null}
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8201 
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s 192.168.0.17:5555 forward --remove tcp:8201'
[UiAutomator2] Restoring hidden api policy to the device default configuration
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s 192.168.0.17\:5555 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[debug] [Instrumentation] .
[debug] [Instrumentation] Time: 65.698
[debug] [Instrumentation] 
[debug] [Instrumentation] OK (1 test)
[debug] [Instrumentation] The process has exited with code 0
```

**Comment by jinmoo21** [comment]
issue closed. it was my mistake :)
