### ISSUE TITLE
java.lang.ClassCastException: when trying to call method getVisualization().length

### ISSUE THREAD

**Issue by Pewliedie** [appium/java-client#1481]
## Description

I'm trying to use OccurrenceMatchingResult using openCV. When I'm calling method  getVisualization().length 
the error appears 

`java.lang.ClassCastException: class com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to class java.lang.String (com.google.common.collect.Maps$TransformedEntriesMap is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
	at io.appium.java_client.imagecomparison.ComparisonResult.getVisualization(ComparisonResult.java:63)
	at com.epam.ami.steps.common.CommonSteps.doVisualCheck(CommonSteps.java:203)
	at com.epam.ami.cases.BookWorkplaceTest.verifyHighlightingDateFieldInRedAndDisplayingHintTextIfDateOutsidePossiblePeriod(BookWorkplaceTest.java:190)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
`

## Environment

* Java client build version or git revision if you use some snapshot: java-client 7.5.1, java version "16.0.1" 2021-04-20
* Appium server version or git revision if you use some snapshot: 1.20.2 
* Desktop OS/version used to run Appium if necessary: Windows 19042.964
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: node v14.17.0
* Mobile platform/version under test: Android API 29
* Real device or emulator/simulator: emulator Android Pixel 2

## Code To Reproduce Issue [ Good To Have ]

`public void doVisualCheck(String baseLineScreenshoot) throws IOException {
        OccurrenceMatchingResult res = null;
        try {
            res = DriverManager.getDriver().findImageOccurrence(new File(baseLineScreenshoot), new File("src/main/resources/baselineScreens/bookWPNExus.png"),
                    new OccurrenceMatchingOptions().withEnabledVisualization());
        } catch (IOException e) {
            e.printStackTrace();
        }
        var softAssertion = new SoftAssertions();
        softAssertion.assertThat(res.getRect())
                .overridingErrorMessage("screens are not equal")
                .isNotNull();
        softAssertion.assertThat(assertThat(res.getVisualization().length)
                .overridingErrorMessage("err")
                .isGreaterThan(ZERO));
        softAssertion.assertAll();
    }`

## Exception Stacktraces

Please create a [gist](https://gist.github.com) with the pasted stacktrace of the exception thrown by java.
https://gist.github.com/Pewliedie/d62507b25670aca8d766b2e1c0abd5f6

**Comment by mykola-mokhnach** [comment]
- Make sure you use the most recent Appium server version (preferably appium@beta)
- Please provide the actual server log as well

**Comment by Pewliedie** [comment]
here is log [appiumLog.txt](https://github.com/appium/java-client/files/6591614/appiumLog.txt)
updated to the latest version Appium, The problem is still reproducible

**Comment by mykola-mokhnach** [comment]
It should be resolved in appium@beta

**Comment by Pewliedie** [comment]
Yes it is, the problem is solved by npm install -g appium@beta.
Thank you!
