### ISSUE TITLE
Im getting org.openqa.selenium.UnsupportedCommandException: actions , exception when executing in BrowserStack  environment. 

### ISSUE THREAD

**Issue by prasannaThanu** [appium/java-client#1489]
## Description
Im getting org.openqa.selenium.UnsupportedCommandException: actions , exception when executing in BrowserStack  environment for IOS devices . But while executing in local machine for IOS simulator same thing is working as expected

## Environment

* Java client build version or git revision if you use some snapshot: 7.5.1
* Appium server version or git revision if you use some snapshot: 1.17.0
* Desktop OS/version used to run Appium if necessary:MAC 10.15.7[Catalina]
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: Iphone 11 version: 14.0
* Real device or emulator/simulator: Real Device

## Details

Working for IOS Simulator in local system but throwing exception while execution on browserstack environment

##Logs
org.openqa.selenium.UnsupportedCommandException: actions
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'MacBooks-MacBook-Pro.local', ip: 'fe80:0:0:0:892:864d:88fe:44f6%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '1.8.0_281'
Driver info: driver.version: RemoteWebDriver
        at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:218)
        at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:117)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:152)
        at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:247)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
        at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
        at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
        at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
        at org.openqa.selenium.remote.RemoteWebDriver.perform(RemoteWebDriver.java:618)
        at Utilities.CommonMethods.swipe(CommonMethods.java:197)
        at Utilities.CommonMethods.scroll(CommonMethods.java:174)
        at Utilities.CommonMethods.ScrollIOS(CommonMethods.java:213)
        at StepDefinition.SelfInspection_SD.click_on_Next_button(SelfInspection_SD.java:293)
        at ✽.Then CLick on Next button(SelfInspection.feature:18)

**Comment by prasannaThanu** [comment]
@mykola-mokhnach could U plz help me on this

**Comment by mykola-mokhnach** [comment]
Unfortunately I cannot. Consider contacting BS customer support.

**Comment by RSV7** [comment]
@prasannaThanu have you solved it?

**Comment by prasannaThanu** [comment]
Yes, i got that exception because of version mismatch

**Comment by vasilyvoitenko** [comment]
@prasannaThanu could you please specify what kind of version mismatch? I'm getting the same exception with BS.
