### ISSUE TITLE
Getting java.lang.reflect.InvocationTargetException using PageFactory for IOSDriver

### ISSUE THREAD

**Issue by srikanthqa** [appium/java-client#149]
Issue only happens with IOSDriver, but works fine with AndroidDriver

Appium Server Version: 1.3.4
Selenium-Java Version:2.44.0

Error Log Trace:

java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at io.appium.java_client.pagefactory.ElementInterceptor.intercept(ElementInterceptor.java:27)
	at org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$3e0229bb.click(<generated>)
	at com.automation.mobile.flickr.TempPage.clickEditDescriptionBtn(TempPage.java:15)
	at com.automation.mobile.flickr.SampleTest.testFlickr(SampleTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.26 seconds
Build info: version: '2.43.0', revision: 'accb3003b9fb8f7cae30f9669b4c594a065396a6', time: '2014-09-09 22:22:51'
System info: host: 'Srikanths-MacBook-Air.local', ip: '10.0.0.2', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.7.0_71'
Session ID: 2c2fbb1f-e373-471b-9375-8bb7280b1c43
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{platform=MAC, javascriptEnabled=true, browserName=iOS, networkConnectionEnabled=false, udid=5e66e1067a0afea89be55a2d06322a98344023bb, desired={platformVersion=8.1, platformName=iOS, deviceName=iPhone, bundleId=com.yahoo.flickr, udid=5e66e1067a0afea89be55a2d06322a98344023bb}, locationContextEnabled=false, platformVersion=8.1, databaseEnabled=false, deviceName=iPhone, platformName=iOS, webStorageEnabled=false, bundleId=com.yahoo.flickr, warnings={}, takesScreenshot=true}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:180)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:79)
	... 36 more

Server Log:

info: [debug] Pushing command to appium work queue: "au.tapById('4')"
info: [debug] Sending command to instruments: au.tapById('4')
info: [debug] [INST] 2015-02-03 04:12:40 +0000 Debug: Got new command 12 from instruments: au.tapById('4')
info: [debug] [INST] 2015-02-03 04:12:40 +0000 Debug: evaluating au.tapById('4')
info: [debug] [INST] 2015-02-03 04:12:40 +0000 Debug: UIAButton.tap()
info: [debug] [INST] 2015-02-03 04:12:40 +0000 Debug: UIAButton.scrollToVisible()
info: [debug] [INST] 2015-02-03 04:12:40 +0000 Debug: UIAButton - scrollToVisible cannot be used because this element has no scrollable ancestor.
info: [debug] [INST] 2015-02-03 04:12:40 +0000 Debug: UIAButton - scrollToVisible cannot be used because this element has no scrollable ancestor.
info: [debug] [INST] 2015-02-03 04:12:40 +0000 Debug: UIAButton could not be tapped because the element is not visible
info: [debug] Socket data received (57 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":13,"value":"elementId 4 could not be tapped"}
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"elementId 4 could not be tapped"},"sessionId":"2c2fbb1f-e373-471b-9375-8bb7280b1c43"}
info: <-- POST /wd/hub/session/2c2fbb1f-e373-471b-9375-8bb7280b1c43/element/4/click 500 1248.761 ms - 200 
info: --> DELETE /wd/hub/session/2c2fbb1f-e373-471b-9375-8bb7280b1c43 {}
info: Shutting down appium session
info: [debug] Stopping ios
info: [debug] Destroying instruments client socket.
info: [debug] Closing socket server.
info: [debug] Instruments socket server was closed
info: [debug] Sending sigterm to instruments
info: [debug] [INST] 2015-02-03 04:12:40 +0000 Stopped: Script was stopped by the user
info: [debug] [INST] 2015-02-03 04:12:40 +0000 Error: VerboseError: elementId 4 could not be tapped
info: [debug] [INST] 2015-02-03 04:12:40 +0000 Error: Error during eval: tapById@file:///usr/local/lib/node_modules/appium/F9058AFA-314F-4031-A36C-DD5E464B313C/bootstrap-8fc1d1e3e10cb9cb.js:1095:25
       eval code
eval@[native code]
startProcessing@file:///usr/local/lib/node_modules/appium/F9058AFA-314F-4031-A36C-DD5E464B313C/bootstrap-8fc1d1e3e10cb9cb.js:2663:30
bootstrap@file:///usr/local/lib/node_modules/appium/F9058AFA-314F-4031-A36C-DD5E464B313C/bootstrap-8fc1d1e3e10cb9cb.js:2729:31
global code@file:///usr/local/lib/node_modules/appium/F9058AFA-314F-4031-A36C-DD5E464B313C/bootstrap-8fc1d1e3e10cb9cb.js:2738:10
info: [debug] [INST] 2015-02-03 04:12:40 +0000 Debug: responding with:
       2015-02-03 04:12:40 +0000 Debug: Running system command #13: /usr/local/Cellar/node/0.10.35/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":13,"value":"elementId 4 could not be tapped"}...
info: [debug] [INST] Instruments Trace Complete (Duration : 33.763096s; Output : /tmp/appium-instruments/instrumentscli0.trace)
info: [debug] [INSTSERVER] Instruments exited with code 0
info: [debug] Cleaning up after instruments exit
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killall iOS Simulator
info: [debug] Killing any other simulator daemons
info: [debug] On a real device; cannot clean device state
info: [debug] Cleaning up appium session
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"2c2fbb1f-e373-471b-9375-8bb7280b1c43"}
info: <-- DELETE /wd/hub/session/2c2fbb1f-e373-471b-9375-8bb7280b1c43 200 892.393 ms - 76 {"status":0,"value":null,"sessionId":"2c2fbb1f-e373-471b-9375-8bb7280b1c43"}

**Comment by TikhomirovSergey** [comment]
Hi! I think it is not the java - client issue. The target is found but it is not clickable
>  /usr/local/Cellar/node/0.10.35/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":13,"value":"elementId 4 could not be tapped"}...

It is possible that the bug on the server side:
https://github.com/appium/appium/issues/4286

It is going to be fixed in 1.3.6

**Comment by TikhomirovSergey** [comment]
It is closed because it is not the issue of java-client
