### ISSUE TITLE
Appium Driver Java client Issue

### ISSUE THREAD

**Issue by min2bro** [appium/java-client#153]
Hi,

I am getting this error using appium driver java client v1.7..The webdriver version used here is 2.39...

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.cirrus.qa.hybridengine.DriverScript.executeKeywords(DriverScript.java:168)
	at com.cirrus.qa.hybridengine.DriverScript.start(DriverScript.java:124)
	at com.cirrus.qa.hybridengine.DriverScript.main(DriverScript.java:68)
Caused by: java.lang.NoSuchMethodError: com.google.common.collect.Multimaps.transformValues(Lcom/google/common/collect/ListMultimap;Lcom/google/common/base/Function;)Lcom/google/common/collect/ListMultimap;
	at com.google.common.net.MediaType.toString(MediaType.java:708)
	at org.openqa.selenium.remote.http.JsonHttpCommandCodec.encode(JsonHttpCommandCodec.java:197)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:572)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:102)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:153)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:53)
	at com.cirrus.qa.hybridengine.Keywords.setUpApp(Keywords.java:339)
	... 7 more

**Comment by Jonahss** [comment]
Well, the newest version of the appium java-client is 1.2.0 so you should try using that.

**Comment by min2bro** [comment]
tried using java-client 1.2.0. Now I'm getting this error

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.mobile.hybrid.DriverScript.executeKeywords(DriverScript.java:175)
	at com.mobile.hybrid.DriverScript.start(DriverScript.java:131)
	at com.mobile.hybrid.DriverScript.main(DriverScript.java:75)
Caused by: java.lang.NoSuchFieldError: INSTANCE
	at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:52)
	at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:56)
	at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<clinit>(DefaultHttpRequestWriterFactory.java:46)
	at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:72)
	at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:84)
	at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<clinit>(ManagedHttpClientConnectionFactory.java:59)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$InternalConnectionFactory.<init>(PoolingHttpClientConnectionManager.java:487)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:147)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:136)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:112)
	at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:726)
	at org.apache.http.impl.client.HttpClients.createDefault(HttpClients.java:58)
	at io.appium.java_client.ComplexFind.<clinit>(ComplexFind.java:15)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:46)
	at com.mobile.hybrid.Keywords.setUpApp(Keywords.java:354)
	... 7 more

**Comment by Jonahss** [comment]
Are you using Java 7? Are you sure your dependencies are set up correctly?

**Comment by min2bro** [comment]
Yes all my dependencies are set up correctly...Do u want me to share the piece of code?

**Comment by TikhomirovSergey** [comment]
Hi @min2bro
>tried using java-client 1.2.0. Now I'm getting this error
The actual stable version is 2.1.0. Do you really use 1.2.0? I think @Jonahss made a little typo :)
>Well, the newest version of the appium java-client is 1.2.0

What is your server version? I think that complex find doesn't work with the server that higher than 1.2.4 - 1.3.0. Actually it was removed in 2.0.0
> at io.appium.java_client.ComplexFind.(ComplexFind.java:15)
at io.appium.java_client.AppiumDriver.(AppiumDriver.java:46)

Also I am suspecting the version conflict of com.google.* artefacts at your project.
I am waiting for your responce.

**Comment by Jonahss** [comment]
Ah yes I typo'd again. Thanks @TikhomirovSergey

**Comment by snailwin** [comment]
same question, current java-client version is 1.4.2
how to solve this problem , thanks @TikhomirovSergey @ Jonahss 

`2016-09-23 14:32:51 sys_log : [INFO] Appium Server -> http://127.0.0.1:4723/wd/hub
Exception in thread "main" java.lang.NoSuchFieldError: INSTANCE
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.j
ava:144)
        at org.openqa.selenium.remote.internal.HttpClientFactory.getClientConnectionManager(HttpClie
ntFactory.java:71)
        at org.openqa.selenium.remote.internal.HttpClientFactory.<init>(HttpClientFactory.java:57)
        at org.openqa.selenium.remote.internal.HttpClientFactory.<init>(HttpClientFactory.java:60)
        at org.openqa.selenium.remote.internal.ApacheHttpClient$Factory.getDefaultHttpClientFactory(
ApacheHttpClient.java:252)
        at org.openqa.selenium.remote.internal.ApacheHttpClient$Factory.<init>(ApacheHttpClient.java
:229)
        at io.appium.java_client.remote.AppiumCommandExecutor.<init>(AppiumCommandExecutor.java:55)
        at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:131)
        at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:92)
        at com.sprd.test.appspider.traverse.Traverse.beforeTraverse(Traverse.java:210)
        at com.sprd.test.appspider.traverse.Traverse.traverse(Traverse.java:74)
        at com.sprd.test.appspider.traverse.Traverse.start(Traverse.java:289)
        at com.sprd.test.appspider.main.SpiderConsole.main(SpiderConsole.java:18)`
