### ISSUE TITLE
BrowserStack unable to create new session with Appium 8 Beta

### ISSUE THREAD

**Issue by darkfrog26** [appium/java-client#1579]
## Description

Attempting to upgrade to Selenium 4 and Appium 8 Beta seems to break BrowserStack. Local testing works great, but when I attempt to establish a session with BrowserStack with the following capabilities:

```
browserName = ios
browserstack.appium_version = 1.21.0
browserstack.console = info
browserstack.idleTimeout = 300
browserstack.local = false
browserstack.networkLogs = true
build = LiveVideoStreamTests
device = iPhone XS
goog:chromeOptions = {args=[--ignore-certificate-errors, --no-sandbox, --disable-dev-shm-usage, use-fake-device-for-media-stream, use-fake-ui-for-media-stream], extensions=[]}
name = iPhone XS
os_version = 15
platform = ANY
real_mobile = true
```

I get this stack trace:

```
[info] Caused by: org.openqa.selenium.WebDriverException: Error : Platform can be one of MAC, WIN8, XP, WINDOWS, and ANY (WARNING: The server did not provide any stacktrace information)
[info] Command duration or timeout: 285 milliseconds
[info] Build info: version: '4.0.0', revision: '3a21814679'
[info] System info: host: 'mhicks-pc', ip: 'xxx.xxx.xxx.xxx', os.name: 'Linux', os.arch: 'amd64', os.version: '5.14.14-1-default', java.version: '1.8.0_292'
[info] Driver info: driver.version: IOSDriver
[info]  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info]  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[info]  at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:217)
[info]  at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:169)
[info]  at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$errorHandler$0(JsonWireProtocolResponse.java:54)
[info]  at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
[info]  at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$1(ProtocolHandshake.java:133)
[info]  at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[info]  at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
[info]  at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
[info]  at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
[info]  at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
[info]  at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[info]  at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
[info]  at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[info]  at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531)
[info]  at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:135)
[info]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info]  at java.lang.reflect.Method.invoke(Method.java:498)
[info]  at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:126)
[info]  at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:102)
[info]  at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:146)
[info]  at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:180)
[info]  at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:559)
[info]  at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:225)
[info]  at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:168)
[info]  at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:79)
[info]  at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:87)
[info]  at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:105)
[info]  at live.LiveVideoStreamTests$$anon$1.createWebDriver(LiveVideoStreamTests.scala:407)
[info]  at com.outr.robobrowser.RoboBrowser.com$outr$robobrowser$RoboBrowser$$_driver(RoboBrowser.scala:39)
[info]  at com.outr.robobrowser.RoboBrowser.com$outr$robobrowser$RoboBrowser$$_driver$(RoboBrowser.scala:35)
[info]  at com.outr.robobrowser.appium.RoboIOS.com$outr$robobrowser$RoboBrowser$$_driver$lzycompute(RoboIOS.scala:8)
[info]  at com.outr.robobrowser.appium.RoboIOS.com$outr$robobrowser$RoboBrowser$$_driver(RoboIOS.scala:8)
[info]  at com.outr.robobrowser.RoboBrowser.driver(RoboBrowser.scala:45)
[info]  at com.outr.robobrowser.RoboBrowser.driver$(RoboBrowser.scala:42)
[info]  at com.outr.robobrowser.appium.RoboIOS.driver(RoboIOS.scala:9)
[info]  at com.outr.robobrowser.appium.RoboIOS.driver(RoboIOS.scala:8)
[info]  at com.outr.robobrowser.RoboBrowser.load(RoboBrowser.scala:77)
[info]  at com.outr.robobrowser.RoboBrowser.load$(RoboBrowser.scala:77)
[info]  at com.outr.robobrowser.appium.RoboIOS.load(RoboIOS.scala:8)
[info]  at live.LiveVideoStreamTests.$anonfun$new$4(LiveVideoStreamTests.scala:43)
[info]  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info]  at com.outr.robobrowser.integration.IntegrationTests.$anonfun$run$7(IntegrationTests.scala:93)
[info]  at scribe.data.MDCMap.contextualize(MDCMap.scala:17)
[info]  at scribe.data.MDC$.contextualize(MDC.scala:30)
[info]  at com.outr.robobrowser.integration.IntegrationTests.recurse$1(IntegrationTests.scala:93)
[info]  at com.outr.robobrowser.integration.IntegrationTests.recurse$1(IntegrationTests.scala:103)
[info]  at com.outr.robobrowser.integration.IntegrationTests.$anonfun$run$1(IntegrationTests.scala:115)
[info]  at scribe.LoggerSupport.elapsed(LoggerSupport.scala:117)
[info]  at scribe.LoggerSupport.elapsed$(LoggerSupport.scala:112)
[info]  at scribe.package$.elapsed(package.scala:6)
[info]  at com.outr.robobrowser.integration.IntegrationTests.run(IntegrationTests.scala:74)
[info]  at com.outr.robobrowser.integration.IntegrationTests.run$(IntegrationTests.scala:73)
[info]  at live.LiveVideoStreamTests.run(LiveVideoStreamTests.scala:20)
[info]  at com.outr.robobrowser.integration.IntegrationTestSuite.recurse(IntegrationTestSuite.scala:67)
[info]  at com.outr.robobrowser.integration.IntegrationTestSuite.main(IntegrationTestSuite.scala:47)
[info]  at com.outr.robobrowser.integration.IntegrationTestSuite.main$(IntegrationTestSuite.scala:25)
[info]  at live.PreparedSuite$.main(PreparedSuite.scala:7)
[info]  at live.PreparedSuite.main(PreparedSuite.scala)
[info]  (elapsed: 6.05s)
```

## Environment

* Java client build version or git revision if you use some snapshot: 8.0.0-beta
* Appium server version or git revision if you use some snapshot: BrowserStack
* Desktop OS/version used to run Appium if necessary: N/A
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: N/A
* Mobile platform/version under test: IOS 15 on iPhone XS
* Real device or emulator/simulator: Real (BrowserStack)

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

I've tried with several basic scenarios and it seems that BrowserStack just doesn't want to work with Appium 8 for some reason.

## Exception Stacktraces

See above

## Link To Appium Logs

No logs are generated since the session fails to create.

**Comment by mykola-mokhnach** [comment]
Have you tried to contact their customer support?

**Comment by valfirst** [comment]
@darkfrog26 it seems you are using capabilities for legacy protocol, check the configurator: https://www.browserstack.com/automate/capabilities?tag=selenium-4

**Comment by darkfrog26** [comment]
@mykola-mokhnach yes, I have, but they haven't been very helpful thus far.
@valfirst I just realized this and that solved the problem. Thanks for the quick response!
