### ISSUE TITLE
java.lang.ClassCastException: tests.DesireCapabilities cannot be cast to org.openqa.selenium.Capabilities

### ISSUE THREAD

**Issue by Poonam2212** [appium/java-client#1625]
my code is  : 
```java
package tests;

import java.net.MalformedURLException;
import java.net.URL;

import org.openqa.selenium.Capabilities;
import org.openqa.selenium.remote.CapabilityType;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileElement;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.ios.IOSDriver;
import io.appium.java_client.remote.MobileCapabilityType;

public class BaseClass {
	
	
	AppiumDriver<MobileElement> driver;
	
	@BeforeTest
	public void setup() {
		try {
		// i want run before a test i will put here
		
//		caps.setCapability("platformName", "ANDROID"); +
		DesireCapabilities caps = new DesireCapabilities();
		caps.setCapability(MobileCapabilityType.PLATFORM_NAME, "ANDROID");
	//	caps.setCapability(CapabilityType.PLATFORM_NAME, "ANDROID");
		caps.setCapability(MobileCapabilityType.PLATFORM_VERSION, "11"); // here give your android version
		caps.setCapability(MobileCapabilityType.DEVICE_NAME, "V2111"); // here give your device name
		caps.setCapability(MobileCapabilityType.UDID, "1363349013001GL"); // here give your device id
		caps.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, "60");
//		caps.setCapability(MobileCapabilityType.APP, "");
		caps.setCapability(MobileCapabilityType.BROWSER_NAME, "Chrome");
		
		URL url = new URL("http://127.0.0.1:4723/wd/hub");	
		
		driver = new AppiumDriver<MobileElement>(url, (Capabilities) caps);
//		driver = new AndroidDriver<MobileElement>(url, caps);
//		driver = new IOSDriver<MobileElement>(url, caps);
		
		} catch(Exception exp) {
			System.out.println("Cause is :"+exp.getCause());
			System.out.println("Message is :"+exp.getMessage());
			exp.printStackTrace();
		}
	}
	
	@Test
	public void sampleTest () {
		System.out.println("Welcome");
	}
	
	@AfterTest
	public void teardown() {
		// i want run after a test i will put here
	}

}
```

i am getting : 

```java
java.lang.ClassCastException: tests.DesireCapabilities cannot be cast to org.openqa.selenium.Capabilities
	at tests.BaseClass.setup(BaseClass.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:529)
	at org.testng.TestRunner.run(TestRunner.java:497)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
```

**Comment by valfirst** [comment]
@Poonam2212 you have your class `tests.DesireCapabilities` which doesn't implement `org.openqa.selenium.Capabilities`, that's why you see `java.lang.ClassCastException` (you can find more details here, for example: https://stackoverflow.com/questions/907360/explanation-of-classcastexception-in-java )

**Comment by Poonam2212** [comment]
@valfirst  i don't understand what you say, can you explain me please

**Comment by valfirst** [comment]
@Poonam2212 
> you can find more details here, for example: https://stackoverflow.com/questions/907360/explanation-of-classcastexception-in-java

or you can search for any other explanations of `java.lang.ClassCastException`
