### ISSUE TITLE
Cannot decorate AndroidDriver (probably the same for IOSDriver

### ISSUE THREAD

**Issue by bhecquet** [appium/java-client#1643]
## Description

I'm trying to use the decorator mechanism provided by selenium 4. 
But following the doc to decorate the android driver, I get the exception

```
java.lang.IllegalStateException: Invisible interface type interface io.appium.java_client.android.HasAndroidSettings for class net.bytebuddy.renamed.java.lang.Object$ByteBuddy$Eik9i4kq
```
Full stacktrace is below

As I understand, this is due to the fact that HasAndroidSettings is not public

## Environment

* Java client build version or git revision if you use some snapshot: 8.0.0-beta2
* Appium server version or git revision if you use some snapshot: 1.18.1
* Desktop OS/version used to run Appium if necessary: Windows 10
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: Appium.exe
* Mobile platform/version under test: android
* Real device or emulator/simulator: android simulator

## Code To Reproduce Issue [ Good To Have ]

```java
UiAutomator2Options options = new UiAutomator2Options();
AndroidDriver mobileDriver = new AndroidDriver(new URL("http://appiumServer:4723/wd/hub"), options);
new EventFiringDecorator(new MyListener()).decorate(mobileDriver);
```

mobileDriver is correctly created, but applying decoration fails with the stacktrace

## Exception Stacktraces

```
java.lang.IllegalStateException: Invisible interface type interface io.appium.java_client.android.HasAndroidSettings for class net.bytebuddy.renamed.java.lang.Object$ByteBuddy$Eik9i4kq
	at net.bytebuddy.dynamic.scaffold.InstrumentedType$Default.validated(InstrumentedType.java:1222)
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:519)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:207)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:198)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3404)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:3600)
	at org.openqa.selenium.support.decorators.WebDriverDecorator.createProxy(WebDriverDecorator.java:323)
	at org.openqa.selenium.support.decorators.WebDriverDecorator.decorate(WebDriverDecorator.java:190)
```

## Link To Appium Logs

Appium logs are not relevant as the problem resides in java_client

**Comment by mykola-mokhnach** [comment]
Yes, it makes sense to make these interfaces public. Please let us know if there are any other hidden ones that must be published

**Comment by bhecquet** [comment]
It seems that only HasAndroidSettings and HasIOSSettings are private

**Comment by mykola-mokhnach** [comment]
The patch has been published. You could try the change by fetching the recent build from jitpack as described in https://github.com/appium/java-client#maven

**Comment by bhecquet** [comment]
Thanks!
