### ISSUE TITLE
getting error on AppiumServiceBuilder with appium2.0.beta@26

### ISSUE THREAD

**Issue by StephanB75** [appium/java-client#1667]
## Description

The installed drivers could not be loaded. They are installed in the APPIUM_HOME but it look like the latest changes in the appium server regarding driver installation via NPM has broke something within the AppiumServiceBuilder.

## Environment

* Java client build version or git revision if you use some snapshot: 8.0
* Appium server version or git revision if you use some snapshot: 2.0beta@26
* Desktop OS/version used to run Appium if necessary:
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 14
* Mobile platform/version under test: ios/android
* Real device or emulator/simulator: simulator

## Details

Until now i have installed the appium drivers with a postscript via npm install and they were located directly in .appium folder.
Now the same postinstall script installs them into a subfolder "node_modules" within the .appium folder and the tests can't find them. Do i have to change the script or the appium home path i set for the appium

![image](https://user-images.githubusercontent.com/90029825/159674259-ee68828b-1571-4d0d-adab-cdc47082b84b.png)

i could "workaround" the problem by do a "npm install resolve-from" within the folder "/.appium/node_modules/appium-xcuitest-driver"

## Exception Stacktraces

`2022-03-23 11:08:44:285 - Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: Could not find a driver for automationName 'XCUITest' and platformName ios'. Have you installed a driver that supports those capabilities? Run 'appium driver list --installed' to see. (Lower-level error: Cannot find module 'resolve-from'
Require stack:
- /Users/st.xxx/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/support/build/lib/npm.js
- /Users/st.xxx/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/support/build/lib/env.js
- /Users/st.xxx/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/support/build/lib/index.js
- /Users/st.xxx/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/support/index.js
- /Users/st.xxx/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/build/lib/protocol/protocol.js
- /Users/st.xxx/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/build/lib/protocol/index.js
- /Users/st.xxx/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/build/lib/basedriver/driver.js
- /Users/st.xxx/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/build/lib/index.js
- /Users/st.xxx/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/index.js
- /Users/st.xxx/.appium/node_modules/appium-xcuitest-driver/build/lib/driver.js
- /Users/st.xxx/.appium/node_modules/appium-xcuitest-driver/build/index.js
- /Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/appium/build/lib/extension/extension-config.js
- /Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/appium/build/lib/cli/extension-command.js
- /Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/appium/build/lib/cli/driver-command.js
- /Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/appium/build/lib/cli/extension.js
- /Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/appium/build/lib/main.js
- /Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/appium/index.js)
- 
- - [debug] [AppiumDriver@a532febe]     at DriverConfig.findMatchingDriver (/Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/appium/lib/extension/driver-config.js:172:14)
2022-03-23 11:08:44:157 - [debug] [AppiumDriver@a532febe]     at AppiumDriver.createSession (/Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/appium/lib/appium.js:194:29)
2022-03-23 11:08:44:157 - [debug] [AppiumDriver@a532febe]     at commandExecutor (/Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/@appium/base-driver/lib/basedriver/driver.js:346:7)
2022-03-23 11:08:44:158 - [debug] [AppiumDriver@a532febe]     at AppiumDriver.executeCommand (/Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/@appium/base-driver/lib/basedriver/driver.js:360:15)
2022-03-23 11:08:44:158 - [debug] [AppiumDriver@a532febe]     at defaultBehavior (/Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/appium/lib/appium.js:538:28)
2022-03-23 11:08:44:158 - [debug] [AppiumDriver@a532febe]     at ImageElementPlugin.handle (/Users/st.xxx/.appium/node_modules/@appium/images-plugin/lib/plugin.js:78:18)
2022-03-23 11:08:44:158 - [debug] [AppiumDriver@a532febe]     at wrappedCmd (/Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/appium/lib/appium.js:587:29)
2022-03-23 11:08:44:158 - [debug] [AppiumDriver@a532febe]     at AppiumDriver.executeWrappedCommand (/Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/appium/lib/appium.js:620:22)
2022-03-23 11:08:44:159 - [debug] [AppiumDriver@a532febe]     at AppiumDriver.executeCommand (/Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/appium/lib/appium.js:549:28)
2022-03-23 11:08:44:159 - [debug] [AppiumDriver@a532febe]     at asyncHandler (/Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/@appium/base-driver/lib/protocol/protocol.js:315:32)
2022-03-23 11:08:44:159 - [debug] [AppiumDriver@a532febe]     at /Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/@appium/base-driver/lib/protocol/protocol.js:413:15
2022-03-23 11:08:44:159 - [debug] [AppiumDriver@a532febe]     at Layer.handle [as handle_request] (/Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/express/lib/router/layer.js:95:5)
2022-03-23 11:08:44:159 - [debug] [AppiumDriver@a532febe]     at next (/Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/express/lib/router/route.js:137:13)
2022-03-23 11:08:44:160 - [debug] [AppiumDriver@a532febe]     at Route.dispatch (/Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/express/lib/router/route.js:112:3)
2022-03-23 11:08:44:160 - [debug] [AppiumDriver@a532febe]     at Layer.handle [as handle_request] (/Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/express/lib/router/layer.js:95:5)
2022-03-23 11:08:44:160 - [debug] [AppiumDriver@a532febe]     at /Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/express/lib/router/index.js:281:22
2022-03-23 11:08:44:160 - [debug] [AppiumDriver@a532febe]     at Function.process_params (/Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/express/lib/router/index.js:341:12)
2022-03-23 11:08:44:160 - [debug] [AppiumDriver@a532febe]     at next (/Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/express/lib/router/index.js:275:10)
2022-03-23 11:08:44:160 - [debug] [AppiumDriver@a532febe]     at logger (/Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/morgan/index.js:144:5)
2022-03-23 11:08:44:160 - [debug] [AppiumDriver@a532febe]     at Layer.handle [as handle_request] (/Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/express/lib/router/layer.js:95:5)
2022-03-23 11:08:44:160 - [debug] [AppiumDriver@a532febe]     at trim_prefix (/Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/express/lib/router/index.js:323:13)
2022-03-23 11:08:44:161 - [debug] [AppiumDriver@a532febe]     at /Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/express/lib/router/index.js:284:7
2022-03-23 11:08:44:161 - [debug] [AppiumDriver@a532febe]     at Function.process_params (/Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/express/lib/router/index.js:341:12)
2022-03-23 11:08:44:161 - [debug] [AppiumDriver@a532febe]     at next (/Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/express/lib/router/index.js:275:10)
2022-03-23 11:08:44:161 - [debug] [AppiumDriver@a532febe]     at /Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/body-parser/lib/read.js:130:5
2022-03-23 11:08:44:161 - [debug] [AppiumDriver@a532febe]     at invokeCallback (/Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/raw-body/index.js:224:16)
2022-03-23 11:08:44:162 - [debug] [AppiumDriver@a532febe]     at done (/Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/raw-body/index.js:213:7)
2022-03-23 11:08:44:162 - [debug] [AppiumDriver@a532febe]     at IncomingMessage.onEnd (/Users/st.xxx/git/rossapp-ios-uitest_java/node_modules/raw-body/index.js:273:7)`

**Comment by mykola-mokhnach** [comment]
@boneskull could you please take a look? Could it be the above dependency is missing in some package manifest?

**Comment by mykola-mokhnach** [comment]
@StephanB75 You could try to fully reinstall the server as a possible workaround

**Comment by StephanB75** [comment]
i have uninstalled and installed several times the appium node package and the drivers completely.
All the time the drivers could not be loaded because of the above error. Only manually installing the resolve-from package worked. But that for every driver.

**Comment by boneskull** [comment]
`resolve-from` could be missing somewhere in appium.. I'll check

**Comment by boneskull** [comment]
https://github.com/appium/appium/pull/16643

**Comment by boneskull** [comment]
@StephanB75 Try 2.0.0-beta26 which was just published a minute ago

**Comment by StephanB75** [comment]
> @StephanB75 Try 2.0.0-beta26 which was just published a minute ago

Big thanks for your super fast response . I will try the fix tomorrow morning and give you feedback

**Comment by boneskull** [comment]
sorry, beta27?

**Comment by StephanB75** [comment]
@boneskull Works ! Thank you again :)
