### ISSUE TITLE
Method is not implemented    at XCUITestDriver.closeWindow

### ISSUE THREAD

**Issue by JonathanOrtegon-L** [appium/java-client#1692]
## Description

I'm doing a migration from Appium 7.3 to 8.0, but I have problems with closing the app without terminating the driver session with driver.close(), but the error occurs on execution

` {"value":{"error":"unknown method","message":"Method is not implemented","stacktrace":"NotImplementedError: Method is not implemented\n    at XCUITestDriver.closeWindow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/navigation.js:49:11)\n    at commandExecutor (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:335:9)\n    at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/async-lock/lib/index.js:137:12\n    at AsyncLock._promiseTry (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/async-lock/lib/index.js:261:31)\n    at exec (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/async-lock/lib/index.js:136:9)\n    at AsyncLock.acquire (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/async-lock/lib/index.js:152:3)\n    at XCUITestDriver.executeCommand (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:348:39)\n    at XCUITestDriver.executeCommand (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:731:24)\n    at AppiumDriver.executeCommand (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/lib/appium.js:563:36)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:85:5)\n    at asyncHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:297:21)"}}`

## Environment

* Serenity 3.2.4
* Java 11 Correto
* Appium 8.0.0:
* Desktop MacOS BigSur
* Mobile platformt  ios 14.5 on iPhone 12 Pro Max:
* Emulator:

## Code To Reproduce Issue [ Good To Have ]

package lulobank.automation.frontend.utils.drivers;

import io.appium.java_client.AppiumDriver;
import net.thucydides.core.util.EnvironmentVariables;
import net.thucydides.core.util.SystemEnvironmentVariables;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Objects;

import static org.apache.commons.lang3.StringUtils.stripAccents;

```
public final class LocalAppiumDriver {

    private static final Logger logger = LoggerFactory.getLogger(LocalAppiumDriver.class);
    private AppiumDriver driver;
    private static LocalAppiumDriver currentDriver;

    private static String nameScenario;

    public static AppiumDriver mobile() throws IOException {

        DesiredCapabilities capabilities = new DesiredCapabilities();
        currentDriver = new LocalAppiumDriver();

        TargetExecution targetExecution = TargetExecution.getTargetExecution();
        String appiumUrl = targetExecution.getAppiumUrl();
        setCapabilities(targetExecution, capabilities);

        try {
            currentDriver.driver = new AppiumDriver(new URL(appiumUrl), capabilities);
        } catch (MalformedURLException e) {
            logger.error("MalformedURLException ", e);
        }

        return currentDriver.driver;
    }

    private static DesiredCapabilities setCapabilities(TargetExecution targetExecution, DesiredCapabilities capabilities) {
        targetExecution.capabilities.forEach(capabilities::setCapability);
        capabilities.setCapability("name", getScenarioName());
        return capabilities;
    }

    private static String getScenarioName() {
        return nameScenario;
    }

    public static void setScenarioName(String scenarioName) {
        nameScenario = stripAccents(scenarioName);
    }

    public static AppiumDriver getDriver() {
        return currentDriver.driver;
    }

    public static boolean isThePlatformIOS() {
        return Objects.requireNonNull(getDriver().getCapabilities().getPlatformName().name()).equalsIgnoreCase("ios");
    }

    public static boolean isTheAppiumConfigGRID() {
        EnvironmentVariables variables = SystemEnvironmentVariables.createEnvironmentVariables();
        String appiumConfig = variables.getProperty("appiumconfig");
        return appiumConfig.equalsIgnoreCase("grid");
    }

    public static void resetApp() {
        currentDriver.driver.close();
    }

}

```

## Exception Stacktraces

```
org.openqa.selenium.UnsupportedCommandException: {"value":{"error":"unknown method","message":"Method is not implemented","stacktrace":"NotImplementedError: Method is not implemented\n    at XCUITestDriver.closeWindow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/navigation.js:49:11)\n    at commandExecutor (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:335:9)\n    at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/async-lock/lib/index.js:137:12\n    at AsyncLock._promiseTry (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/async-lock/lib/index.js:261:31)\n    at exec (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/async-lock/lib/index.js:136:9)\n    at AsyncLock.acquire (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/async-lock/lib/index.js:152:3)\n    at XCUITestDriver.executeCommand (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:348:39)\n    at XCUITestDriver.executeCommand (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:731:24)\n    at AppiumDriver.executeCommand (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/lib/appium.js:563:36)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:85:5)\n    at asyncHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:297:21)"}}
Command duration or timeout: 4 milliseconds
Build info: version: '4.1.3', revision: '7b1ebf28ef'
System info: host: 'LULO-C02F22WBMD6M.local', ip: 'fe80:0:0:0:1060:b35e:6b46:1412%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '11.6.4', java.version: '11.0.12'
Driver info: io.appium.java_client.AppiumDriver
Command: [ec885fd8-a0ae-45ad-9614-d8d34c868cde, close {}]
Capabilities {appium:app: Users/jortegon/Library/Deve..., appium:automationName: XCUITest, appium:databaseEnabled: false, appium:deviceId: , appium:deviceName: iPhone 12 Pro Max, appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:name: Onboarding desde PEP dilige..., appium:networkConnectionEnabled: false, appium:noReset: true, appium:platformVersion: 14.5, appium:shouldTerminateApp: true, appium:takesScreenshot: true, appium:udid: 59D95976-33E4-40DE-9C68-666..., appium:webStorageEnabled: false, platformName: ios}
Session ID: ec885fd8-a0ae-45ad-9614-d8d34c868cde

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:217)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:169)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:622)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:268)
	at org.openqa.selenium.remote.RemoteWebDriver.close(RemoteWebDriver.java:452)
	at lulobank.automation.frontend.utils.drivers.LocalAppiumDriver.resetApp(LocalAppiumDriver.java:72)
```

**Comment by KazuCocoa** [comment]
Do you want to use `terminateApp`?

**Comment by vnuta9** [comment]
@KazuCocoa @jlipps 
Similar issue, is occurring for me. For our MobileWeb application automation, I am trying to open a new window and switch in to that using the recent Selenium 4.0 methods:

### Environment:

- Appium Server: **2.11.5**
- JDK **21.0.4**
- Appium-java client: **9.3**
- Selenium-java client: **4.25**
- Desktop MacOS Sequoia: **15.3**
- Mobile platform iOS 18.3 on iPhone: **11**

### Code To Reproduce:
```
// driver below would be either **AppiumDriver**, or one of it's subclasses like **AndroidDriver**, **IOSDriver** based on the platform
driver =  getDriver4MobileWeb(platform, browser, deviceName) ;
stack.add(driver.getWindowHandle());
//Opens a new window and switches to new window
        **driver.switchTo().newWindow**(WindowType.WINDOW);// ----> Error(given below is thrown) here<---
        stack.add(driver.getWindowHandle());
        System.out.println("window handles = "+driver.getWindowHandles()+",stack items="+stack.toString());
		//change the context to WEBVIEW (more so for iOS, as it is default for Android) 
    	changeDriverContextToWeb();
```
### Exception Stack:
```
UnsupportedCommand {"value":{"error":"unknown method","message":"Method has not yet been implemented","stacktrace":"NotYetImplementedError: Method has not yet been implemented\n    at XCUITestDriver.executeCommand (/Users/venkatanutalapati/.nvm/versions/node/v20.16.0/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.ts:102:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at XCUITestDriver.executeCommand (/Users/venkatanutalapati/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:1044:12)\n    at defaultBehavior (/Users/venkatanutalapati/.nvm/versions/node/v20.16.0/lib/node_modules/appium/lib/appium.js:1135:14)\n    at AppiumDriver.executeWrappedCommand (/Users/venkatanutalapati/.nvm/versions/node/v20.16.0/lib/node_modules/appium/lib/appium.js:1241:16)\n    at AppiumDriver.executeCommand (/Users/venkatanutalapati/.nvm/versions/node/v20.16.0/lib/node_modules/appium/lib/appium.js:1147:17)\n    at asyncHandler (/Users/venkatanutalapati/.nvm/versions/node/v20.16.0/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:387:19)"}}
Command duration or timeout: 17 milliseconds
Build info: version: '4.28.1', revision: '73f5ad48a2'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '15.3', java.version: '21.0.6'
Driver info: io.appium.java_client.ios.IOSDriver
Command: [80ba2ffa-621a-4699-9664-9b568a97062f, newWindow {type=window}]
Capabilities {appium:autoAcceptAlerts: true, appium:autoWebview: true, appium:automationName: XCUITest, appium:databaseEnabled: false, appium:deviceName: Venkata Nutalapati's iPhone, appium:includeSafariInWebviews: true, appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:networkConnectionEnabled: false, appium:platformVersion: 18.3, appium:takesScreenshot: true, appium:udid: 00008030-000159EA0E60402E, appium:webStorageEnabled: false, appium:webviewConnectTimeout: 50000, browserName: Safari, platformName: IOS}
Session ID: 80ba2ffa-621a-4699-9664-9b568a97062f[m
```
**Please help !**
