### ISSUE TITLE
module org.seleniumhq.selenium.remote_driver does not "opens org.openqa.selenium.remote" to module java.client

### ISSUE THREAD

**Issue by ilamp** [appium/java-client#1748]
## Description

I've been trying to connect to local appium server but haven't been able to so far.
`module org.seleniumhq.selenium.remote_driver does not "opens org.openqa.selenium.remote" to module java.client`

## Details

I've been trying to connect to local appium server but haven't been able to so far.
`module org.seleniumhq.selenium.remote_driver does not "opens org.openqa.selenium.remote" to module java.client`

## Exception Stacktraces

`Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '4.2.1', revision: 'ac4d0fdd4a'
System info: host: 'DESKTOP-V17PTVE', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '18.0.2.1'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [null, newSession {capabilities=[{appium:appActivity=*********, appium:appPackage=*********, appium:appWaitActivity=*********, appium:autoLaunch=false, appium:automationName=UIAutomator2, appium:noReset=true, platformName=ANDROID, appium:platformVersion=7, appium:udid=127.0.0.1:5645}], desiredCapabilities=Capabilities {appActivity: *****, appPackage: ******, appWaitActivity: ********, autoLaunch: false, automationName: UIAutomator2, noReset: true, platformName: ANDROID, platformVersion: 7, udid: 127.0.0.1:5645}}]
Capabilities {}
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '4.2.1', revision: 'ac4d0fdd4a'
System info: host: 'DESKTOP-V17PTVE', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '18.0.2.1'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [null, newSession {capabilities=[{appium:appActivity=*******, appium:appPackage=********, appium:appWaitActivity=*******, appium:autoLaunch=false, appium:automationName=UIAutomator2, appium:noReset=true, platformName=ANDROID, appium:platformVersion=7, appium:udid=127.0.0.1:5645}], desiredCapabilities=Capabilities {appActivity: ********, appPackage: ******, appWaitActivity: ******, autoLaunch: false, automationName: UIAutomator2, noReset: true, platformName: ANDROID, platformVersion: 7, udid: 127.0.0.1:5645}}]
Capabilities {}
	at org.seleniumhq.selenium.remote_driver/org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:569)
	at java.client@8.1.1/io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:224)
	at org.seleniumhq.selenium.remote_driver/org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:162)
	at java.client@8.1.1/io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:79)
	at java.client@8.1.1/io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:87)
	at java.client@8.1.1/io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:116)
	at com.cx.ibot/com.cx.ibot.TakeScreenshotController.createAppiumDriver(TakeScreenshotController.java:53)
	at com.cx.ibot/com.cx.ibot.TakeScreenshotController.onButtonClick(TakeScreenshotController.java:28)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:77)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at javafx.base@18.0.2/com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:275)
	at javafx.fxml@18.0.2/com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:84)
	at javafx.fxml@18.0.2/javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1854)
	at javafx.fxml@18.0.2/javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1724)
	at javafx.base@18.0.2/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base@18.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at javafx.base@18.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base@18.0.2/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@18.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@18.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@18.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@18.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18.0.2/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@18.0.2/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base@18.0.2/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@18.0.2/javafx.scene.Node.fireEvent(Node.java:8797)
	at javafx.controls@18.0.2/javafx.scene.control.Button.fire(Button.java:203)
	at javafx.controls@18.0.2/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:208)
	at javafx.controls@18.0.2/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at javafx.base@18.0.2/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at javafx.base@18.0.2/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base@18.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at javafx.base@18.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base@18.0.2/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@18.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@18.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@18.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@18.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18.0.2/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@18.0.2/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base@18.0.2/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@18.0.2/javafx.scene.Scene$MouseHandler.process(Scene.java:3881)
	at javafx.graphics@18.0.2/javafx.scene.Scene.processMouseEvent(Scene.java:1874)
	at javafx.graphics@18.0.2/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2607)
	at javafx.graphics@18.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at javafx.graphics@18.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics@18.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at javafx.graphics@18.0.2/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at javafx.graphics@18.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at javafx.graphics@18.0.2/com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at javafx.graphics@18.0.2/com.sun.glass.ui.View.notifyMouse(View.java:937)
	at javafx.graphics@18.0.2/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@18.0.2/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private org.openqa.selenium.remote.CommandCodec org.openqa.selenium.remote.HttpCommandExecutor.commandCodec accessible: module org.seleniumhq.selenium.remote_driver does not "opens org.openqa.selenium.remote" to module java.client
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:180)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:174)
	at java.client@8.1.1/io.appium.java_client.remote.AppiumCommandExecutor.getPrivateFieldValue(AppiumCommandExecutor.java:100)
	at java.client@8.1.1/io.appium.java_client.remote.AppiumCommandExecutor.getCommandCodec(AppiumCommandExecutor.java:126)
	at java.client@8.1.1/io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:142)
	at java.client@8.1.1/io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:180)
	at org.seleniumhq.selenium.remote_driver/org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:551)
	... 61 more`

## Link To Appium Logs

There isn't much in the appium server logs:

`Aug 25, 2022 8:31:45 PM org.openqa.selenium.W3CCapabilityKeysValidator validateCapability
WARNING: Support for Legacy Capabilities is deprecated; You are sending "appPackage" which is an invalid capability. Please update to W3C Syntax: https://www.selenium.dev/blog/2022/legacy-protocol-support/
Aug 25, 2022 8:31:45 PM org.openqa.selenium.W3CCapabilityKeysValidator validateCapability
WARNING: Support for Legacy Capabilities is deprecated; You are sending "appWaitActivity" which is an invalid capability. Please update to W3C Syntax: https://www.selenium.dev/blog/2022/legacy-protocol-support/
Aug 25, 2022 8:31:45 PM org.openqa.selenium.W3CCapabilityKeysValidator validateCapability
WARNING: Support for Legacy Capabilities is deprecated; You are sending "appActivity" which is an invalid capability. Please update to W3C Syntax: https://www.selenium.dev/blog/2022/legacy-protocol-support/
Aug 25, 2022 8:31:45 PM org.openqa.selenium.W3CCapabilityKeysValidator validateCapability
WARNING: Support for Legacy Capabilities is deprecated; You are sending "noReset" which is an invalid capability. Please update to W3C Syntax: https://www.selenium.dev/blog/2022/legacy-protocol-support/
Aug 25, 2022 8:31:45 PM org.openqa.selenium.W3CCapabilityKeysValidator validateCapability
WARNING: Support for Legacy Capabilities is deprecated; You are sending "automationName" which is an invalid capability. Please update to W3C Syntax: https://www.selenium.dev/blog/2022/legacy-protocol-support/
Aug 25, 2022 8:31:45 PM org.openqa.selenium.W3CCapabilityKeysValidator validateCapability
WARNING: Support for Legacy Capabilities is deprecated; You are sending "autoLaunch" which is an invalid capability. Please update to W3C Syntax: https://www.selenium.dev/blog/2022/legacy-protocol-support/
Aug 25, 2022 8:31:45 PM org.openqa.selenium.W3CCapabilityKeysValidator validateCapability
WARNING: Support for Legacy Capabilities is deprecated; You are sending "udid" which is an invalid capability. Please update to W3C Syntax: https://www.selenium.dev/blog/2022/legacy-protocol-support/`

**Comment by bipin-k** [comment]
@ilamp Can you please a code snippet to reproduce this issue? Also, can you please share appium, java and node version!

**Comment by ilamp** [comment]
@bipin-k Please try this: https://github.com/ilamp/Demo

**Comment by ilamp** [comment]
For anyone facing this issue you can add `--add-options` flag to your `javafx-maven-plugin` configuration.

`            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.8</version>
                <executions>
                    <execution>
                        
                        <id>default-cli</id>
                        <configuration>
                            <mainClass>com.cx.ibot/com.cx.ibot.MainApplication</mainClass>
                            <options>
                                <option>--add-opens</option>
                                <option>org.seleniumhq.selenium.remote_driver/org.openqa.selenium.remote=java.client</option>
                            </options>
                        </configuration>
                    </execution>
                </executions>
            </plugin>`

**Comment by ilamp** [comment]
For anyone facing this issue you can add `--add-options` flag to your `javafx-maven-plugin` configuration.

```
  <options>
      <option>--add-opens</option>
      <option>org.seleniumhq.selenium.remote_driver/org.openqa.selenium.remote=java.client</option>
  </options>
```

**Comment by bipin-k** [comment]
Can we please close this issue as this is resolved now? cc: @ilamp @SrinivasanTarget @mykola-mokhnach
