### ISSUE TITLE
Exception in thread "main" java.lang.ClassCastException: class org.openqa.selenium.remote.RemoteWebDriver cannot be cast to class io.appium.java_client.AppiumDriver (org.openqa.selenium.remote.RemoteWebDriver and io.appium.java_client.AppiumDriver are in unnamed module of loader 'app') 	at com.browserstack.app.JavaSample2.main(JavaSample2.java:44)

### ISSUE THREAD

**Issue by sharutkarsh** [appium/java-client#1859]
I want to do drag and drop operation on an android mobile browser.

Below are the dependencies I have in pom for selenium and appium 

<dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.141.59</version>
        </dependency>
      
        <dependency>
        <groupId>io.appium</groupId>
        <artifactId>java-client</artifactId>
        <version>7.4.1</version>
    </dependency>
    
    
    I'm using this piece of code to perform drag and drop.
    
     new AndroidTouchAction((PerformsTouchActions) driver).longPress(LongPressOptions.longPressOptions().withElement(ElementOption.element(source)))
        .waitAction(WaitOptions.waitOptions(Duration.ofSeconds(2)))
        .moveTo(ElementOption.element(target))
        .release()
        .perform();
        
        
Which is throwing this error :

 "Exception in thread "main" java.lang.ClassCastException: class org.openqa.selenium.remote.RemoteWebDriver cannot be cast to class io.appium.java_client.AppiumDriver (org.openqa.selenium.remote.RemoteWebDriver and io.appium.java_client.AppiumDriver are in unnamed module of loader 'app')
	at com.browserstack.app.JavaSample2.main(JavaSample2.java:44)"

**Comment by valfirst** [comment]
I recommend to bump the used dependencies
