### ISSUE TITLE
Java 8.3.0 is not compatible with selenium 4.8.2 

### ISSUE THREAD

**Issue by Idoserovitz** [appium/java-client#1872]
## Description

selenium java version [4.8.2](https://github.com/SeleniumHQ/selenium/blob/trunk/java/CHANGELOG) was released no long ago and appium java-client 8.3.0 cannot invoke appium server programmatically(manually it works well). I get `SurefireExecutionException: Exception in provider` error when executing the test and I can see in the logs that appium server wasn’t able to launch.

## Environment

* Java client build version or git revision if you use some snapshot: 8.3.0
* Appium server version or git revision if you use some snapshot: 2.0.0-beta.57
* Desktop OS/version used to run Appium if necessary: MacOS Ventura, m1 machine
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 16.16.0
* Mobile platform/version under test: android api 30, iOS 15.5
* Real device or emulator/simulator: emulator and simulator on both platforms

## Details

I use maven, testng and surefire-plugin setup. Maven automatically updates selenium's version.

## Exception Stacktraces
SurefireExecutionException: Exception in provider

**Comment by Idoserovitz** [comment]
Solved it by going to `$HOME/.m2/repository/io/appium/java-client/8.3.0` and adjusting the file: `java-client-8.3.0.pom`.
Changing all selenium related dependencies' version tag from: `<version>[4.7.0, 5.0)</version>` to `<version>[4.7.0, 4.8.2)</version>` to eliminate incompatible 4.8.2 selenium version.

Still would like to have a time estimation for a compatible version, Thanks.

**Comment by mykola-mokhnach** [comment]
Please provide the full stacktrace

**Comment by Idoserovitz** [comment]
@mykola-mokhnach 
https://gist.github.com/Idoserovitz/58c2b2e41ede8c950d7ffb4bc3eeaffd

Note that "CustomTestListenerAdapter" is a class I created which implements test failure post action and triggered by testng. It should not cause such an issue.
And again, appium server never started.

**Comment by mykola-mokhnach** [comment]
I don't observe any mentions of appium client in the stacktrace. Are you sure your issue is somehow related to it?

**Comment by amnajamshaid** [comment]
> I've just merged #1878
> 
> It will be published with the next java client patch

How long would it take? Would it be deployed till tomorrow?

**Comment by amnajamshaid** [comment]
> Solved it by going to `$HOME/.m2/repository/io/appium/java-client/8.3.0` and adjusting the file: `java-client-8.3.0.pom`. Changing all selenium related dependencies' version tag from: `<version>[4.7.0, 5.0)</version>` to `<version>[4.7.0, 4.8.2)</version>` to eliminate incompatible 4.8.2 selenium version.
> 
> Still would like to have a time estimation for a compatible version, Thanks.

Thank you for your fix. I faced the same issue.

**Comment by SrinivasanTarget** [comment]
In SeleniumConf now, will do it tonight.

**Comment by ZuhayrMerchant110** [comment]
you don't have to do anything in the java-client-8.3.0.pom instead just change the version of your selenium maven libraries in your project pom file to 4.8.2.

**Comment by amnajamshaid** [comment]
@SrinivasanTarget  so we will use java client version 8.3.0 now and the issue will be resolved ?

**Comment by ZuhayrMerchant110** [comment]
yes appium version 8.3.0 and selenium java 4.8.2

**Comment by Higgens75** [comment]
i have updated now appium version 8.3.0 and selenium java 4.8.2 and using latest appium 2 beta,
but the AppiumDriverLocalService throws n ow a nullpointer Exception

java.lang.NullPointerExceptionio.appium.java_client.service.local.AppiumDriverLocalService.destroyProcess(AppiumDriverLocalService.java:220)
Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 

Anyone know if there has something changed in the AppiumServerBuilder i have to adjust now ?

**Comment by ZuhayrMerchant110** [comment]
@Higgens75 can you run appium -v and send the screenshot here?

**Comment by ZuhayrMerchant110** [comment]
and also your pom file as well

**Comment by Idoserovitz** [comment]
> i have updated now appium version 8.3.0 and selenium java 4.8.2 and using latest appium 2 beta, but the AppiumDriverLocalService throws n ow a nullpointer Exception
> 
> java.lang.NullPointerExceptionio.appium.java_client.service.local.AppiumDriverLocalService.destroyProcess(AppiumDriverLocalService.java:220) Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
> 
> Anyone know if there has something changed in the AppiumServerBuilder i have to adjust now ?

you need selenium version **below** 4.8.2
I think maven will download selenium's latest jar file regardless the version you specify in **your** pom file. This is because the java-client depends on selenium and java-client's pom file will still "tell" maven to download latest selenium's jar file.

your options(if changing the version won't solve it):
1. https://github.com/appium/java-client/issues/1872#issuecomment-1484017595
2. change to master: https://github.com/appium/java-client/issues/1872#issuecomment-1487244500

**Comment by mykola-mokhnach** [comment]
@nir-tal-talkspace Please provide the full stacktrace

**Comment by nir-tal-talkspace** [comment]
Step failed
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInCustomProvider]: SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'NirTal2.lan', ip: '192.168.1.141'
Build info: version: '4.8.3', revision: 'e5e76298c3'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '13.2.1', java.version: '17'
Driver info: IOSDriver
Command: [null, newSession {capabilities=[{appium:useNewWDA=true, appium:newCommandTimeout=300, appium:autoAcceptAlerts=true, appium:includeSafariInWebviews=true, appium:bundleId=com.talktala.talktala, appium:derivedDataPath=/Users/nirtal/Library/Developer/Xcode/DerivedData/WebDriverAgent-fwbdxunyvfwzddgatcwxyatuptva/Build/Products, appium:automationName=XCuiTest, appium:platformVersion=14.5, appium:udid=CF1790E7-7617-41D5-A4A5-E4CDCD3E4432, appium:wdaLocalPort=8100, appium:deviceName=iPhone 11 Simulator, platformName=IOS, appium:fullContextList=true, appium:app=/Users/nirtal/Downloads/Client Development.app, appium:webviewConnectTimeout=30000}], desiredCapabilities=Capabilities {appium:app: /Users/nirtal/Downloads/Cli..., appium:autoAcceptAlerts: true, appium:automationName: XCuiTest, appium:bundleId: com.talktala.talktala, appium:derivedDataPath: /Users/nirtal/Library/Devel..., appium:deviceName: iPhone 11 Simulator, appium:fullContextList: true, appium:includeSafariInWebviews: true, appium:newCommandTimeout: 300, appium:platformVersion: 14.5, appium:udid: CF1790E7-7617-41D5-A4A5-E4C..., appium:useNewWDA: true, appium:wdaLocalPort: 8100, appium:webviewConnectTimeout: 30000, platformName: IOS}}]
Capabilities {appium:app: /Users/nirtal/Downloads/Cli..., appium:autoAcceptAlerts: true, appium:automationName: XCuiTest, appium:bundleId: com.talktala.talktala, appium:derivedDataPath: /Users/nirtal/Library/Devel..., appium:deviceName: iPhone 11 Simulator, appium:fullContextList: true, appium:includeSafariInWebviews: true, appium:newCommandTimeout: 300, appium:platformVersion: 14.5, appium:udid: CF1790E7-7617-41D5-A4A5-E4C..., appium:useNewWDA: true, appium:wdaLocalPort: 8100, appium:webviewConnectTimeout: 30000, platformName: IOS}
  while locating IosDriverProvider
  at IosModule.configure(IosModule.java:31)
  at Hooks.iosDriver(Hooks.java:38)
      \_ for field iosDriver
  while locating Hooks

Learn more:
  https://github.com/google/guice/wiki/ERROR_IN_CUSTOM_PROVIDER

1 error

======================
Full classname legend:
======================
Hooks:                      "glue.steps.Hooks"
IOSDriver:                  "io.appium.java_client.ios.IOSDriver"
IosDriverProvider:          "glue.di.providers.IosDriverProvider"
IosModule:                  "glue.di.modules.IosModule"
SessionNotCreatedException: "org.openqa.selenium.SessionNotCreatedException"
========================
End of classname legend:
========================

	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1104)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1139)
	at io.cucumber.guice.GuiceFactory.getInstance(GuiceFactory.java:83)
	at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
	at io.cucumber.java.JavaHookDefinition.execute(JavaHookDefinition.java:64)
	at io.cucumber.core.runner.CoreHookDefinition.execute(CoreHookDefinition.java:46)
	at io.cucumber.core.runner.HookDefinitionMatch.runStep(HookDefinitionMatch.java:21)
	at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:84)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:56)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:78)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
	at io.cucumber.core.runtime.Runtime.lambda$executePickle$6(Runtime.java:132)
	at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:130)
	at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
	at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:130)
	at io.cucumber.core.runtime.Runtime.lambda$executePickle$7(Runtime.java:132)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.cucumber.core.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:253)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
	at io.cucumber.core.runtime.Runtime.lambda$runFeatures$3(Runtime.java:114)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.SliceOps$1$1.accept(SliceOps.java:200)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.cucumber.core.runtime.Runtime.runFeatures(Runtime.java:115)
	at io.cucumber.core.runtime.Runtime.lambda$run$0(Runtime.java:84)
	at io.cucumber.core.runtime.Runtime.execute(Runtime.java:99)
	at io.cucumber.core.runtime.Runtime.run(Runtime.java:82)
	at io.cucumber.core.cli.Main.run(Main.java:87)
	at io.cucumber.core.cli.Main.main(Main.java:30)
Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'NirTal2.lan', ip: '192.168.1.141'
Build info: version: '4.8.3', revision: 'e5e76298c3'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '13.2.1', java.version: '17'
Driver info: io.appium.java_client.ios.IOSDriver
Command: [null, newSession {capabilities=[{appium:useNewWDA=true, appium:newCommandTimeout=300, appium:autoAcceptAlerts=true, appium:includeSafariInWebviews=true, appium:bundleId=com.talktala.talktala, appium:derivedDataPath=/Users/nirtal/Library/Developer/Xcode/DerivedData/WebDriverAgent-fwbdxunyvfwzddgatcwxyatuptva/Build/Products, appium:automationName=XCuiTest, appium:platformVersion=14.5, appium:udid=CF1790E7-7617-41D5-A4A5-E4CDCD3E4432, appium:wdaLocalPort=8100, appium:deviceName=iPhone 11 Simulator, platformName=IOS, appium:fullContextList=true, appium:app=/Users/nirtal/Downloads/Client Development.app, appium:webviewConnectTimeout=30000}], desiredCapabilities=Capabilities {appium:app: /Users/nirtal/Downloads/Cli..., appium:autoAcceptAlerts: true, appium:automationName: XCuiTest, appium:bundleId: com.talktala.talktala, appium:derivedDataPath: /Users/nirtal/Library/Devel..., appium:deviceName: iPhone 11 Simulator, appium:fullContextList: true, appium:includeSafariInWebviews: true, appium:newCommandTimeout: 300, appium:platformVersion: 14.5, appium:udid: CF1790E7-7617-41D5-A4A5-E4C..., appium:useNewWDA: true, appium:wdaLocalPort: 8100, appium:webviewConnectTimeout: 30000, platformName: IOS}}]
Capabilities {appium:app: /Users/nirtal/Downloads/Cli..., appium:autoAcceptAlerts: true, appium:automationName: XCuiTest, appium:bundleId: com.talktala.talktala, appium:derivedDataPath: /Users/nirtal/Library/Devel..., appium:deviceName: iPhone 11 Simulator, appium:fullContextList: true, appium:includeSafariInWebviews: true, appium:newCommandTimeout: 300, appium:platformVersion: 14.5, appium:udid: CF1790E7-7617-41D5-A4A5-E4C..., appium:useNewWDA: true, appium:wdaLocalPort: 8100, appium:webviewConnectTimeout: 30000, platformName: IOS}
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:561)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:269)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:107)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:132)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:243)
	at glue.di.providers.IosDriverProvider.get(IosDriverProvider.java:79)
	at glue.di.providers.IosDriverProvider.get(IosDriverProvider.java:28)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:67)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
	at com.netflix.governator.LifecycleListenerModule$LifecycleListenerProvisionListener.onProvision(LifecycleListenerModule.java:51)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
	at com.netflix.governator.guice.InternalLifecycleModule.onProvision(InternalLifecycleModule.java:65)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:62)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:59)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at io.cucumber.guice.SequentialScenarioScope.lambda$scope$0(SequentialScenarioScope.java:40)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:50)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:124)
	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:33)
	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
	at com.netflix.governator.LifecycleListenerModule$LifecycleListenerProvisionListener.onProvision(LifecycleListenerModule.java:51)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
	at com.netflix.governator.guice.InternalLifecycleModule.onProvision(InternalLifecycleModule.java:65)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1101)
	... 37 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.io.File.getAbsolutePath()" because "this.nodeJSExec" is null
	at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:177)
	at io.appium.java_client.remote.AppiumCommandExecutor.lambda$execute$2(AppiumCommandExecutor.java:242)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:240)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	... 73 more

**Comment by mykola-mokhnach** [comment]
> Caused by: java.lang.NullPointerException: Cannot invoke "java.io.File.getAbsolutePath()" because "this.nodeJSExec" is null

`nodeJSExec` property is marked as final, so it could only be null if null is passed to the contractor. How do you initialize the AppiumDriverLocalService class?

**Comment by nir-tal-talkspace** [comment]
I am not using an appium local service I am starting the service manually via "appium" command in the cli before to avoid using the service. 

this is the init code of the driver:
                    var xcuiTestOptions = new XCUITestOptions()
                            .setAutomationName(IOS_XCUI_TEST)
                            .setPlatformName(IOS)
                            .setFullContextList(true)
                            .setAutoAcceptAlerts(true)
                .setIncludeSafariInWebviews(true)
                .setWebviewConnectTimeout(Duration.ofSeconds(30))
                .setNewCommandTimeout(Duration.ofMinutes(5))
                .setBundleId(Constants.IOS_CLIENT_BUNDLE_ID);
            xcuiTestOptions.setDeviceName("iPhone 11 Simulator")
                    .setPlatformVersion("14.5")
                    // set to true to while testing webviews on local - this will remove previous stored webviews and will start fresh
                    .setUseNewWDA(true)
                    .setWdaLocalPort(8100)
                    .setDerivedDataPath("/Build/Products")
                    .setUdid("CF1790E7-7617-41D5-A4A5-E4CDCD3E4432")
                    .setApp("/Users/test.app");
            return new IOSDriver(xcuiTestOptions);

**Comment by nir-tal-talkspace** [comment]
same error when using:
`new IOSDriver(new AppiumServiceBuilder().usingAnyFreePort().build(), xcuiTestOptions);`

**Comment by mykola-mokhnach** [comment]
It turns out this failure is caused by https://github.com/SeleniumHQ/selenium/commit/1c70137592eb472a7089a920a9d0ca5deb078bbe#diff-6a2bf51c104e6ba92d3820843d8da94e8557501e8aa10e1a4734016c0f4a0d7cL475

The protected abstract method `findDefaultExecutable` has been unexpectedly removed from the DriverService class, which we inherit thus causing the above NPE. 

@diegomolina @titusfortner Shall we adapt our code to this change or should it be reverted on the Selenium side?

**Comment by titusfortner** [comment]
We moved driver finding responsibilities out of service classes to better support selenium manager.

The new Driver Finder class is now responsible for locating the correct driver and updating the service class if necessary.

**Comment by mykola-mokhnach** [comment]
> We moved driver finding responsibilities out of service classes to better support selenium manager.
> 
> The new Driver Finder class is now responsible for locating the correct driver and updating the service class if necessary.

I totally understand the point of the change. Just wanted to acknowledge this change broke the appium client.

**Comment by dipakkumar1225** [comment]
Another workaround is to exclude selenium dependency in pom.xml and the add selenium version. In case if not working then delete the  appium java-client 8.3.0 version from local repository %userprofile%\.m2\repository\io\appium\java-client

```
 <dependencies>
        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>8.3.0</version>
            <exclusions>

                <exclusion>
                    <groupId>org.seleniumhq.selenium</groupId>
                    <artifactId>selenium-remote-driver</artifactId>
                </exclusion>

                <exclusion>
                    <groupId>org.seleniumhq.selenium</groupId>
                    <artifactId>selenium-support</artifactId>
                </exclusion>

                <exclusion>
                    <groupId>org.seleniumhq.selenium</groupId>
                    <artifactId>selenium-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.8.1</version>
        </dependency>

    </dependencies>
```

**Comment by mykola-mokhnach** [comment]
> Do we need to help adjust the appium code to work with the new driver finder?

thanks, I have already [hacked](https://github.com/appium/java-client/pull/1880) it

**Comment by anu199012** [comment]
Still, I am getting the same error.

![image](https://user-images.githubusercontent.com/130862237/232246006-c018e0f5-e77a-46ef-b29f-73350c943907.png)

<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>fromscrach</groupId>
  <artifactId>mobileApp</artifactId>
  <version>0.0.1-SNAPSHOT</version>

  <name>mobileApp</name>
  
  <url>http://www.example.com</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.7</maven.compiler.source>
    <maven.compiler.target>1.7</maven.compiler.target>
  </properties>

  <dependencies>
	    
    <dependency>
    <groupId>io.appium</groupId>
    <artifactId>java-client</artifactId>
    <version>8.3.0</version>
</dependency>
<dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>7.7.1</version>
    <scope>test</scope>
</dependency> 

<dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.8.1</version>
        </dependency>

  </dependencies>

  <build>
    <pluginManagement>
      <plugins>
        
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.1.0</version>
        </plugin>
        
        <plugin>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>2.22.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-install-plugin</artifactId>
          <version>2.5.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>2.8.2</version>
        </plugin>
        
        <plugin>
          <artifactId>maven-site-plugin</artifactId>
          <version>3.7.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-project-info-reports-plugin</artifactId>
          <version>3.0.0</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>

**Comment by nir-tal-talkspace** [comment]
@SrinivasanTarget  can you please provide a patch version?
thanks!

**Comment by debasisj** [comment]
> Still, I am getting the same error.
> 
> ![image](https://user-images.githubusercontent.com/130862237/232246006-c018e0f5-e77a-46ef-b29f-73350c943907.png)
> 
> UTF-8 1.7 1.7
> ```
> <dependencies>
> 
> 	<dependency>
> 		<groupId>io.appium</groupId>
> 		<artifactId>java-client</artifactId>
> 		<version>8.3.0</version>
> 	</dependency>
> 	<dependency>
> 		<groupId>org.testng</groupId>
> 		<artifactId>testng</artifactId>
> 		<version>7.7.1</version>
> 		<scope>test</scope>
> 	</dependency>
> 
> 	<dependency>
> 		<groupId>org.seleniumhq.selenium</groupId>
> 		<artifactId>selenium-java</artifactId>
> 		<version>4.8.1</version>
> 	</dependency>
> 
> </dependencies>
> ```

have you  done  a clean build to update  packages?

**Comment by debasisj** [comment]
hi guys - any update on this?  Selenium has released 4.9.0

**Comment by nethira** [comment]
> Still, I am getting the same error.
> 
> ![image](https://user-images.githubusercontent.com/130862237/232246006-c018e0f5-e77a-46ef-b29f-73350c943907.png)
> 
> UTF-8 1.7 1.7
> ```
> <dependencies>
> 
> 	<dependency>
> 		<groupId>io.appium</groupId>
> 		<artifactId>java-client</artifactId>
> 		<version>8.3.0</version>
> 	</dependency>
> 	<dependency>
> 		<groupId>org.testng</groupId>
> 		<artifactId>testng</artifactId>
> 		<version>7.7.1</version>
> 		<scope>test</scope>
> 	</dependency>
> 
> 	<dependency>
> 		<groupId>org.seleniumhq.selenium</groupId>
> 		<artifactId>selenium-java</artifactId>
> 		<version>4.8.1</version>
> 	</dependency>
> 
> </dependencies>
> ```

try using this code in your pom.xml .This worked for me.
``` <dependencies>
<dependency>
		<groupId>org.testng</groupId>
		<artifactId>testng</artifactId>
		<version>7.7.1</version>
		<scope>test</scope>
	</dependency>
        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>8.3.0</version>
            <exclusions>

                <exclusion>
                    <groupId>org.seleniumhq.selenium</groupId>
                    <artifactId>selenium-remote-driver</artifactId>
                </exclusion>

                <exclusion>
                    <groupId>org.seleniumhq.selenium</groupId>
                    <artifactId>selenium-support</artifactId>
                </exclusion>

                <exclusion>
                    <groupId>org.seleniumhq.selenium</groupId>
                    <artifactId>selenium-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.8.1</version>
        </dependency>

    </dependencies>
```

**Comment by Prashant9835** [comment]
Till now , maximum selenium 4.8.2 is compatible with java-client 8.3.0
