### ISSUE TITLE
Unable to start service using AppiumDriverLocalService.buildService(builder)

### ISSUE THREAD

**Issue by manivannan-r** [appium/java-client#1924]
## Description

Unable to start appium server programmatically, using AppiumDriverLocalService.

## Environment

APPIUM JAVA CLIENT : 8.5.0
APPIUM SERVER : 2.0.0-beta.71
NODE : v20.2.0
NPM : v9.6.6
OS : macOS Monterey (V 2.6.5 (21G531))
Chip : Apple M1 Pro

## Code To Reproduce Issue [ Good To Have ]

           
		```
AppiumDriverLocalService service;
		AppiumServiceBuilder builder = new AppiumServiceBuilder();
		builder.withIPAddress(CommonUtil.getLocalIPAddress());
		builder.usingAnyFreePort();
//		builder.usingDriverExecutable(new File("/usr/local/bin/node"));
		builder.withAppiumJS(new File("/usr/local/lib/node_modules/appium/build/lib/main.js"));
//		builder.withArgument(GeneralServerFlag.SESSION_OVERRIDE);
//		builder.withArgument(() -> GeneralServerFlag.BASEPATH.getArgument(), "/wd/hub");
                service = AppiumDriverLocalService.buildService(builder);
                service.start();
```

## Exception Stacktraces

Please create a [gist](https://gist.github.com) with the pasted stacktrace of the exception thrown by java.

## Link To Appium Logs

/usr/local/lib/node_modules/appium/node_modules/sharp/lib/sharp.js:37
  throw new Error(help.join('\n'));
        ^
Error: 
Something went wrong installing the "sharp" module

dlopen(/usr/local/lib/node_modules/appium/node_modules/sharp/build/Release/sharp-darwin-x64.node, 0x0001): symbol not found in flat namespace (__ZTVN4vips7VOptionE)

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current darwin-x64 runtime: "npm install --platform=darwin --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/sharp/lib/sharp.js:37:9)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/sharp/lib/constructor.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/sharp/lib/index.js:6:15)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
Exception in thread "main" io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: /usr/local/bin/node Arguments: [/usr/local/lib/node_modules/appium/build/lib/main.js, --port, 4723, --address, 0.0.0.0] 
Process output: 
/usr/local/lib/node_modules/appium/node_modules/sharp/lib/sharp.js:37
  throw new Error(help.join('\n'));
        ^
Error: 

```
Something went wrong installing the "sharp" module

dlopen(/usr/local/lib/node_modules/appium/node_modules/sharp/build/Release/sharp-darwin-x64.node, 0x0001): symbol not found in flat namespace (__ZTVN4vips7VOptionE)

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current darwin-x64 runtime: "npm install --platform=darwin --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/sharp/lib/sharp.js:37:9)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/sharp/lib/constructor.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/sharp/lib/index.js:6:15)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)


	at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:182)
	at com.zoho.appiumtestkit.tests.DemoTest.main(DemoTest.java:38)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20006 ms
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:89)
	at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:147)
	at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:169)
	... 1 more
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:87)
	... 3 more
```

**Comment by mseremin** [comment]
Did you solve this problem?

**Comment by monushhmohan** [comment]
Hi Mani, 

Have you got a solution to issue yet?

I have facing exact issue whilst trying to automate handling appium server to start and stop. 

Thanks

**Comment by ashwithpoojary98** [comment]
@manivannan-r uninstall Appium and install the latest version of Appium
