### ISSUE TITLE
org.openqa.selenium.InvalidArgumentException: Exception while reading JSON

### ISSUE THREAD

**Issue by vnuta9** [appium/java-client#1933]
## Description

I am using appium ver**2.0.0-beta66**,
 java-client ver**8.5**, 
node ver **18.15.0**; 
selenium-java ver **4.9.1**; 
selenium-server ver**3.141.59**;
 JDK 1.15-02 on a Mac Ventura ver13.3.1a testing a Flutter app.

Enabled appium plug-ins **gestures** and **element-wait**
I was trying to do a swipe action using **PointerInput**, **Sequence** classes
Exactly at a place I am calling a swipe action, and at the end calling **driver.perform(ImmutableList.of (swipe))**, I am getting the error

## Environment

* Java client build version or git revision if you use some snapshot:
* Appium server version or git revision if you use some snapshot:
* Desktop OS/version used to run Appium if necessary:
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test:
* Real device or emulator/simulator:

## Details

```
**org.openqa.selenium.InvalidArgumentException: Exception while reading JSON**
Build info: version: '4.9.1', revision: 'eb2032df7f'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '15.0.2'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [19290b5f-197c-4096-b9db-0debe306b4a9, actions {actions=[org.openqa.selenium.interactions.Sequence@b9fa10b]}]
Capabilities {appium:appActivity: com.zimperium.zips.MainActi..., appium:appPackage: com.zimperium.zips, appium:autoGrantPermissions: true, appium:automationName: UIAutomator2, appium:chromedriverPort: 11000, appium:databaseEnabled: false, appium:desired: {appActivity: com.zimperium.zips.MainActi..., appPackage: com.zimperium.zips, autoGrantPermissions: true, automationName: UIAutomator2, chromedriverPort: 11000, deviceName: Pixel 4, noReset: true, platformName: ANDROID, systemPort: 10000, udid: 9B081FFAZ00D09}, appium:deviceApiLevel: 33, appium:deviceManufacturer: Google, appium:deviceModel: Pixel 4, appium:deviceName: 9B081FFAZ00D09, appium:deviceScreenDensity: 440, appium:deviceScreenSize: 1080x2280, appium:deviceUDID: 9B081FFAZ00D09, appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:networkConnectionEnabled: true, appium:noReset: true, appium:pixelRatio: 2.75, appium:platformVersion: 13, appium:statBarHeight: 83, appium:systemPort: 10000, appium:takesScreenshot: true, appium:udid: 9B081FFAZ00D09, appium:viewportRect: {height: 2131, left: 0, top: 83, width: 1080}, appium:warnings: {}, appium:webStorageEnabled: false, platformName: ANDROID}
Session ID: 19290b5f-197c-4096-b9db-0debe306b4a9
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:193)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.RemoteWebDriver.perform(RemoteWebDriver.java:611)
	at pages.BasePage.swipeJlipp(BasePage.java:905)
```

## Code To Reproduce Issue [ Good To Have ]

The line 905 in BasePage.java is from this method:
```
    protected void **swipeJlipp**(Point start, Point end, Duration duration) {
        boolean isAndroid = params.getPlatformName().equalsIgnoreCase("Android");

        PointerInput input = new PointerInput(PointerInput.Kind.TOUCH, "finger");
        Sequence swipe = new Sequence(input, 1);
        swipe.addAction(input.createPointerMove(Duration.ZERO, PointerInput.Origin.viewport(), start.x, start.y));
        swipe.addAction(input.createPointerDown(PointerInput.MouseButton.LEFT.asArg()));
        if (isAndroid) {
            duration = duration.dividedBy(ANDROID_SCROLL_DIVISOR);
        } else {
            swipe.addAction(new Pause(input, duration));
            duration = Duration.ZERO;
        }
        swipe.addAction(input.createPointerMove(duration, PointerInput.Origin.viewport(), end.x, end.y));
        swipe.addAction(input.createPointerUp(PointerInput.MouseButton.LEFT.asArg()));
        swipe.addAction(input.createPointerUp(PointerInput.MouseButton.LEFT.asArg()));
        driver.perform(ImmutableList.of(swipe));// <<<<<<<<==== error thrown at this line.
    }
```

Interestingly another one step preceding this, another swipe method ran perfectly fine

```
    public void swipeOrScrollUpQuarterBySequence() {
        Dimension size = getWindowSize();//driver.manage().window().getSize();
        int startX = size.getWidth() / 2;
        int startY = size.getHeight() / 2;
        int endX = startX;
        int endY = (int) (size.getHeight() * 0.25);
        PointerInput finger = new PointerInput(PointerInput.Kind.TOUCH, "finger");
        Sequence sequence = new Sequence(finger, 1)
                .addAction(finger.createPointerMove(Duration.ZERO, PointerInput.Origin.viewport(), startX, startY))
                .addAction(finger.createPointerDown(PointerInput.MouseButton.LEFT.asArg()))
                .addAction(new Pause(finger, Duration.ofMillis(200)))
                .addAction(finger.createPointerMove(Duration.ofMillis(500), PointerInput.Origin.viewport(), endX, endY))
                .addAction(finger.createPointerUp(PointerInput.MouseButton.LEFT.asArg()));

        driver.perform(Collections.singletonList(sequence));
    }
```
What is the root cause of this problem ? Incompatibilities of components used ? Or the particular mobile page, on which the scroll action is carried out ?

Thanks for your help
## Exception Stacktraces

Please create a [gist](https://gist.github.com) with the pasted stacktrace of the exception thrown by java.

## Link To Appium Logs

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by mykola-mokhnach** [comment]
Please also provide the full server log

**Comment by vnuta9** [comment]
@mykola-mokhnach 
I beg your pardon.
Please let me know how do I collect the server logs ?
I will also, google for any information about the same..

**Comment by vnuta9** [comment]
@mykola-mokhnach 
An interesting tit bit of information to add now. I ran the same code with an iPhone, it is working perfectly fine. No problem what so ever. I felt it is relevant for the problem.

**Comment by vnuta9** [comment]
@mykola-mokhnach 

My bad.
Apart from reason for the  error, the page swipe is working now. The basic reason is that the page is long list of data and it took 30 sec to fully load the whole page. When I incorporated the wait for that period before calling the swipe(), the swipe worked fine, and no error thrown.

We can close this issue, except for the reason for throwing the error.
Sorry for the inconvenience.
