### ISSUE TITLE
[Java-Client Ver 9.3.0] Camera moking 

### ISSUE THREAD

**Issue by thuonglai** [appium/java-client#2210]
## Description

Hi @sudharsan-selvaraj  When i using injectMockImage function has error as the following log:
```
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
Build info: version: '4.19.0', revision: '5f9cec8963'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '14.4', java.version: '18.0.1.1'
Driver info: io.appium.java_client.flutter.android.FlutterAndroidDriver
Capabilities {appium:address: 0.0.0.0, appium:allowCors: false, appium:allowInsecure: [], appium:app: /Users/axlehire/Documents/a..., appium:autoGrantPermissions: true, appium:automationName: FlutterIntegration, appium:basePath: /wd/hub, appium:callbackPort: 4723, appium:debugLogSpacing: false, appium:denyInsecure: [], appium:driver: {xcuitest: {wdaLocalPort: 8100}}, appium:driversImportChunkSize: 3, appium:eventTimings: true, appium:extraArgs: [], appium:fastReset: true, appium:flutterElementWaitTimeout: 10000, appium:flutterEnableMockCamera: true, appium:flutterServerLaunchTimeout: 120000, appium:flutterSystemPort: 9999, appium:keepAliveTimeout: 600, appium:localTimezone: false, appium:logFormat: text, appium:logNoColors: false, appium:logTimestamp: false, appium:loglevel: debug, appium:longStacktrace: false, appium:noPermsCheck: false, appium:pluginsImportChunkSize: 7, appium:port: 4723, appium:relaxedSecurityEnabled: true, appium:sessionOverride: false, appium:skipUninstall: true, appium:strictCaps: false, appium:subcommand: server, appium:tmpDir: /var/folders/rb/8xmsqrs175g..., appium:useDrivers: [], appium:usePlugins: [], platformName: ANDROID}
Session ID: 3c0b24fb-6d62-4000-84bb-95cab61836f3
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
	at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:237)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:463)
	at io.appium.java_client.flutter.CanExecuteFlutterScripts.executeFlutterCommand(CanExecuteFlutterScripts.java:30)
	at io.appium.java_client.flutter.SupportsFlutterCameraMocking.injectMockImage(SupportsFlutterCameraMocking.java:34)
	at io.appium.java_client.flutter.SupportsFlutterCameraMocking.injectMockImage(SupportsFlutterCameraMocking.java:24)
	at io.appium.java_client.android.CommandTest.testCameraMocking(CommandTest.java:134)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

## Environment

* Java client build version or git revision if you use some snapshot: 9.3.0
* Appium server version or git revision if you use some snapshot: 2.11.2
* Desktop OS/version used to run Appium if necessary: MacOS 14.4 (23E214)
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: v18.2.0
* Mobile platform/version under test: Android 14.0
* Real device or emulator/simulator: Emulator 

## Code To Reproduce Issue [ Good To Have ]

```
String usernameLoginKey = "__login_screen.form.text.username";
        String passwordLoginKey = "__login_screen.form.text.password";
        String buttonLoginKey = "__login_screen.form.button.signin";
        WebElement usernameField = driver.findElement(AppiumBy.flutterKey(usernameLoginKey));
        WebElement passwordField = driver.findElement(AppiumBy.flutterKey(passwordLoginKey));
        WebElement loginBtn = driver.findElement(AppiumBy.flutterKey(buttonLoginKey));
        usernameField.sendKeys("admin");
        passwordField.sendKeys("admin");
        loginBtn.click();

        final String successQr = driver.injectMockImage(
                TestUtils.resourcePathToAbsolutePath("success_qr.png").toFile());
        driver.injectMockImage(
                TestUtils.resourcePathToAbsolutePath("second_qr.png").toFile());

        driver.findElement(AppiumBy.flutterKey("scan_icon")).click();
```

## Link To Appium Logs

[gist](https://gist.github.com/thuonglai/75cf57aa2485b3954773b6d684c2dcb9)

**Comment by saikrishna321** [comment]
@thuonglai Closing this issue as not issue with java-client. Please raise this issue under https://github.com/AppiumTestDistribution/appium-flutter-integration-driver
