### ISSUE TITLE
Issue with WebDriverWait while using Selenium Driver and Appium Driver in the same test

### ISSUE THREAD

**Issue by Simon-Kaz** [appium/java-client#229]
I have a project where i need to automate an app and (separately) navigate to a website to trigger events for said app. 

I have created a simple junit project where I create 2 driver instances - AppiumDriver (iOSDriver) and WebDriver (FirefoxDriver or ChromeDriver).

I have also created 2 WebDriverWaits, appiumWait and webDriverWait to handle explicit waiting for both drivers.

Following is a sample test suite setup:

```java

public class SampleTest {

    @iOSFindBy(accessibility = "book_button")
    private WebElement bookButton;

    @iOSFindBy(accessibility = "TODO")
    private WebElement alert;

    private AppiumDriver appiumDriver;
    private WebDriverWait appiumWait;
    private WebDriverWait webDriverWait;
    private AppiumFieldDecorator appiumFieldDecorator;
    private WebDriver webDriver;

    private static int DEFAULT_IMPLICIT_WAIT = 10;

    @Before
    public void setUp() throws Exception {

        File classpathRoot = new File(System.getProperty("user.dir"));
        File appDir = new File(classpathRoot, "src/app/");
        DesiredCapabilities capabilities = new DesiredCapabilities();

        File app = new File(appDir, "app.app");
        capabilities.setCapability("app", app.getAbsolutePath());
        capabilities.setCapability("platformName", "iOS");
        capabilities.setCapability("platformVersion", "8.3");
        capabilities.setCapability("deviceName", "iPhone 6");
        capabilities.setCapability("udid","udid");
        capabilities.setCapability("bundleId","bundleId");
        capabilities.setCapability("deviceReadyTimeout","45");
        capabilities.setCapability("newCommandTimeout","180");
        capabilities.setCapability("sendKeyStrategy","setValue");

        appiumDriver = new IOSDriver(new URL("http://0.0.0.0:4730/wd/hub"), capabilities);

        appiumWait = new WebDriverWait(appiumDriver, 120);
        appiumDriver.manage().timeouts().implicitlyWait(DEFAULT_IMPLICIT_WAIT, TimeUnit.SECONDS);
        appiumFieldDecorator = new AppiumFieldDecorator(appiumDriver, DEFAULT_IMPLICIT_WAIT, TimeUnit.SECONDS);
        PageFactory.initElements(appiumFieldDecorator, this);

        webDriver = new FirefoxDriver();
        webDriverWait = new WebDriverWait(webDriver, 20);

    }

    @After
    public void tearDown() throws Exception {
        appiumDriver.quit();
    }


    @Test
    public void notificationIsDisplayedTest(){
        appiumWait.until(ExpectedConditions.visibilityOf(bookButton));

        webDriver.get("URL");

        webDriverWait.until(ExpectedConditions.visibilityOf(webDriver.findElement(By.id("username"))));
        webDriver.findElement(By.id("username")).sendKeys("username");
        webDriver.findElement(By.id("password")).sendKeys("password");
        webDriver.findElement(By.id("button-login")).click();

        appiumWait.until(ExpectedConditions.visibilityOf(alert));

    }

}

```

When I run the following test, I get an ElementNotFound exception on the following line:

```
webDriverWait.until(ExpectedConditions.visibilityOf(webDriver.findElement(By.id("username"))));
```

Here's the stacktrace:
```
org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"id","selector":"username"}
Command duration or timeout: 18 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.47.1', revision: 'unknown', time: '2015-07-30 11:02:44'
System info: host: 'MacBook-Pro.local', ip: 'IP', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.4', java.version: '1.8.0_25'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=37.0.2, platform=MAC, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: a5528d97-5e4a-7646-a74d-4e793d66d54a
*** Element info: {Using=id, value=username}
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:348)
        at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:389)
        at org.openqa.selenium.By$ById.findElement(By.java:215)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:340)
        at EngageTest.pushNotificationIsDisplayedTest(EngageTest.java:102)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
        at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
        at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"id","selector":"username"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.47.1', revision: 'unknown', time: '2015-07-30 11:02:44'
System info: host: 'MacBook-Pro.local', ip: 'IP', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.4', java.version: '1.8.0_25'
Driver info: driver.version: unknown
        at <anonymous class>.FirefoxDriver.prototype.findElementInternal_(file:///var/folders/67/0_32yrc90c91rk8q9fv7w5x40000gp/T/anonymous9040496597686730813webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10667)
        at <anonymous class>.FirefoxDriver.prototype.findElement(file:///var/folders/67/0_32yrc90c91rk8q9fv7w5x40000gp/T/anonymous9040496597686730813webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10676)
        at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///var/folders/67/0_32yrc90c91rk8q9fv7w5x40000gp/T/anonymous9040496597686730813webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12643)
        at <anonymous class>.DelayedCommand.prototype.executeInternal_(file:///var/folders/67/0_32yrc90c91rk8q9fv7w5x40000gp/T/anonymous9040496597686730813webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12648)
        at <anonymous class>.DelayedCommand.prototype.execute/<(file:///var/folders/67/0_32yrc90c91rk8q9fv7w5x40000gp/T/anonymous9040496597686730813webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12590)
```

**Comment by Simon-Kaz** [comment]
Not an appium issue, closing!

**Comment by rkrisztian** [comment]
You might want to use this instead:
https://selenium.googlecode.com/git/docs/api/java/org/openqa/selenium/support/ui/ExpectedConditions.html#visibilityOfElementLocated-org.openqa.selenium.By-
The `visibilityOf` one expects the element to be already present.
