### ISSUE TITLE
MR

### ISSUE THREAD

**Issue by Jack-Martin** [appium/java-client#361]
java.lang.RuntimeException: java.lang.InstantiationException:  error is shown while instantiating the page object class in another package class.  

"FirstPage" and "FirstTest" classes are in different packages 

Test Page:
package pageObjects;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.PageFactory;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.pagefactory.AndroidFindBy;
import io.appium.java_client.pagefactory.AppiumFieldDecorator;
public class FirstPage {
	 public AppiumDriver driver;
	@AndroidFindBy(id="com.test.musicapp.staging:id/pager_button_skip")
	public WebElement button_skip;
	 public TutorialPage(AppiumDriver driver)
		{
			PageFactory.initElements(new AppiumFieldDecorator(driver), this);		
		}
 public void skip() throws InterruptedException
{
	button_skip.click();
}
}

Test class:
package testScripts;
import java.io.File;
import java.net.URL;
import java.util.concurrent.TimeUnit;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.PageFactory;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.android.AndroidDriver;
import pageObjects.FirstPage;
public class FirstTest {
	public AppiumDriver driver;
	@BeforeClass
	public void setUp() throws Exception 
	{
	  	DesiredCapabilities capabilities = new DesiredCapabilities();
	  	File appDir = new File("/Users/Desktop/Android");
	  	File app = new File(appDir, "MUSIC.apk");
	  	capabilities.setCapability("device","Android");
	  	capabilities.setCapability("deviceName", "Name");
	  	capabilities.setCapability("app-package","com.test.musicapp.ui.activity");         
	  	capabilities.setCapability("app-activity","SplashActivity");
	  	capabilities.setCapability("app", app.getAbsolutePath());
	  	driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
	  	driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
	}
	@Test
	public void logic() throws Exception
	{
		TutorialPage Obj = PageFactory.initElements(driver,TutorialPage.class);
		Obj.skip();
	}
	}	

This the error message i got when i run my code using TestNG framework using Eclipse:
FAILED: logic
java.lang.RuntimeException: java.lang.InstantiationException: pageObjects.FirstPage
	at org.openqa.selenium.support.PageFactory.instantiatePage(PageFactory.java:134)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:64)
	at testScripts.Tutorialmethod.logic(Tutorialmethod.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
Caused by: java.lang.InstantiationException: pageObjects.TutorialPage
	at java.lang.Class.newInstance(Class.java:427)
	at org.openqa.selenium.support.PageFactory.instantiatePage(PageFactory.java:131)
	... 26 more
Caused by: java.lang.NoSuchMethodException: pageObjects.TutorialPage.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 27 more

**Comment by TikhomirovSergey** [comment]
@Jack-Martin 
Can you use for the issue reporting https://github.com/appium/java-client/blob/master/ISSUE_TEMPLATE.md? 
And, please use this template furter.

This problem is not related to Appium at all. This exception is thrown here. 
https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/support/PageFactory.java#L134. It means that the target class has no default constructor and constructor which accepts _org.openqa.selenium.WebDriver_ as the parameter. It is default engine of Selenium. 

Also I do not recommend you to this thing:

```java
TutorialPage Obj = PageFactory.initElements(driver,TutorialPage.class);
```
because it may turn into **null** all values which have been filled by _io.appium.java_client.pagefactory.AppiumFieldDecorator_. About the integration of Appium and Selenium PageFactory please read here:  https://github.com/appium/java-client/blob/master/docs/Page-objects.md. Also there is a lot of useful information: https://github.com/appium/java-client/wiki

@Jack-Martin I'm going to close this issue if my answer solves your problem. Also you can close it on your own.

**Comment by Jack-Martin** [comment]
Thanks Sergey Tikhomirov,

By changing the page object parameters the code worked.
