### ISSUE TITLE
[feature request] we need to wrap `ios_webkit_debug_proxy` like AppiumService

### ISSUE THREAD

**Issue by truebit** [appium/java-client#372]
## Description
As java-client does not launch `ios_webkit_debug_proxy` when setting `autoWebview=true` desired capability or query context( e.g. `driver.getContextHandles()` ,`driver.context(String)`, `driver.getContext()`, it would fail like below:

> [MJSONWP] Encountered internal error running command: RequestError: Error: connect ECONNREFUSED 127.0.0.1:27753
>     at new RequestError (/usr/local/lib/node_modules/appium/node_modules/request-promise/lib/errors.js:11:15)
>     at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/appium/node_modules/request-promise/lib/rp.js:60:32)
>     at self.callback (/usr/local/lib/node_modules/appium/node_modules/request-promise/node_modules/request/request.js:199:22)
>     at emitOne (events.js:90:13)
>     at Request.emit (events.js:182:7)
>     at Request.onRequestError (/usr/local/lib/node_modules/appium/node_modules/request-promise/node_modules/request/request.js:821:8)
>     at emitOne (events.js:90:13)
>     at ClientRequest.emit (events.js:182:7)
>     at Socket.socketErrorListener (_http_client.js:306:9)
>     at emitOne (events.js:90:13)
>     at Socket.emit (events.js:182:7)
>     at emitErrorNT (net.js:1249:8)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>     at process._tickCallback (internal/process/next_tick.js:98:9)

I think we could handle this by launching `ios_webkit_debug_proxy` as a service like AppiumService

**Comment by TikhomirovSergey** [comment]
I think it needs for the convenient enhancement of the server

**Comment by SrinivasanTarget** [comment]
https://github.com/appium/appium/issues/4454

**Comment by SrinivasanTarget** [comment]
https://github.com/google/ios-webkit-debug-proxy will go away when https://github.com/appium/appium-remote-debugger is adopted in upcoming server changes

**Comment by Sumanjit13** [comment]
Hi
Is there any workaround for this. As i am also facing this issue when switch to webview or getContextHandles for real device.
Thanks in advance.

**Comment by imurchie** [comment]
The dependency on `ios-webkit-debug-proxy` for real devices will not be going away any time soon. It depends on iOS getting actual automation support into Safari.
