### ISSUE TITLE
When release action of TouchAction executed, the coordinate is negative after 3 moveTo actions.

### ISSUE THREAD

**Issue by JFRabbit** [appium/java-client#542]
## Description

When I use TouchAction to deblock graphical password, I found the release action coordinate change to negative. The graphical password is like a "Z". Detail coordinate please see code.

## Environment

* java client build version or git revision if you use some shapshot: 4.1.2
* Appium server version or git revision if you use some shapshot: 1.4.16.1
* Desktop OS/version used to run Appium if necessary: Windows7 64
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: NA
* Mobile platform/version under test: Android, 6.0. Native app
* Real device or emulator/simulator: Real device

## Details

All move action is OK. But when release action is execute, exception happened.
And I check the error log, the coordinate is [x=-456.0, y=456.0].
Why coordinate is negative? What coordinate should be after move to a point and release finger?

## Code To Reproduce Issue [ Good To Have ]

    deblock(AndroidDriver driver){
		TouchAction action = new TouchAction(driver);
		
		action.press(312, 752).waitAction(1000);
		action.moveTo(456, 0).waitAction(1000);
		action.moveTo(-456, 456).waitAction(1000);
		action.moveTo(456, 0).waitAction(1000);

		action.release().perform();
    }

## Ecxeption stacktraces

Exception:
org.openqa.selenium.interactions.InvalidCoordinatesException: The coordinates provided to an interactions operation are invalid. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 4.20 seconds
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'lenovo-PC', ip: '10.168.1.236', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_112'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{appPackage=com.baoneng.bnfinance.test, networkConnectionEnabled=true, warnings={}, databaseEnabled=false, deviceName=G2W7N15323012269, platform=LINUX, appActivity=com.baoneng.bnfinance.ui.SplashActivity, desired={appPackage=com.baoneng.bnfinance.test, appActivity=com.baoneng.bnfinance.ui.SplashActivity, platformVersion=6.0, unicodeKeyboard=false, platformName=Android, deviceName=any word, resetKeyboard=false}, platformVersion=6.0, webStorageEnabled=false, locationContextEnabled=false, browserName=Android, takesScreenshot=true, javascriptEnabled=true, unicodeKeyboard=false, platformName=Android, resetKeyboard=false}]
Session ID: 0c81aa44-a458-4b0d-be83-0b0af464a73a
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:174)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:635)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at io.appium.java_client.AppiumDriver.performTouchAction(AppiumDriver.java:336)
	at io.appium.java_client.AppiumDriver$$FastClassBySpringCGLIB$$b7cf8974.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
	at io.appium.java_client.events.DefaultAspect.doAround(DefaultAspect.java:530)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at io.appium.java_client.android.AndroidDriver$$EnhancerBySpringCGLIB$$2a1026e7.performTouchAction(<generated>)
	at io.appium.java_client.TouchAction.perform(TouchAction.java:323)
	at atp.apptest.main.testutil.Lock_Pattern.swipeToDeblocking(Lock_Pattern.java:26)
	at atp.apptest.main.unittest.TestProductNameChanged.testDeLock(TestProductNameChanged.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

## Link to Appium logs

Log:
> info: [debug] Pushing command to appium work queue: ["element:touchDown",{"x":312,"y":752}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:touchDown","params":{"x":312,"y":752}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: touchDown
> info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1080,1812]
> info: [debug] [BOOTSTRAP] [debug] Performing TouchDown using element? false x: 312, y: 752
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
> info: [debug] Pushing command to appium work queue: ["element:touchMove",{"x":768,"y":752}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:touchMove","params":{"x":768,"y":752}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: touchMove
> info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1080,1812]
> info: [debug] [BOOTSTRAP] [debug] Performing TouchMove using element? false x: 768, y: 752
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
> info: [debug] Pushing command to appium work queue: ["element:touchMove",{"x":312,"y":1208}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:touchMove","params":{"x":312,"y":1208}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: touchMove
> info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1080,1812]
> info: [debug] [BOOTSTRAP] [debug] Performing TouchMove using element? false x: 312, y: 1208
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
> info: [debug] Pushing command to appium work queue: ["element:touchMove",{"x":768,"y":1208}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:touchMove","params":{"x":768,"y":1208}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: touchMove
> info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1080,1812]
> info: [debug] [BOOTSTRAP] [debug] Performing TouchMove using element? false x: 768, y: 1208
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
> info: [debug] Pushing command to appium work queue: ["element:touchUp",{"x":-456,"y":456}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:touchUp","params":{"x":-456,"y":456}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: touchUp
> info: [debug] Responding to client with error: {"status":29,"value":{"message":"The coordinates provided to an interactions operation are invalid.","origValue":"Coordinate [x=-456.0, y=456.0] is outside of element rect: [0,0][1080,1812]"},"sessionId":"0c81aa44-a458-4b0d-be83-0b0af464a73a"}
> info: <-- POST /wd/hub/session/0c81aa44-a458-4b0d-be83-0b0af464a73a/touch/perform 500 4169.725 ms - 243 
> info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1080,1812]
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":29,"value":"Coordinate [x=-456.0, y=456.0] is outside of element rect: [0,0][1080,1812]"}
> info: --> DELETE /wd/hub/session/0c81aa44-a458-4b0d-be83-0b0af464a73a {}
> info: Shutting down appium session

**Comment by TikhomirovSergey** [comment]
@qwertjkl9090 Hi
Yes. This is the bug. But it is not the client bug and the `moveTo`/swipe action. It is related to Android backend. There is the issue https://github.com/appium/appium/issues/7486.

**Comment by mykola-mokhnach** [comment]
@monanyk Can you check if the patch https://github.com/appium/appium-uiautomator2-server/pull/184 works for you? The deployment tutorial is at https://github.com/appium/python-client/issues/244#issuecomment-414499267

**Comment by monanyk** [comment]
I am getting error while building 

Error:
> Configure project :app
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
Configuration 'testCompile' in project ':app' is deprecated. Use 'testImplementation' instead.
Configuration 'androidTestCompile' in project ':app' is deprecated. Use 'androidTestImplementation' instead.

FAILURE: Build failed with an exception.

Task 'install' is ambiguous in root project 'appium-uiautomator2-server'. Candidates are: 'installAUT', 'installE2eTestDebug'
, 'installE2eTestDebugAndroidTest', 'installServerDebug', 'installServerDebugAndroidTest'. 


Output file is not getting generated.

![l_f75a tmp](https://user-images.githubusercontent.com/42806476/44806219-03d53e00-abe4-11e8-8915-1df249e6b603.PNG)

**Comment by amustroph** [comment]
Why is this bug closed? Is there any workaround? What is the workaround? Is it fixed? In which version is it fixed?

**Comment by saikrishna321** [comment]
@amustroph you are asking about an issue which got closed 1 year back. Please open a new issue if you have a similar issue
