### ISSUE TITLE
Can't use sendKeyEvent

### ISSUE THREAD

**Issue by bridgewaterrobbie** [appium/java-client#586]
## Description

Please describe the issue. It may be a bug description. So then please briefly descride steps which you were trying to perform and what happened instead.
If there is the feature you want to see added to Appium Java client so please describe necessity of this feature and the way that it should work.

## Environment

Appium version (or git revision) that exhibits the issue: 1.6.4
Last Appium version that did not exhibit the issue (if applicable):
MacOS 10.12
Node.js version (unless using Appium.app|exe): 7.5
Mobile platform/version under test: Android 7.1.1
Real device or emulator/simulator: Real device (Pixel)
Appium CLI or Appium.app|exe: CLI

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

wd.sendKeyEvent(33);
Seems to happen regardless of what app is being automated.

## Exception stacktraces
"An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - undefined (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 118 milliseconds"

## Link to Appium logs

`[HTTP] --> POST /wd/hub/session/fce62f7a-3da4-4f4f-9b82-ec494453c078/appium/device/keyevent {"keycode":33}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/fce62f7a-3da4-4f4f-9b82-ec494453c078/appium/device/keyevent] to [POST http://localhost:8200/wd/hub/session/a7728891-cde4-43d2-b528-44376fd4fb1a/appium/device/keyevent] with body: {"keycode":33}
[MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - undefined
    at doJwpProxy$ (../../../lib/mjsonwp/mjsonwp.js:343:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session/fce62f7a-3da4-4f4f-9b82-ec494453c078/appium/device/keyevent 500 114 ms - 274 
`
Including here since it is pretty small.

**Comment by bridgewaterrobbie** [comment]
I opened this issue in the wrong project, sorry about that. 
https://github.com/appium/appium/issues/7991
