### ISSUE TITLE
appium dont work from idea

### ISSUE THREAD

**Issue by desided** [appium/java-client#622]
## Description

when try start project from idea - its not start, in console idea - 
`Exception in thread "main" java.lang.NoClassDefFoundError: org/openqa/selenium/NoSuchSessionException
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:111)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:73)
	at test.main(test.java:22)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.NoSuchSessionException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more

Process finished with exit code 1`

## Environment

* java client build version or git revision if you use some shapshot:1.8
* Appium server version or git revision if you use some shapshot:1.6.3
* Desktop OS/version used to run Appium if necessary:windows/ubuntu
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:4.2.6
* Mobile platform/version under test:android
* Real device or emulator/simulator:genymotion android 5.0

## Details
from idea - appium dont work. 
logs
`appium
[Appium] Welcome to Appium v1.6.4
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
` and all...

## Code To Reproduce Issue [ Good To Have ]
`public class test {
    //public static final String URL = "http://0.0.0.0:4723/wd/hub";
    //public static AndroidDriver driver;
    public static void main(String[] args) throws Exception {
        WebDriver driver;
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("deviceName", "Nexus 7");
        capabilities.setCapability("platformVersion", "5.0");
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("appPackage", "jp.naver.line.android");
        //capabilities.setCapability("noReset", true);
        driver =  new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
        WebDriverWait wait = new WebDriverWait(driver, 5);
    }
}
`

## Ecxeption stacktraces

Please create a [gist](https://gist.github.com) with pasted stacktrace of exception thrown by java.

## Link to Appium logs

when try to go http://0.0.0.0:4723/wd/hub from browser - got it 
`appium
[Appium] Welcome to Appium v1.6.4
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET / {}
[debug] [HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- GET / 404 8 ms - 43 
[HTTP] <-- GET /favicon.ico 200 5 ms - 1150 
[HTTP] --> GET / {}
`

**Comment by SrinivasanTarget** [comment]
@desided We use IntelliJ Ide for our java client dev.It works absolutely fine. Please share the gist in form of gist and open a new issue incase if you hit any issue in our latest version of java client. If you have any question on how appium works please raise it on our discuss forum not here.

**Comment by appiumnovice** [comment]
Hi,
I have the same problem with Appium Java client 5.0.0-BETA6 and BETA7.
The tests are successfully passed with Appium Java client 4.1.2.

Appium release : 1.6.3

Server side error : no trace.

Client side error:
java.lang.NoClassDefFoundError: org/openqa/selenium/NoSuchSessionException
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:111)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:73)
	at com.sncf.automation.framework.AndroidSuperAppiumDriver.<init>(AndroidSuperAppiumDriver.java:30)
	at com.sncf.automation.framework.AndroidSuperAppiumDriver.<init>(AndroidSuperAppiumDriver.java:38)
	at com.sncf.automation.test.common.Application.setUp(Application.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at cucumber.runtime.Utils$1.call(Utils.java:40)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:34)
	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
	at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
	at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
	at cucumber.runtime.Runtime.runBeforeHooks(Runtime.java:202)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:40)
	at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:102)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:95)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:38)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:100)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.NoSuchSessionException
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 45 more

Thanks for your help.
Stéphane
