### ISSUE TITLE
SessionNotCreatedException Using Selenium 3.3.1 and Appium 1.6.4

### ISSUE THREAD

**Issue by ryanlevell** [appium/java-client#627]
## Description

I am trying to run Android and iOS tests on Sauce Labs. I am getting the error ```SessionNotCreatedException: Unable to create new remote session```. I talked to Sauce Labs support and they said the capabilities are being parsed incorrectly and linked me to [Appium #7786](https://github.com/appium/appium/issues/7786). This issue was closed but someone mentioned to create an issue in the java-client project.

## Environment

* Java 8 (on Windows 7)
* Selenium 3.3.1
* Appium 1.6.4
* Appium Java Client 1.4.2

## Details

The ```DesiredCapabilities``` come directly from Sauce Lab's [Platform Configurator](https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/).

I am using version 1.6 in the capabilities as recommended by Sauce Labs:

> As always, we recommend that you use the latest Appium version whenever possible. By setting your appiumVersion desired capability to "1.6"

Downgrading to Selenium 2.53.1 runs the tests correctly.

## Code To Reproduce Issue

```
public static void main(String[] args) throws Exception {
	String url = "http://<user>:<token>@ondemand.saucelabs.com:80/wd/hub";
	DesiredCapabilities caps = DesiredCapabilities.android();
	caps.setCapability("appiumVersion", "1.6");
	caps.setCapability("deviceName", "Android GoogleAPI Emulator");
	caps.setCapability("deviceOrientation", "portrait");
	caps.setCapability("browserName", "Chrome");
	caps.setCapability("platformVersion", "7.0");
	caps.setCapability("platformName", "Android");
	WebDriver driver = new RemoteWebDriver(new URL(url), caps); // line 37
	driver.get("https://google.com");
	driver.quit();
}
```

## Exception stacktraces

```
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{appiumVersion=1.6, platformVersion=7.0, browserName=Chrome, deviceOrientation=portrait, platformName=Android, version=, deviceName=Android GoogleAPI Emulator, platform=ANDROID}], required capabilities = Capabilities [{}]
Build info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'
System info: host: '<computer name>', ip: '<computer ip>', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_45'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:244)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:158)
	at Main.main(Main.java:37)
```

## Link to Appium logs

```
2017-04-18 14:27:54:356 - [Appium] Welcome to Appium v1.6.4
2017-04-18 14:27:54:358 - [Appium] Non-default server args:
2017-04-18 14:27:54:358 - [Appium]   port: 4443
2017-04-18 14:27:54:358 - [Appium]   callbackAddress: 127.0.0.1
2017-04-18 14:27:54:358 - [Appium]   logTimestamp: true
2017-04-18 14:27:54:359 - [Appium]   logNoColors: true
2017-04-18 14:27:54:359 - [Appium]   selendroidPort: 4725
2017-04-18 14:27:54:359 - [Appium]   chromedriverExecutable: /home/chef/chromedriver_2.26_linux_64
2017-04-18 14:27:54:359 - [Appium]   defaultCapabilities: {
2017-04-18 14:27:54:359 - [Appium]     orientation: PORTRAIT
2017-04-18 14:27:54:360 - [Appium]     udid: emulator-5554
2017-04-18 14:27:54:360 - [Appium]     noReset: true
2017-04-18 14:27:54:360 - [Appium]     browserName: chrome
2017-04-18 14:27:54:360 - [Appium]     maxTypingFrequency: 8
2017-04-18 14:27:54:361 - [Appium]     newCommandTimeout: 0
2017-04-18 14:27:54:361 - [Appium]     eventTimings: true
2017-04-18 14:27:54:361 - [Appium]   }
2017-04-18 14:27:54:362 - [Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
2017-04-18 14:27:54:364 - [Appium]   orientation: 'PORTRAIT'
2017-04-18 14:27:54:364 - [Appium]   udid: 'emulator-5554'
2017-04-18 14:27:54:364 - [Appium]   noReset: true
2017-04-18 14:27:54:364 - [Appium]   browserName: 'chrome'
2017-04-18 14:27:54:364 - [Appium]   maxTypingFrequency: 8
2017-04-18 14:27:54:364 - [Appium]   newCommandTimeout: 0
2017-04-18 14:27:54:365 - [Appium]   eventTimings: true
2017-04-18 14:27:54:394 - [Appium] Appium REST http interface listener started on 0.0.0.0:4443
2017-04-18 14:27:54:406 - [HTTP] --> GET /wd/hub/status {}
2017-04-18 14:27:54:408 - [debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
2017-04-18 14:27:54:421 - [debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.4","revision":null}}
2017-04-18 14:27:54:427 - [HTTP] <-- GET /wd/hub/status 200 17 ms - 83 
2017-04-18 14:27:54:560 - [HTTP] --> POST /wd/hub/session {"alwaysMatch":{"deviceName":"Android GoogleAPI Emulator","platform":"ANDROID","browserName":"Chrome","version":"","deviceOrientation":"portrait","platformVersion":"7.0","platformName":"Android","appiumVersion":"1.6"},"desiredCapabilities":{"deviceName":"Android GoogleAPI Emulator","webdriver.remote.quietExceptions":true,"chromeOptions":{"androidPackage":"com.android.chrome"},"browserName":"chrome","proxy":{"proxyAutoconfigUrl":"http://127.0.0.1:19876/pac.js","proxyType":"PAC"},"platformVersion":"7.0","platformName":"Android"},"requiredCapabilities":{},"capabilities":{"requiredCapabilities":{},"desiredCapabilities":{"deviceName":"Android GoogleAPI Emulator","platform":"ANDROID","browserName":"Chrome","version":"","deviceOrientation":"portrait","platformVersion":"7.0","platformName":"Android","appiumVersion":"1.6"}},"firstMatch":[]}
2017-04-18 14:27:54:563 - [debug] [MJSONWP] Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":["desiredCapabilities"],"optional":["requiredCapabilities","capabilities","sessionId","id"]} and you sent ["alwaysMatch","desiredCapabilities","requiredCapabilities","capabilities","firstMatch"]
2017-04-18 14:27:54:566 - [HTTP] <-- POST /wd/hub/session 400 5 ms - 243
```

**Comment by SrinivasanTarget** [comment]
@ryanlevell Can you use latest java client without excluding or downgrading selenium? It should work.

**Comment by ryanlevell** [comment]
I don't use the client at all. It is on Sauce Lab's end. I am not running the Appium server myself. Are you saying I should check with Sauce Lab's to see what java client version they are running?

**Comment by Brian-Watson** [comment]
In my java gradle project, I only specify java-client, and it will pull in the latest version of selenium that it needs and is compatible with.  I do this in build.gradle...

`    compile 'io.appium:java-client:5.0.0-BETA7'
`

**Comment by ryanlevell** [comment]
I was using 1.4.2, but didn't realize it was using Selenium 2.53.1. So this could definitely be the problem as I was using 3.3.1. Sauce Labs is having some technical difficulties, but once it is back up, I will give it a try with 5.0.0-BETA7 as it is updated to 3.3.1.

**Comment by ryanlevell** [comment]
Appium 5.0.0-BETA7 + Selenium 3.3.1 works correctly. I assumed the latest release version (4.1.2) already supported Selenium 3, but it does not. Thanks for the help.

**Comment by fionazj** [comment]
I met same problem even though use same version of selenium and java-client... would you please help to reopen this issue?

**Comment by fionazj** [comment]
@ryanlevell, would you mind take a look at it? thanks~

**Comment by Hellydays** [comment]
The same problem with the same versions(

**Comment by ryanlevell** [comment]
@fionazj @Hellydays Make sure it is not using an older version of Selenium through another dependency.

**Comment by durgesh-provar** [comment]
I too get the above exception for SauceLab while using the data center as "APAC Region".
using selenium 3.4.0 jar
and for other data centers, my code is working.

**Comment by durgesh-provar** [comment]
@fionazj @Hellydays @ryanlevell 
I too get the above exception for SauceLab while using the data center as "APAC Region".
using selenium 3.4.0 jar
and for other data centers, my code is working.
