### ISSUE TITLE
new AndroidDriver Failed at java-client 5.0.0-BETA8

### ISSUE THREAD

**Issue by TomHappy** [appium/java-client#640]
## Description

I upgrade java-client from version 4.1.2 to 5.0.0-BETA8, and got an error when new a AndroidDriver,it works good at java client 4.1.2 :

## Environment

* java client build version or git revision if you use some shapshot:5.0.0-BETA8
* Appium server version or git revision if you use some shapshot:1.6.4,install by "npm install -g appium"  
* Desktop OS/version used to run Appium if necessary:windows10 64bit
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:nodejs version is 6.10.3, v
* Mobile platform/version under test:Android 5.1.1
* Real device or emulator/simulator:real device

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

	@BeforeClass
	public void setUp() throws InterruptedException,NumberFormatException, IOException
	{
		service = AppiumDriverLocalService.buildService(new AppiumServiceBuilder()
				.withIPAddress(readexcel.getValue("AppiumServerIp"))
				.withArgument(GeneralServerFlag.LOG_LEVEL, "error")
				.usingPort(Integer.parseInt(readexcel.getValue("AppiumServerPort")))
				.usingDriverExecutable(new File(readexcel.getValue("Appium_Node_Path")))
				.withAppiumJS(new File(readexcel.getValue("Appium_JS_Path"))));
		service.start();
		appiumServiceUrl = service.getUrl().toString();

		File classpathRoot = new File(System.getProperty("user.dir"));
		File appDir = new File(classpathRoot, "apps");
		File app = new File(appDir, readexcel.getValue("appDir"));
		
		DesiredCapabilities capabilities = new DesiredCapabilities();

		capabilities.setCapability(AndroidMobileCapabilityType.UNICODE_KEYBOARD, true);
		capabilities.setCapability(AndroidMobileCapabilityType.RESET_KEYBOARD, true);
		capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
		capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "5.1.1");
		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "AndroidDevice");
		capabilities.setCapability(MobileCapabilityType.UDID, readexcel.getValue("udid"));
		capabilities.setCapability(MobileCapabilityType.NO_RESET, true);
		capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
		capabilities.setCapability(AndroidMobileCapabilityType.APP_PACKAGE, appPackage);
		capabilities.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY, appActivity);
		
		System.out.println("打印：" + appiumServiceUrl);
		driver = new AndroidDriver<>(new URL(appiumServiceUrl), capabilities);
	}

## Ecxeption stacktraces

FAILED CONFIGURATION: @BeforeClass setUp
java.lang.NoSuchMethodError: com.google.common.base.Throwables.throwIfUnchecked(Ljava/lang/Throwable;)V
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:176)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:112)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:73)
	at utils.BaseTestCaseKeepData.setUp(BaseTestCaseKeepData.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)

**Comment by eliasnogueira** [comment]
I've seem this on Selenium where I use another libs with guava as dependency.
Try to remove guava dependency from Appium (or another lib like log4j) and add the last guava version...

```xml
<dependency>
   <groupId>io.appium</groupId>
   <artifactId>java-client</artifactId>
   <version>5.0.0-BETA8</version>
      <exclusions>
         <exclusion>
            <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
          </exclusion>
       </exclusions>
 </dependency>
 <dependency>
     <groupId>com.google.guava</groupId>
     <artifactId>guava</artifactId>
     <version>21.0</version>
</dependency>
```

**Comment by SrinivasanTarget** [comment]
Selenium will be updating their dependencies sooner during their migration to new APIs.

**Comment by TomHappy** [comment]
Thanks @eliasnogueira and @SrinivasanTarget ,i add the new guava dependency,it works good，i close the issues

**Comment by balajireddytg** [comment]
@eliasnogueira 
i add the new guava dependency and also its not working i'm working with 
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-server</artifactId>
    <version>3.3.0</version>
</dependency>
<dependency>
   <groupId>io.appium</groupId>
   <artifactId>java-client</artifactId>
   <version>5.0.0-BETA8</version>
      <exclusions>
         <exclusion>
            <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
          </exclusion>
       </exclusions>
 </dependency>
 <dependency>
     <groupId>com.google.guava</groupId>
     <artifactId>guava</artifactId>
     <version>21.0</version>
</dependency>


still I'm getting same error

**Comment by gopi1218** [comment]
Hi,
Am getting below error while running basic appium test.Please help me on this.Attached screenshot

java.lang.NoSuchMethodError: com.google.common.base.Throwables.throwIfUnchecked(Ljava/lang/Throwable;)V
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:176)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)


![2](https://user-images.githubusercontent.com/35260154/34755736-073216e0-f5be-11e7-998e-bccf50109502.png)
![1](https://user-images.githubusercontent.com/35260154/34755737-076a9a1a-f5be-11e7-85c2-18e2208acf54.png)
![3](https://user-images.githubusercontent.com/35260154/34755738-07a2ed3e-f5be-11e7-983a-d6fcc3e88ce3.png)
