### ISSUE TITLE
launch test jar - java.lang.RuntimeException: Stub!

### ISSUE THREAD

**Issue by nIvanovp** [appium/java-client#75]
1) I have collected a test project in jar file.

2) After starting the server, run jar file and get the following log: java.lang.RuntimeException: Stub! 
at org.apache.http.params.AbstractHttpParams.(AbstractHttpParams.java:5) at org.apache.http.params.BasicHttpParams.(BasicHttpParams.java:6) at org.openqa.selenium.remote.HttpCommandExecutor.(HttpCommandExecutor.java:93) at org.openqa.selenium.remote.HttpCommandExecutor.(HttpCommandExecutor.java:81) at org.openqa.selenium.remote.RemoteWebDriver.(RemoteWebDriver.java:153) at io.appium.java_client.AppiumDriver.(AppiumDriver.java:43) at com.bn.appium.tests.android.AndroidKpiTests.setUp(AndroidKpiTests.java:40) at com.bn.appium.tests.Main.main(Main.java:22)

3) File appDir = new File("/Users/Admin/Downloads"); 
File app = new File(appDir, "nookforandroid-4.0.0.405-release.apk"); 
DesiredCapabilities capabilities = new DesiredCapabilities(); capabilities.setCapability(CapabilityType.BROWSER_NAME, ""); capabilities.setCapability("platformName", "Android"); 
capabilities.setCapability("deviceName", "08f6df9a");
capabilities.setCapability("platformVersion", "4.4");
capabilities.setCapability("app", app.getAbsolutePath());
capabilities.setCapability("appPackage", "bn.ereader"); 
capabilities.setCapability("appActivity", ".MainActivity"); 
driver = new AppiumDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

Could you help me solve the problem?

**Comment by TikhomirovSergey** [comment]
This issue is not actual, I think. If you can reproduce it with latest client/server versions please open another one.
