### ISSUE TITLE
Error: Carthage not found. Install using `brew install Carthage`.

### ISSUE THREAD

**Issue by keshavwy** [appium/java-client#755]
## Description
If I try to execute the code using testng.xml through eclipse I am facing the above issue. If I try to execute the same code without testng.xml it works fine. I have attach the logs mentioned below.

## Environment

* java client build version or git revision if you use some shapshot:
* Appium server version or git revision if you use some shapshot: 1.7.1
* Desktop OS/version used to run Appium if necessary:
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: iOS 11 (iPhone 6s)
* Real device or emulator/simulator: Both Real and Simulator

## Details

[RemoteTestNG] detected TestNG version 6.8.0
[TestNG] Running:
  /Users/webyog/Documents/workspace/NewtonApp/src/test/resources/runner/testngiOS.xml

Appium server stopped
[Appium] Welcome to Appium v1.7.1
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium]   noReset: true
[Appium] Deprecated server args:
[Appium]   --no-reset => --default-capabilities '{"noReset":true}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   noReset: true
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
AppiumServer Started
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/webyog/Library/Developer/Xcode/DerivedData/CloudMagic-anxksayzldxjhqbtmycmpzzvmqzq/Build/Products/Debug-iphonesimulator/Newton.app","platformVersion":"11.0","appiumVersion":"1.6","automationName":"XCUITest","bundleId":"com.cloudmagic.mail","platformName":"iOS","deviceName":"iPhone 6s"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/webyog/Library/Developer/Xcode/DerivedData/CloudMagic-anxksayzldxjhqbtmycmpzzvmqzq/Build/Products/Debug-iphonesimulator/Newton.app","platformVersion":"11.0","appiumVersion":"1.6","automationName":"XCUITest","bundleId":"com.cloudmagic.mail","platformName":"iOS","deviceName":"iPhone 6s"},null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1508062064521 (15:37:44 GMT+0530 (IST))
[Appium] Creating new XCUITestDriver (v2.51.1) session
[Appium] Capabilities:
[Appium]   app: '/Users/webyog/Library/Developer/Xcode/DerivedData/CloudMagic-anxksayzldxjhqbtmycmpzzvmqzq/Build/Products/Debug-iphonesimulator/Newton.app'
[Appium]   platformVersion: '11.0'
[Appium]   appiumVersion: '1.6'
[Appium]   automationName: 'XCUITest'
[Appium]   bundleId: 'com.cloudmagic.mail'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPhone 6s'
[Appium]   noReset: true
[BaseDriver] The following capabilities were provided, but are not recognized by appium: appiumVersion.
[BaseDriver] Session created with session id: eb325a00-b3fc-4e35-8ff9-38d50f8499bf
[debug] [XCUITest] Xcode version set to '9.0' (tools v9.0.0.0.1.1504363082)
[debug] [XCUITest] iOS SDK Version set to '11.0'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1508062064715 (15:37:44 GMT+0530 (IST))
[iOSSim] Constructing iOS simulator for Xcode version 9.0 with udid '52D63C3C-98C2-42A1-A5C4-27E360F0956B'
[XCUITest] Determining device to run tests on: udid: '52D63C3C-98C2-42A1-A5C4-27E360F0956B', real device: false
[BaseDriver] Using local app '/Users/webyog/Library/Developer/Xcode/DerivedData/CloudMagic-anxksayzldxjhqbtmycmpzzvmqzq/Build/Products/Debug-iphonesimulator/Newton.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1508062065036 (15:37:45 GMT+0530 (IST))
[debug] [XCUITest] Checking whether app '/Users/webyog/Library/Developer/Xcode/DerivedData/CloudMagic-anxksayzldxjhqbtmycmpzzvmqzq/Build/Products/Debug-iphonesimulator/Newton.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [BaseDriver] Event 'resetStarted' logged at 1508062065037 (15:37:45 GMT+0530 (IST))
[debug] [XCUITest] Reset: noReset is on. Leaving simulator as is
[debug] [BaseDriver] Event 'resetComplete' logged at 1508062065037 (15:37:45 GMT+0530 (IST))
[debug] [iOSLog] Starting iOS 11.0 simulator log capture
[debug] [iOSLog] System log path: /Users/webyog/Library/Logs/CoreSimulator/52D63C3C-98C2-42A1-A5C4-27E360F0956B/system.log
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1508062065188 (15:37:45 GMT+0530 (IST))
[XCUITest] Setting up simulator
[debug] [iOS] No reason to set locale
[debug] [iOS] No iOS / app preferences to set
[debug] [iOSSim] Setting common Simulator preferences to {"ConnectHardwareKeyboard":false}
[debug] [iOSSim] Updated shared Simulator preferences at '/Users/webyog/Library/Preferences/com.apple.iphonesimulator.plist' with {"ConnectHardwareKeyboard":false}
[debug] [iOSSim] The count of running Simulator UI client instances is 1
[iOSSim] Both Simulator with UDID 52D63C3C-98C2-42A1-A5C4-27E360F0956B and the UI client are currently running
[debug] [BaseDriver] Event 'simStarted' logged at 1508062065786 (15:37:45 GMT+0530 (IST))
[debug] [XCUITest] Installing '/Users/webyog/Library/Developer/Xcode/DerivedData/CloudMagic-anxksayzldxjhqbtmycmpzzvmqzq/Build/Products/Debug-iphonesimulator/Newton.app' on Simulator with UUID '52D63C3C-98C2-42A1-A5C4-27E360F0956B'...
[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1508062069362 (15:37:49 GMT+0530 (IST))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[debug] [XCUITest] Capability 'useNewWDA' set to false, so trying to reuse currently running WDA instance at 'http://localhost:8100/'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] WDA is not listening at 'http://localhost:8100/'. Rebuilding...
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1508062069500 (15:37:49 GMT+0530 (IST))
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Error: Carthage not found. Install using `brew install carthage`
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at checkForDependencies$ (../../../lib/wda/utils.js:59:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Carthage not found. Install using `brew install carthage`
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at checkForDependencies$ (../../../lib/wda/utils.js:59:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1508062069509 (15:37:49 GMT+0530 (IST))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: "Carthage not found. Install using `brew install carthage`".
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Removing WDA application from device
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1508062080637 (15:38:00 GMT+0530 (IST))
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Error: Carthage not found. Install using `brew install carthage`
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at checkForDependencies$ (../../../lib/wda/utils.js:59:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Carthage not found. Install using `brew install carthage`
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at checkForDependencies$ (../../../lib/wda/utils.js:59:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1508062080640 (15:38:00 GMT+0530 (IST))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: "Carthage not found. Install using `brew install carthage`".
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: "Carthage not found. Install using `brew install carthage`".
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:381:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: "Carthage not found. Install using `brew install carthage`".
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:381:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "Carthage not found. Install using `brew install carthage`".
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:381:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] <-- POST /wd/hub/session 500 27264 ms - 262 

===============================================
iOS_Suite
Total tests run: 1, Failures: 0, Skips: 1
Configuration Failures: 1, Skips: 1
===============================================

**Comment by saikrishna321** [comment]
@keshavwy make sure you have carthage installed 

```
Error: Carthage not found. Install using brew install carthage
```

If your getting this error when running test from eclipse make sure you have set PATH in env of eclipse

**Comment by keshavwy** [comment]
@saikrishna321 

I tried setting up the PATH, but still, it didn't work. I think I am doing something wrong while setting up the PATH in the environment. If you know how to do that successfully, can you help me with exact steps so that it solves this issue?

**Comment by SrinivasanTarget** [comment]
@keshavwy Please check this in our discuss [forum](https://discuss.appium.io/)
