### ISSUE TITLE
org.openqa.selenium.NoSuchElementException even when the element is present

### ISSUE THREAD

**Issue by panshul2006** [appium/java-client#861]
## Description

I've 4 test cases defined using TestNG within my Appium project and all 4 test cases performs almost same code execution besides the difference that all 4 test cases run on different parts of the app I'm automating. The issue I'm facing is within my test case I need to find an element and get its value which works fine in Test Case 1 but fails for Test Case 2, 3 and 4 respectively. However if I comment out Test Case 1, then the code works fine for Test Case 2 but fails for Test Case 3 and 4. If I run code for Test Case 1, 2, 3 or 4 individually, all of them work.  I'm not able to understand why the code works only for the first test case in execution but fails to find the element in the next test case.

Note that the only option for me to find element is using absolute xpath value since the app I'm trying to automate does not have any other attribute defined.

## Environment

* java client 4.1.2
* Appium server version: v1.7.2
* Selenium: v3.4.0
* Desktop OS/version used to run Appium if necessary: Windows 10 x64
* Mobile platform/version under test: Fire TV Stick running on Android 5.1.1
* Real device or emulator/simulator: Real device

## Details

Please provide more details, if necessary.
I've provided the code for Test1. As mentioned earlier, Test2, Test3 and Test4 are same as Test1. The code highlighted in **Bold** is the one which fails from second Test onwards even though the code works fine when tested individually and the element is definitely present on the screen when the code is executed. However the script returns no element found.

## Code To Reproduce Issue [ Good To Have ]

@Test //Test Case for Home tab
	public void Test1_Home() throws InterruptedException, ParseException{
		Thread.sleep(delay3); //Wait for 10 seconds to load the content
		driver.findElementByXPath("//android.widget.FrameLayout[@content-desc=\"Home, Button\"]").click(); //Code to click Home button
		Thread.sleep(delay2); //Wait for 10 seconds to load the content
		((AndroidDriver<WebElement>) driver).pressKeyCode(23); //Code to click first video thumbnail button
		Thread.sleep(delay2); //Wait for 10 seconds to load the content
		//((AndroidDriver<WebElement>) driver).pressKeyCode(23); //Code to click first video thumbnail button
		//Thread.sleep(delay2); //Wait for 10 seconds to load the content
		((AndroidDriver<WebElement>) driver).pressKeyCode(23); //Code to click video thumbnail button to start playback
		Thread.sleep(delay4); //Allow the video to play for 30 seconds including buffering time
		//Video playback verification code starts
		Object xRayDump = null;
		try {
			final Process process = Runtime.getRuntime().exec("adb shell dumpsys activity service com.amazon.ssm/.OverlayService"); //Execute adb command of X-ray output
			InputStream inStream = process.getInputStream();
			final BufferedReader br= new BufferedReader(
			new InputStreamReader(inStream));
			String line;
			while ((line = br.readLine()) != null) {
				xRayDump = xRayDump + line + "\n"; //Get dump of X-ray output to 'xRayDump'
			}
			br.close();
			try {
				process.waitFor();
			}
			catch (final InterruptedException e) {
				System.out.println(e.getMessage());
			}
		} catch (final Exception e) {
			System.out.println(e.getMessage());
		}
		// System.out.println(xRayDump); //Prints contents of 'xRayDump' which contains entire dump of X-ray output
		if(!((String) xRayDump).isEmpty())
		{
			String s = String.valueOf(xRayDump); //Copy contents of xRayDump to a string variable 's'
			Pattern pattern = Pattern.compile("\\[com.amazon.ssm.multimedia.video.framerate\\]: \\[(.*?)\\]"); //Regular expression to get value of frame rate from X-ray output
			Matcher matcher = pattern.matcher(s);
			while (matcher.find())
			{
				s=matcher.group(1); //Copy output of matched pattern from the above mentioned regular expression to the string variable 's'
				// System.out.println(s); //Prints contents of string variable 's'
			}
			if(s=="null") //Condition to check if frame rate is null i.e. no video played
			{
				boolean result = false; //Set result to false
				System.out.println("Home: No video playback observed");
				Assert.assertTrue(result); //Fails the test case
			}
			else
			{
				boolean result = true; //Set result to true
				System.out.println("Home: Video playback observed");
				Assert.assertTrue(result); //Passes the test case
			}
		}
		//Video playback verification code ends
		Thread.sleep(delay2); //Wait for 10 seconds
		//Video pause verification code starts
		((AndroidDriver<WebElement>) driver).pressKeyCode(23); //Pause the video
		Thread.sleep(1000); //Wait for 1 seconds
		**strTime1 = driver.findElementByXPath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout[1]/android.widget.FrameLayout/android.widget.FrameLayout[3]/android.widget.FrameLayout[3]/android.widget.FrameLayout[2]/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.TextView").getText();**
		System.out.println(strTime1);
		Thread.sleep(delay1); //Wait for 5 seconds
		strTime2 = driver.findElementByXPath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout[1]/android.widget.FrameLayout/android.widget.FrameLayout[3]/android.widget.FrameLayout[3]/android.widget.FrameLayout[2]/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.TextView").getText();
		System.out.println(strTime2);
		time1 = time.parse(strTime1);
		time2 = time.parse(strTime2);
		System.out.println(time1);
		System.out.println(time2);
		if(String.valueOf(strTime1).equals(String.valueOf(strTime2)))
		{
			boolean result = true; //Set result to true
			System.out.println("Home: Video playback pause successful");
			Assert.assertTrue(result); //Passes the test case
		}
		else
		{
			boolean result = false; //Set result to false
			System.out.println("Home: Video playback pause failed");
			Assert.assertTrue(result); //Fails the test case
		}
		//Video pause verification code ends
		Thread.sleep(delay1); //Wait for 5 seconds
		driver.findElementByXPath("//android.widget.FrameLayout[contains(@content-desc, \"Play at\")]/android.widget.FrameLayout/android.widget.ImageView").click(); //Resume the playback by pressing Play button on the screen
		Thread.sleep(delay2); //Allow the video to play for 10 seconds including buffering time
		//Video forward verification code starts
		((AndroidDriver<WebElement>) driver).pressKeyCode(20); //Press DPad Down key to invoke seekbar
		Thread.sleep(1000); //Wait for 1 seconds
		strTime1 = driver.findElementByXPath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout[1]/android.widget.FrameLayout/android.widget.FrameLayout[3]/android.widget.FrameLayout[3]/android.widget.FrameLayout[2]/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.TextView").getText();
		System.out.println(strTime1);
		((AndroidDriver<WebElement>) driver).longPressKeyCode(90); //Forward the video
		Thread.sleep(delay1); //Forwards for 5 seconds
		((AndroidDriver<WebElement>) driver).pressKeyCode(23); //Play the video
		((AndroidDriver<WebElement>) driver).pressKeyCode(20); //Press DPad Down key to invoke seekbar
		Thread.sleep(1000); //Wait for 1 seconds
		strTime2 = driver.findElementByXPath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout[1]/android.widget.FrameLayout/android.widget.FrameLayout[3]/android.widget.FrameLayout[3]/android.widget.FrameLayout[2]/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.TextView").getText();
		System.out.println(strTime2);
		time1 = time.parse(strTime1);
		time2 = time.parse(strTime2);
		System.out.println(time1);
		System.out.println(time2);
		if(time2.after(time1))
		{
			boolean result = true; //Set result to true
			System.out.println("Home: Video playback forward successful");
			Assert.assertTrue(result); //Passes the test case
		}
		else
		{
			boolean result = false; //Set result to false
			System.out.println("Home: Video playback forward failed");
			Assert.assertTrue(result); //Fails the test case
		}
		//Video forward verification code ends
		Thread.sleep(delay2); //Wait for 10 seconds
		//Video rewind verification code starts
		((AndroidDriver<WebElement>) driver).pressKeyCode(20); //Press DPad Down key to invoke seekbar
		Thread.sleep(1000); //Wait for 1 seconds
		strTime1 = driver.findElementByXPath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout[1]/android.widget.FrameLayout/android.widget.FrameLayout[3]/android.widget.FrameLayout[3]/android.widget.FrameLayout[2]/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.TextView").getText();
		System.out.println(strTime1);
		((AndroidDriver<WebElement>) driver).longPressKeyCode(89); //Rewind the video
		Thread.sleep(delay1); //Rewinds for 5 seconds
		((AndroidDriver<WebElement>) driver).pressKeyCode(23); //Play the video
		((AndroidDriver<WebElement>) driver).pressKeyCode(20); //Press DPad Down key to invoke seekbar
		Thread.sleep(1000); //Wait for 1 seconds
		strTime2 = driver.findElementByXPath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout[1]/android.widget.FrameLayout/android.widget.FrameLayout[3]/android.widget.FrameLayout[3]/android.widget.FrameLayout[2]/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.TextView").getText();
		System.out.println(strTime2);
		time1 = time.parse(strTime1);
		time2 = time.parse(strTime2);
		System.out.println(time1);
		System.out.println(time2);
		if(time2.before(time1))
		{
			boolean result = true; //Set result to true
			System.out.println("Home: Video playback rewind successful");
			Assert.assertTrue(result); //Passes the test case
		}
		else
		{
			boolean result = false; //Set result to false
			System.out.println("Home: Video playback rewind failed");
			Assert.assertTrue(result); //Fails the test case
		}
		//Video rewind verification code ends
		Thread.sleep(delay2); //Allow the video to play for 10 seconds including buffering time
	}

## Exception stack traces

org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 10.13 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'MININT-G6S73SJ', ip: '192.168.0.121', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_161'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{appPackage=com.HBO, deviceScreenSize=1920x1080, networkConnectionEnabled=true, noReset=true, warnings={}, databaseEnabled=false, deviceName=G070L8157432230F, fullReset=false, platform=LINUX, deviceUDID=G070L8157432230F, appActivity=com.hbo.go.LaunchActivity, desired={appPackage=com.HBO, appActivity=com.hbo.go.LaunchActivity, noReset=true, platformVersion=5.1.1, browserName=, platformName=Android, deviceName=FireTVStick, fullReset=false}, platformVersion=5.1.1, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, browserName=, javascriptEnabled=true, deviceModel=AFTT, platformName=Android, deviceManufacturer=Amazon}]
Session ID: c32ca202-bd39-4ca9-8744-a052376864d9
*** Element info: {Using=xpath, value=/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout[1]/android.widget.FrameLayout/android.widget.FrameLayout[3]/android.widget.FrameLayout[3]/android.widget.FrameLayout[2]/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.TextView}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:671)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:410)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:56)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:509)
	at io.appium.java_client.DefaultGenericMobileDriver.findElementByXPath(DefaultGenericMobileDriver.java:134)
	at io.appium.java_client.AppiumDriver.findElementByXPath(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElementByXPath(AndroidDriver.java:1)
	at amazon.StartApplication.Test3_Movies(StartApplication.java:428)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

Let me know if any further information is required. Any kind of help would be appreciated

## Link to Appium logs

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by TikhomirovSergey** [comment]
client v4.1.2, server v1.7.2 and Selenium v3.4.0 are outdated. Could you update artefacts?
I am closing this issue.

**Comment by paishali23** [comment]
Exception in thread "main" org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters.
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'DESKTOP-3M59BK0', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {appActivity: .MainActivity, appPackage: com.chla.patientapp, databaseEnabled: false, desired: {appActivity: .MainActivity, appPackage: com.chla.patientapp, deviceName: emulator-5554, platformName: android}, deviceApiLevel: 28, deviceManufacturer: Google, deviceModel: Android SDK built for x86, deviceName: emulator-5554, deviceScreenDensity: 440, deviceScreenSize: 1080x2220, deviceUDID: emulator-5554, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, pixelRatio: 2.75, platform: LINUX, platformName: android, platformVersion: 9, statBarHeight: 66, takesScreenshot: true, viewportRect: {height: 2022, left: 0, top: 66, width: 1080}, warnings: {}, webStorageEnabled: false}
Session ID: c77b3eb4-d8ce-4fca-8272-77977ffcfaa8
*** Element info: {Using=xpath, value=/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup[1]/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[2]/android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[3]/android.view.ViewGroup}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:61)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:428)
	at io.appium.java_client.DefaultGenericMobileDriver.findElementByXPath(DefaultGenericMobileDriver.java:151)
	at io.appium.java_client.AppiumDriver.findElementByXPath(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElementByXPath(AndroidDriver.java:1)
	at automation.main(automation.java:30)
