### ISSUE TITLE
i am new here,when i write like this    driver.findElement(By.id("com.example.a24189.myapplication:id/tv_test")).click(); get NullPointerException

### ISSUE THREAD

**Issue by chenqingru** [appium/java-client#886]
this is my code 
 DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("deviceName", "IBR899MNBQHATKNB");
        capabilities.setCapability("automationName", "Appium");
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("platformVersion", "4.4.4");
        capabilities.setCapability("appPackage", "com.example.a24189.myapplication");
        capabilities.setCapability("appActivity", "com.example.a24189.myapplication.Main2Activity");
        capabilities.setCapability(AUTO_GRANT_PERMISSIONS,"true");
        capabilities.setCapability("noReset",true);//不重装app
        capabilities.setCapability("noSign",true);//不进行重签名
        AndroidDriver driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

        Thread.sleep(1000*1);
        driver.findElement(By.id("com.example.a24189.myapplication:id/tv_test")).click();

## Environment

* java client : 5.0.0-BETA9
* Appium server version : 3.8
* Real device or emulator/simulator:  Real device

## 
server log
[HTTP] {"using":"class name","value":"android.widget.TextView"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["class name","android.widget.TextView","3816d0a5-e489-46a5-b982-0488a1001213"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"class name","selector":"android.widget.TextView","context":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"class name","selector":"android.widget.TextView","context":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'android.widget.TextView' using 'CLASS_NAME' with the contextId: '' multiple: false
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[CLASS=android.widget.TextView, INSTANCE=0]
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"value":{"ELEMENT":"1"},"status":0}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"1"}
[HTTP] <-- POST /wd/hub/session/3816d0a5-e489-46a5-b982-0488a1001213/element 200 106 ms - 87
[HTTP]

client log 

Exception in thread "main" java.lang.NullPointerException
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:279)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:83)
	at com.example.CalculatorTest.main(CalculatorTest.java:39)

**Comment by chenqingru** [comment]
i change java client version and then solved the problem
