### ISSUE TITLE
PageFactory.initElements(new AppiumFieldDecorator(driver,10, TimeUnit.SECONDS), this)

### ISSUE THREAD

**Issue by stephenws** [appium/java-client#907]
## Description

For PageFactory Constructor when we try to initialise Pagefactory 
AppiumFieldDecorator is not working
Could you pleas tell what should be used 

## Environment

* java client build version or git revision if you use some shapshot: 6.00 Beta5
* Appium server version or git revision if you use some shapshot: 1.7.0
* Desktop OS/version used to run Appium if necessary:
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test:
* Real device or emulator/simulator:

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.
You can git clone https://github.com/appium/sample-code or https://github.com/appium/sample-code/tree/master/sample-code/apps and reproduce an issue using Java and sample apps.
Also you can create a [gist](https://gist.github.com) with pasted java code sample or put it here using markdown. About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and 
[Writing on GitHub](https://help.github.com/categories/writing-on-github/)

## Ecxeption stacktraces

Please create a [gist](https://gist.github.com) with pasted stacktrace of exception thrown by java.

## Link to Appium logs

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by mykola-mokhnach** [comment]
By providing the example code and stacktraces you can help yourself

**Comment by Siddh010** [comment]
I am facing similar issue with latest Java client 6.0.0 with 👎 java.lang.ExceptionInInitializerError
	at io.appium.java_client.pagefactory.utils.ProxyFactory.getEnhancedProxy(ProxyFactory.java:52)
	at io.appium.java_client.pagefactory.utils.ProxyFactory.getEnhancedProxy(ProxyFactory.java:33)
	at io.appium.java_client.pagefactory.AppiumFieldDecorator.proxyForAnElement(AppiumFieldDecorator.java:217)
	at io.appium.java_client.pagefactory.AppiumFieldDecorator.access$0(AppiumFieldDecorator.java:215)
	at io.appium.java_client.pagefactory.AppiumFieldDecorator$1.proxyForLocator(AppiumFieldDecorator.java:107)
	at org.openqa.selenium.support.pagefactory.DefaultFieldDecorator.decorate(DefaultFieldDecorator.java:62)
	at io.appium.java_client.pagefactory.AppiumFieldDecorator.decorate(AppiumFieldDecorator.java:155)
	at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:113)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
	at com.greatWest.pageObject.LoginPage.<init>(LoginPage.java:82)
