### ISSUE TITLE
StaleElement Exception even when using "ignoring(StaleElementReferenceException.class, StaleElementReferenceException.class)"

### ISSUE THREAD

**Issue by Gocoollnath** [appium/java-client#925]
## Description

StaleElement Exception even when using "ignoring(StaleElementReferenceException.class, StaleElementReferenceException.class)"

## Environment

Appium version (or git revision) that exhibits the issue: 1.8.1

Java Client - v6.0.0
Desktop OS/version used to run Appium: Windows 10
Node.js version (unless using Appium.app|exe): Latest
Mobile platform/version under test: API 25
Real device or emulator/simulator: Real device
Appium CLI or Appium.app|exe: Appium CLI
TestNG -6.14.3
Extent Reports - 2.41.2

## Code To Reproduce Issue [ Good To Have ]

new WebDriverWait(driver,250).ignoring(StaleElementReferenceException.class, StaleElementReferenceException.class).until(ExpectedConditions.elementToBeClickable(By.id("element")))

## Ecxeption stacktraces

org.openqa.selenium.StaleElementReferenceException: android.support.test.uiautomator.StaleObjectException
	at android.support.test.uiautomator.UiObject2.getAccessibilityNodeInfo(UiObject2.java:629)
	at android.support.test.uiautomator.UiObject2.getVisibleBounds(UiObject2.java:210)
	at android.support.test.uiautomator.UiObject2.getVisibleCenter(UiObject2.java:251)
	at android.support.test.uiautomator.UiObject2.click(UiObject2.java:343)
	at io.appium.uiautomator2.model.UiObject2Element.click(UiObject2Element.java:64)
	at io.appium.uiautomator2.handler.Click.safeHandle(Click.java:38)
	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:65)
	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:247)
	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:238)
	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:762)

For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'IN-GOKUL-D', ip: '192.168.89.101', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '10'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {appActivity: com.amcsgroup.amcsmobile.AM..., appPackage: com.amcsgroup.amcsmobile, autoGrantPermissions: true, automationName: Uiautomator2, databaseEnabled: false, desired: {appActivity: com.amcsgroup.amcsmobile.AM..., appPackage: com.amcsgroup.amcsmobile, autoGrantPermissions: true, automationName: Uiautomator2, deviceName: Android Device, newCommandTimeout: 0, platformName: android}, deviceApiLevel: 25, deviceManufacturer: samsung, deviceModel: SM-T385, deviceName: 192.168.89.65:5555, deviceScreenDensity: 213, deviceScreenSize: 800x1280, deviceUDID: 192.168.89.65:5555, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, newCommandTimeout: 0, pixelRatio: 1.3312501, platform: LINUX, platformName: LINUX, platformVersion: 7.1.1, statBarHeight: 32, takesScreenshot: true, viewportRect: {height: 768, left: 0, top: 32, width: 1280}, warnings: {}, webStorageEnabled: false}
Session ID: 4b6843cc-f2ad-41a1-a51e-6081efd408a3
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:218)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:276)
	at io.appium.java_client.DefaultGenericMobileElement.execute(DefaultGenericMobileElement.java:45)
	at io.appium.java_client.MobileElement.execute(MobileElement.java:1)
	at io.appium.java_client.android.AndroidElement.execute(AndroidElement.java:1)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:83)
	at test_demo.route_job(test_demo.java:263)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

## Link to Appium logs

https://gist.github.com/Gocoollnath/d8c880d7b02f300490cfd436aabb5d7b

**Comment by Gocoollnath** [comment]
It doesn't wait till the time specified. It throws the exception before that.

**Comment by mykola-mokhnach** [comment]
The attached server log says the opposite, since I observe multiple calls to `elementDisplayed` there

**Comment by Gocoollnath** [comment]
I gave 250 seconds as wait time. But it doesn't

**Comment by Warren25** [comment]
@Gocoollnath These are two methods I use to resolve this issue:

public void waitForElement(WebElement element) {
        withTimeoutOf(Duration.ofSeconds(20))
                .doWait()
                .ignoring(Exception.class)
                .pollingEvery(Duration.ofSeconds(1))
                .until(exp -> element.isDisplayed() || !element.isDisplayed());
    }

    public void waitForElements(List<WebElement> elements) {
        withTimeoutOf(Duration.ofSeconds(20))
                .doWait()
                .ignoring(Exception.class)
                .pollingEvery(Duration.ofSeconds(1))
                .until(exp ->
                        elements.stream().allMatch(element -> element.isDisplayed() || !element.isDisplayed()));
    }

Hopefully this helps!

**Comment by 0neel** [comment]
From your stack trace, I see that `click()` is called outside of wait:
```
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:83)
at test_demo.route_job(test_demo.java:263)
```
That's why `.ignoring(StaleElementReferenceException.class)` is not working.
