### ISSUE TITLE
org.openqa.selenium.WebDriverException: java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by chethanshetty09** [appium/java-client#947]
## This issue is already reported under 
https://github.com/appium/appium-desktop/issues/566#issuecomment-397541626

Appium - 1.6.1
Appium server - 1.8.0
Java-Client - 6.0.0
Selenium - 3.12.0

The problem
I am getting java.net.SocketException: Connection reset during some step [execution]
https://github.com/appium/appium-desktop/files/2087613/appium-server-logs.txt

Especially during the debugging the line and randomly when execution is in progress.

Environment
MAC - 10.13.2

Java logs:

org.openqa.selenium.WebDriverException: java.net.SocketException: Connection reset
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: '', ip: '', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_101'
Driver info: driver.version: AppiumDriver
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:233)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:344)
at io.appium.java_client.DefaultGenericMobileDriver.findElements(DefaultGenericMobileDriver.java:54)
at io.appium.java_client.AppiumDriver.findElements(AppiumDriver.java:152)
at io.appium.java_client.FindsByAccessibilityId.findElementsByAccessibilityId(FindsByAccessibilityId.java:50)
at io.appium.java_client.AppiumDriver.findElementsByAccessibilityId(AppiumDriver.java:188)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
at org.testng.TestRunner.privateRun(TestRunner.java:756)
at org.testng.TestRunner.run(TestRunner.java:610)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
at org.testng.SuiteRunner.run(SuiteRunner.java:289)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
at org.testng.TestNG.runSuites(TestNG.java:1133)
at org.testng.TestNG.run(TestNG.java:1104)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
Caused by: java.net.SocketException: Connection reset
at java.net.SocketInputStream.read(Unknown Source)
at java.net.SocketInputStream.read(Unknown Source)
at okio.Okio$2.read(Okio.java:139)
at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:212)
at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
at okhttp3.RealCall.execute(RealCall.java:77)
at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:105)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:155)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:218)
... 37 more

**Comment by SrinivasanTarget** [comment]
https://github.com/appium/java-client/issues/922

**Comment by JohnHuahuaZhan** [comment]
@SrinivasanTarget 
Appium 1.8 works well with android but throw 'connection reset' exception with iOS. this exception happens very  frequently at iOS platform.

**Comment by SrinivasanTarget** [comment]
@JohnHuahuaZhan Can you replace the java client dependency in your project and add the below one and give a try?
<img width="929" alt="screen shot 2018-06-19 at 12 53 40 pm" src="https://user-images.githubusercontent.com/8896549/41582874-705ba20a-73c0-11e8-9b5a-53804247bd0b.png">

**Comment by tobecrazy** [comment]
I got the same errors when I try to debug my code.

**Comment by JohnHuahuaZhan** [comment]
@SrinivasanTarget 
I could not solve the dependence.
[05fa225c56](https://jitpack.io/com/github/appium/java-client/05fa225c56/) it is only a build log there

**Comment by saikrishna321** [comment]
@SrinivasanTarget to use jitpack, java-client should also have the repo added. So its not gonna work,


@JohnHuahuaZhan i would suggest you to build the master locally n replace the .jar file into .m2 io.appium folder

**Comment by NavdeepSingh09** [comment]
Can anyone describe in detail how it fixed?

**Comment by SrinivasanTarget** [comment]
> to use jitpack, java-client should also have the repo added. So its not gonna work,

Not necessary. Failure was due to signing of artifacts.

> Can anyone describe in detail how it fixed?

Can you try in latest version of java client.

**Comment by NavdeepSingh09** [comment]
I believe it's working right now thanks

**Comment by SrinivasanTarget** [comment]
Thanks. Feel free to reopen incase if you hit the same.

**Comment by deepikashekar37** [comment]
I was facing the same error . After upgrading java client to 6.1.10 . It solved.

@SrinivasanTarget 
Thanks

**Comment by chittamit79** [comment]
I was also facing the same error. After upgrading java client to 6.1.0. It solved.

Thanks
