### ISSUE TITLE
Appium  scripts sometimes wrong wrong without any reason in appium logs

### ISSUE THREAD

**Issue by lwb2001258** [appium/java-client#948]
## Description

Please describe the issue. It may be a bug description. So then please briefly descride steps which you were trying to perform and what happened instead.
If there is the feature you want to see added to Appium Java client so please describe necessity of this feature and the way that it should work.

## Environment

* java client build version or git revision if you use some shapshot:3.4.1
* Appium server version or git revision if you use some shapshot:1.6.5
* Desktop OS/version used to run Appium if necessary:win 10
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:8.4
* Mobile platform/version under test:API24 Android 7.0
* Real device or emulator/simulator:Real device

## Details

Link the remote devices to the computer with USB wire. Appium scripts sometimes(not always) would went wrong with the error(But the USB wire is ok and the scripts is not stable):
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'DESKTOP-F6GLHCI', ip: '192.168.8.34', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_171'
Driver info: driver.version: AndroidDriver
Capabilities [{app=F:\appiumforone\A03APK\A03V2T.apk, appPackage=com.iteach.zed.a03, appActivity=com.iteach.zed.a03.activity.LoginActivity, noReset=true, noSign=true, newCommandTimeout=10000, automationName=UiAutomator2, unicodeKeyboard=true, platformName=Android, deviceName=huawei, resetKeyboard=true, platform=ANY}]
Session ID: 53c66c8a-5717-44ff-8d79-6098bcc87d99
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:43)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.startActivity(AndroidDriver.java:234)
	at io.appium.java_client.android.AndroidDriver.startActivity(AndroidDriver.java:247)
	at io.appium.java_client.android.AndroidDriver.startActivity(AndroidDriver.java:257)
	at com.iteach.zed.a03.utils.DriverUtil.login(DriverUtil.java:96)
	at com.iteach.zed.a03.main.A03ClickAll.wodeChickAll(A03ClickAll.java:1131)
	at com.iteach.zed.a03.main.ClickAllTest.t_004_冒烟测试_我的页面点击测试(ClickAllTest.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused: connect
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'DESKTOP-F6GLHCI', ip: '192.168.8.34', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_171'
Driver info: driver.version: AndroidDriver
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:76)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	... 21 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:144)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:64)
	... 22 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 35 more

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.
You can git clone https://github.com/appium/sample-code or https://github.com/appium/sample-code/tree/master/sample-code/apps and reproduce an issue using Java and sample apps.
Also you can create a [gist](https://gist.github.com) with pasted java code sample or put it here using markdown. About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and 
[Writing on GitHub](https://help.github.com/categories/writing-on-github/)

## Ecxeption stacktraces

org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'DESKTOP-F6GLHCI', ip: '192.168.8.34', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_171'
Driver info: driver.version: AndroidDriver
Capabilities [{app=F:\appiumforone\A03APK\A03V2T.apk, appPackage=com.iteach.zed.a03, appActivity=com.iteach.zed.a03.activity.LoginActivity, noReset=true, noSign=true, newCommandTimeout=10000, automationName=UiAutomator2, unicodeKeyboard=true, platformName=Android, deviceName=huawei, resetKeyboard=true, platform=ANY}]
Session ID: 53c66c8a-5717-44ff-8d79-6098bcc87d99
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:43)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.startActivity(AndroidDriver.java:234)
	at io.appium.java_client.android.AndroidDriver.startActivity(AndroidDriver.java:247)
	at io.appium.java_client.android.AndroidDriver.startActivity(AndroidDriver.java:257)
	at com.iteach.zed.a03.utils.DriverUtil.login(DriverUtil.java:96)
	at com.iteach.zed.a03.main.A03ClickAll.wodeChickAll(A03ClickAll.java:1131)
	at com.iteach.zed.a03.main.ClickAllTest.t_004_冒烟测试_我的页面点击测试(ClickAllTest.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused: connect
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'DESKTOP-F6GLHCI', ip: '192.168.8.34', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_171'
Driver info: driver.version: AndroidDriver
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:76)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	... 21 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:144)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:64)
	... 22 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 35 more

## Link to Appium logs(seems to be well but not true)

[HTTP] <-- GET /wd/hub/session/a656ea3a-90c6-46ed-8dca-8445d2bbf1db/element/7ad570b1-c733-44b7-b455-ded8e8ab914e/attribute/selected 200 18 ms - 79 
[HTTP] --> POST /wd/hub/session/a656ea3a-90c6-46ed-8dca-8445d2bbf1db/element {"using":"id","value":"com.iteach.zed.a03:id/point_ct"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["id","com.iteach.zed.a03:id/point_ct","a656ea3a-90c6-46ed-8dca-8445d2bbf1db"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 2000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8206/wd/hub/session/0c5b0468-2506-457e-aaee-d26b5d6a2c33/element] with body: {"strategy":"id","selector":"com.iteach.zed.a03:id/point_ct","context":"","multiple":false}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"0c5b0468-2506-457e-aaee-d26b5d6a2c33","status":0,"value":{"ELEMENT":"80d8eaa7-0c88-4f3f-9f68-f1e0e9c184ca"}}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"80d8eaa7-0c88-4f3f-9f68-f1e0e9c184ca"}
[HTTP] <-- POST /wd/hub/session/a656ea3a-90c6-46ed-8dca-8445d2bbf1db/element 200 41 ms - 122 
[HTTP] --> GET /wd/hub/session/a656ea3a-90c6-46ed-8dca-8445d2bbf1db/element/80d8eaa7-0c88-4f3f-9f68-f1e0e9c184ca/attribute/selected {}
[debug] [MJSONWP] Calling AppiumDriver.getAttribute() with args: ["selected","80d8eaa7-0c88-4f3f-9f68-f1e0e9c184ca","a656ea3a-90c6-46ed-8dca-8445d2bbf1db"]
[debug] [JSONWP Proxy] Proxying [GET /element/80d8eaa7-0c88-4f3f-9f68-f1e0e9c184ca/attribute/selected] to [GET http://localhost:8206/wd/hub/session/0c5b0468-2506-457e-aaee-d26b5d6a2c33/element/80d8eaa7-0c88-4f3f-9f68-f1e0e9c184ca/attribute/selected] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"0c5b0468-2506-457e-aaee-d26b5d6a2c33\",\"status\":0,\"value\":\"false\"}"
[debug] [MJSONWP] Responding to client with driver.getAttribute() result: "false"
[HTTP] <-- GET /wd/hub/session/a656ea3a-90c6-46ed-8dca-8445d2bbf1db/element/80d8eaa7-0c88-4f3f-9f68-f1e0e9c184ca/attribute/selected 200 17 ms - 79 
[HTTP] --> POST /wd/hub/session/a656ea3a-90c6-46ed-8dca-8445d2bbf1db/element {"using":"id","value":"com.iteach.zed.a03:id/point_wifi"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["id","com.iteach.zed.a03:id/point_wifi","a656ea3a-90c6-46ed-8dca-8445d2bbf1db"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 2000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8206/wd/hub/session/0c5b0468-2506-457e-aaee-d26b5d6a2c33/element] with body: {"strategy":"id","selector":"com.iteach.zed.a03:id/point_wifi","context":"","multiple":false}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"0c5b0468-2506-457e-aaee-d26b5d6a2c33","status":0,"value":{"ELEMENT":"56283693-9e66-420e-af66-3b9d0c842d05"}}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"56283693-9e66-420e-af66-3b9d0c842d05"}
[HTTP] <-- POST /wd/hub/session/a656ea3a-90c6-46ed-8dca-8445d2bbf1db/element 200 47 ms - 122 
[HTTP] --> GET /wd/hub/session/a656ea3a-90c6-46ed-8dca-8445d2bbf1db/element/56283693-9e66-420e-af66-3b9d0c842d05/attribute/selected {}
[debug] [MJSONWP] Calling AppiumDriver.getAttribute() with args: ["selected","56283693-9e66-420e-af66-3b9d0c842d05","a656ea3a-90c6-46ed-8dca-8445d2bbf1db"]
[debug] [JSONWP Proxy] Proxying [GET /element/56283693-9e66-420e-af66-3b9d0c842d05/attribute/selected] to [GET http://localhost:8206/wd/hub/session/0c5b0468-2506-457e-aaee-d26b5d6a2c33/element/56283693-9e66-420e-af66-3b9d0c842d05/attribute/selected] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"0c5b0468-2506-457e-aaee-d26b5d6a2c33\",\"status\":0,\"value\":\"false\"}"
[debug] [MJSONWP] Responding to client with driver.getAttribute() result: "false"
[HTTP] <-- GET /wd/hub/session/a656ea3a-90c6-46ed-8dca-8445d2bbf1db/element/56283693-9e66-420e-af66-3b9d0c842d05/attribute/selected 200 22 ms - 79 
[HTTP] --> DELETE /wd/hub/session/a656ea3a-90c6-46ed-8dca-8445d2bbf1db {}
[debug] [MJSONWP] Calling AppiumDriver.deleteSession() with args: ["a656ea3a-90c6-46ed-8dca-8445d2bbf1db"]
[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1529239596210 (20:46:36 GMT+0800 (中国标准时间))
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [JSONWP Proxy] Proxying [DELETE /] to [DELETE http://localhost:8206/wd/hub/session/0c5b0468-2506-457e-aaee-d26b5d6a2c33] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"0c5b0468-2506-457e-aaee-d26b5d6a2c33\",\"status\":0,\"value\":\"Session deleted\"}"
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'E:\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","GSLDU17C06003131","shell","am","force-stop","com.iteach.zed.a03"]
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8206 
[debug] [ADB] Running 'E:\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","GSLDU17C06003131","forward","--remove","tcp:8206"]
[Appium] Removing session a656ea3a-90c6-46ed-8dca-8445d2bbf1db from our master session list
[debug] [BaseDriver] Event 'quitSessionFinished' logged at 1529239597409 (20:46:37 GMT+0800 (中国标准时间))
[debug] [MJSONWP] Received response: null
[debug] [MJSONWP] But deleting session, so not returning
[debug] [MJSONWP] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/a656ea3a-90c6-46ed-8dca-8445d2bbf1db 200 1201 ms - 76

**Comment by SrinivasanTarget** [comment]
@lwb2001258 Would recommend to update Appium Server and client to latest as the mentioned client and server are deprecated and not been supported.
