### ISSUE TITLE
Unhandled endpoint: /session/3C00DA4C-C3E6-4B84-A728-2F9ED49DBF41/element/97000000-0000-0000-1702-000000000000/selected

### ISSUE THREAD

**Issue by JohnHuahuaZhan** [appium/java-client#953]
```
Appium server - 1.8.1
Java-Client - 6.0.0
Selenium - 3.12.0
MAC - 10.13.5
```
```log
org.openqa.selenium.WebDriverException: Returned value cannot be converted to Boolean: Unhandled endpoint: /session/3C00DA4C-C3E6-4B84-A728-2F9ED49DBF41/element/97000000-0000-0000-1702-000000000000/selected -- http://localhost:8100/ with parameters {
    wildcards =     (
        "session/3C00DA4C-C3E6-4B84-A728-2F9ED49DBF41/element/97000000-0000-0000-1702-000000000000/selected"
    );
}
```

**Comment by saikrishna321** [comment]
@JohnHuahuaZhan Please fill in the issue template that is going to help understand the issue

**Comment by JohnHuahuaZhan** [comment]
@saikrishna321 
## Description
call element.isSelectted() to get selection state of element.the appium server is on mac device and java client run at linux platform
## Environment

* java client build version or git revision if you use some shapshot:1.8
* Appium server version or git revision if you use some shapshot:1.8.1
* Desktop OS/version used to run Appium if necessary:mac os 10.13.5
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:8.11.2
* Mobile platform/version under test:ios 10.3.3
* Real device or emulator/simulator:real device

## Details

```java
 IOSElement loginButton = driver.findElement(MobileBy.iOSNsPredicateString("name CONTAINS 'login'"));
loginButton.isSelected();
```
## Ecxeption stacktraces

```
org.openqa.selenium.WebDriverException: Returned value cannot be converted to Boolean: Unhandled endpoint: /session/555F3FC0-AA78-4AE7-B3DA-E33E507820A3/element/3D000000-0000-0000-2302-000000000000/selected -- http://localhost:8100/ with parameters {
    wildcards =     (
        "session/555F3FC0-AA78-4AE7-B3DA-E33E507820A3/element/3D000000-0000-0000-2302-000000000000/selected"
    );
}
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'caihua-PC', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-21deepin-generic', java.version: '1.8.0_172'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.RemoteWebElement.isSelected(RemoteWebElement.java:145)
	at ios_appium.App.main(App.java:63)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at org.openqa.selenium.remote.RemoteWebElement.isSelected(RemoteWebElement.java:143)
	... 1 more
```

## Link to Appium logs
appium log
```
[W3C] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/362e4321-6f8d-4849-9f87-48f81e3346b8/element/3D000000-0000-0000-2302-000000000000/selected] to [GET http://localhost:8100/session/555F3FC0-AA78-4AE7-B3DA-E33E507820A3/element/3D000000-0000-0000-2302-000000000000/selected] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"Unhandled endpoint: \\/session\\/555F3FC0-AA78-4AE7-B3DA-E33E507820A3\\/element\\/3D000000-0000-0000-2302-000000000000\\/selected -- http:\\/\\/localhost:8100\\/ with parameters {\\n    wildcards =     (\\n        \\\"session\\/555F3FC0-AA78-4AE7-B3DA-E33E507820A3\\/element\\/3D000000-0000-0000-2302-000000000000\\/selected\\\"\\n    );\\n}\",\n  \"sessionId\" : \"555F3FC0-AA78-4AE7-B3DA-E33E507820A3\",\n  \"status\" : 1\n}"
[JSONWP Proxy] Replacing sessionId 555F3FC0-AA78-4AE7-B3DA-E33E507820A3 with 362e4321-6f8d-4849-9f87-48f81e3346b8
```

**Comment by mykola-mokhnach** [comment]
I assume `/selected` endpoint is not implemented on the server side and this is by design. You could try to use `/value` endpoint instead to check if a checkbox is checked.

**Comment by saikrishna321** [comment]
close as inactive
