### ISSUE TITLE
Can't run appium server programmatically

### ISSUE THREAD

**Issue by tanumuki** [appium/java-client#967]
## Description

Can't run appium server programmatically
In my test suite I am using @BeforeSuite annotations of testNG and calling the POM.xml. But it throws exception

## Environment

* java client build version or git revision if you use some shapshot: 6.1.0
* Appium server version or git revision if you use some shapshot: 1.8.1
* Desktop OS/version used to run Appium if necessary: MacOS
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: iPhone 8 simulator 
* Real device or emulator/simulator:

## Details

INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
appium starting!!
[Appium] Welcome to Appium v1.8.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.8.1","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 21 ms - 83
[HTTP] 
device is  IPHONE_SIMULATOR
Simualtor is thsis!!!
Driver Managerclass capabilities.IphoneSimulatorCapabilities
this is the driver
driver is null
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"/Users/tanumukherjee/Downloads/Saavn.app","automationName":"XCuiTest","platformName":"iOS","deviceName":"iPhone X"},"capabilities":{"alwaysMatch":{"appium:app":"/Users/tanumukherjee/Downloads/Saavn.app","appium:automationName":"XCuiTest","appium:deviceName":"iPhone X","platformName":"ios"},"firstMatch":[{}]}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/tanumukherjee/Downloads/Saavn.app","automationName":"XCuiTest","platformName":"iOS","deviceName":"iPhone X"},null,{"alwaysMatch":{"appium:app":"/Users/tanumukherjee/Downloads/Saavn.app","appium:automationName":"XCuiTest","appium:deviceName":"iPhone X","platformName":"ios"},"firstMatch":[{}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1530713786771 (19:46:26 GMT+0530 (IST))
[Appium] Creating new XCUITestDriver (v2.84.0) session
[Appium] Capabilities:
[Appium]   platformName: ios
[Appium]   app: /Users/tanumukherjee/Downloads/Saavn.app
[Appium]   automationName: XCuiTest
[Appium]   deviceName: iPhone X
[debug] [BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities [object Object] were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[BaseDriver] Session created with session id: 4f269670-73a2-4edf-a9bb-80b7047b8304
[debug] [XCUITest] Current user: 'tanumukherjee'
[debug] [XCUITest] Xcode version set to '9.4.1' (tools v9.4.1.0.1.1528165917)
[debug] [XCUITest] iOS SDK Version set to '11.4'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1530713787634 (19:46:27 GMT+0530 (IST))
[XCUITest] Simulator udid not provided, using desired caps to create a new simulator
[XCUITest] No platformVersion specified. Using latest version Xcode supports: '11.4' This may cause problems if a simulator does not exist for this platform version.
[debug] [simctl] Creating simulator with name 'appiumTest-iPhone X', device type id 'iPhone X' and runtime id '11.4'
[iOSSim] Constructing iOS simulator for Xcode version 9.4.1 with udid '792C4501-C577-421B-83E1-369637BF70A7'
[XCUITest] Created simulator with udid '792C4501-C577-421B-83E1-369637BF70A7'.
[XCUITest] Determining device to run tests on: udid: '792C4501-C577-421B-83E1-369637BF70A7', real device: false
[BaseDriver] Using local app '/Users/tanumukherjee/Downloads/Saavn.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1530713789209 (19:46:29 GMT+0530 (IST))
[debug] [XCUITest] Checking whether app '/Users/tanumukherjee/Downloads/Saavn.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app '/Users/tanumukherjee/Downloads/Saavn.app': 'com.Saavn.Saavn'
[debug] [BaseDriver] Event 'resetStarted' logged at 1530713789214 (19:46:29 GMT+0530 (IST))
[XCUITest] Not scrubbing third party app in anticipation of uninstall
[debug] [BaseDriver] Event 'resetComplete' logged at 1530713789370 (19:46:29 GMT+0530 (IST))
[XCUITest] Continuing without capturing device logs: iOS Simulator with udid 792C4501-C577-421B-83E1-369637BF70A7 is not running
[XCUITest] Setting up simulator
[debug] [iOS] No reason to set locale
[debug] [iOS] No iOS / app preferences to set
[debug] [iOSSim] No Simulator cache items for cleanup were matched in '/Users/tanumukherjee/Library/Developer/CoreSimulator/Devices/792C4501-C577-421B-83E1-369637BF70A7/data/Library/Caches'
[debug] [iOSSim] Setting preferences of 792C4501-C577-421B-83E1-369637BF70A7 Simulator to {"ConnectHardwareKeyboard":false}
[debug] [iOSSim] Setting common Simulator preferences to {"ConnectHardwareKeyboard":false}
[debug] [iOSSim] Updated 792C4501-C577-421B-83E1-369637BF70A7 Simulator preferences at '/Users/tanumukherjee/Library/Preferences/com.apple.iphonesimulator.plist' with {"DevicePreferences":{"792C4501-C577-421B-83E1-369637BF70A7":{"ConnectHardwareKeyboard":false}},"ConnectHardwareKeyboard":false}
[debug] [iOSSim] The count of running Simulator UI client instances is 0
[iOSSim] Booting Simulator with UDID 792C4501-C577-421B-83E1-369637BF70A7...
[iOSSim] Starting Simulator UI with command: open -Fn /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID 792C4501-C577-421B-83E1-369637BF70A7 -ConnectHardwareKeyboard 0
[iOSSim] Simulator with UDID 792C4501-C577-421B-83E1-369637BF70A7 booted in 32 seconds
[debug] [BaseDriver] Event 'simStarted' logged at 1530713821862 (19:47:01 GMT+0530 (IST))
[debug] [XCUITest] Starting log capture for iOS Simulator with udid '792C4501-C577-421B-83E1-369637BF70A7', using 'xcrun simctl spawn 792C4501-C577-421B-83E1-369637BF70A7 log stream --style compact'
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1530713822819 (19:47:02 GMT+0530 (IST))
[debug] [XCUITest] Verifying application platform
[debug] [XCUITest] CFBundleSupportedPlatforms: ["iPhoneSimulator"]
[debug] [XCUITest] Installing '/Users/tanumukherjee/Downloads/Saavn.app' on Simulator with UUID '792C4501-C577-421B-83E1-369637BF70A7'...
[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1530713828975 (19:47:08 GMT+0530 (IST))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[debug] [XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] WDA is not listening at 'http://localhost:8100/'
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1530713829366 (19:47:09 GMT+0530 (IST))
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Error: Carthage binary is not found. Install using `brew install carthage` if it is not installed and make sure the root folder, where carthage binary is installed, is present in PATH environment variable. The current PATH value: '/usr/bin:/bin:/usr/sbin:/sbin'
[XCUITest]     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[XCUITest]     at checkForDependencies$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/wda/utils.js:70:9)
[XCUITest]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Reso[durces/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appieum.app/Cobntents/Resourug] ces/app/node_modules[Bas/appium/nodeeDriver] Event 'wdaStartFailed' logged at 1530713829390 (19:47:09 GMT+0530 (IST))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: "Carthage binary is not found. Install using `brew install carthage` if it is not installed and make sure the root folder, where carthage binary is installed, is present in PATH environment variable. The current PATH value: '/usr/bin:/bin:/usr/sbin:/sbin'".
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Removing WDA application from device
_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest]     at <anonymous>
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1530713840719 (19:47:20 GMT+0530 (IST))
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Error: Carthage binary is not found. Install using `brew install carthage` if it is not installed and make sure the root folder, where carthage binary is installed, is present in PATH environment variable. The current PATH value: '/usr/bin:/bin:/usr/sbin:/sbin'
[XCUITest]     at [Odebug] [BaseDrbject.wrappedLogger.errorAndThroiver] Evwe (/nt Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[XCUITest]     at checkForDependencies$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/wda/utils.js:70:9)
[XCUITest]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[XCUITest]     at Generato'wdaStartFailed' logged at 1530713840724 (19:47:20 GMT+0530 (IST))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: "Carthage binary is not found. Install using `brew install carthage` if it is not installed and make sure the root folder, where carthage binary is installed, is present in PATH environment variable. The current PATH value: '/usr/bin:/bin:/usr/sbin:/sbin'".
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Removing WDA application from device
rFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest]     at <anonymous>
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: "Carthage binary is not found. Install using `brew install carthage` if it is not installed and make sure the root folder, where carthage binary is installed, is present in PATH environment variable. The current PATH value: '/usr/bin:/bin:/usr/sbin:/sbin'".
[XCUITest]     at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:427:13)
[XCUITest]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_mo[dduleseb/babel-runtiugme] [XCU/rITegest] Not celearing log nfiles. Use `clearSystemFierator/runtime.js:136:37)
les` capability to turn on.
[debug] [XCUITest] Deleting simulator created for this run (udid: '792C4501-C577-421B-83E1-369637BF70A7')
[XCUITest]     at <anonymous>
[debug] [XCUITest] Killing running processes 'xcodebuild.*792C4501-C577-421B-83E1-369637BF70A7, 792C4501-C577-421B-83E1-369637BF70A7.*XCTRunner' for the device 792C4501-C577-421B-83E1-369637BF70A7...
[debug] [XCUITest] 'pgrep -nif xcodebuild.*792C4501-C577-421B-83E1-369637BF70A7' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] 'pgrep -nif 792C4501-C577-421B-83E1-369637BF70A7.*XCTRunner' didn't detect any matching processes. Return code: 1
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1530713854418 (19:47:34 GMT+0530 (IST))
[W3C] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "Carthage binary is not found. Install using `brew install carthage` if it is not installed and make sure the root folder, where carthage binary is installed, is present in PATH environment variable. The current PATH value: '/usr/bin:/bin:/usr/sbin:/sbin'".
[W3C]     at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:427:13)
[W3C]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[W3C]     at <anonymous>
[HTTP] <-- POST /wd/hub/session 500 67751 ms - 1926
[HTTP] 
Error: org.openqa.selenium.WebDriverException: It is impossible to create a new session because 'createSession' which takes HttpClient, InputStream and long was not found or it is not accessible
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'Tanus-MacBook-Pro.local', ip: 'fe80:0:0:0:873:8972:6ac7:2835%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.5', java.version: '1.8.0_151'
Driver info: driver.version: IOSDriver
org.openqa.selenium.WebDriverException: It is impossible to create a new session because 'createSession' which takes HttpClient, InputStream and long was not found or it is not accessible
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'Tanus-MacBook-Pro.local', ip: 'fe80:0:0:0:873:8972:6ac7:2835%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.5', java.version: '1.8.0_151'
Driver info: driver.version: IOSDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:195)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:209)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:231)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:95)
	at managers.DriverConnection.<init>(DriverConnection.java:28)
	at managers.DriverConnection.getDriverInstance(DriverConnection.java:37)
	at capabilities.IphoneSimulatorCapabilities.createDriver(IphoneSimulatorCapabilities.java:35)
	at managers.DriverManager.getDriver(DriverManager.java:31)
	at testCases.VerifyHomePage.init(VerifyHomePage.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:529)
	at org.testng.TestRunner.run(TestRunner.java:497)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:185)
	... 45 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "Carthage binary is not found. Install using `brew install carthage` if it is not installed and make sure the root folder, where carthage binary is installed, is present in PATH environment variable. The current PATH value: '/usr/bin:/bin:/usr/sbin:/sbin'".
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'Tanus-MacBook-Pro.local', ip: 'fe80:0:0:0:873:8972:6ac7:2835%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.5', java.version: '1.8.0_151'
Driver info: driver.version: IOSDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "Carthage binary is not found. Install using `brew install carthage` if it is not installed and make sure the root folder, where carthage binary is installed, is present in PATH environment variable. The current PATH value: '/usr/bin:/bin:/usr/sbin:/sbin'".
    at getResponseForW3CError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:806:13)
    at asyncHandler$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:361:37)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	... 50 more

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.
You can git clone https://github.com/appium/sample-code or https://github.com/appium/sample-code/tree/master/sample-code/apps and reproduce an issue using Java and sample apps.
Also you can create a [gist](https://gist.github.com) with pasted java code sample or put it here using markdown. About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and 
[Writing on GitHub](https://help.github.com/categories/writing-on-github/)

## Ecxeption stacktraces

Please create a [gist](https://gist.github.com) with pasted stacktrace of exception thrown by java.

## Link to Appium logs

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by SrinivasanTarget** [comment]
> [debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: "Carthage binary is not found. Install using brew install carthage if it is not installed and make sure the root folder, where carthage binary is installed, is present in PATH environment variable. The current PATH value: '/usr/bin:/bin:/usr/sbin:/sbin'".

@tanumuki Hope you got it.

**Comment by tanumuki** [comment]
Hey Sri,
This is not happening when i run the appium server manually from terminal!! :(  Basically the carthage issue doesn't come up when i run it manually. But when i call it programmatically i see this issue. Any leads?

**Comment by SrinivasanTarget** [comment]
@tanumuki Ideally both does the same. Not sure as i haven't encountered that so far. Check in discuss forum if any one has encountered the same.

Looking at logs. Can you check both programatic start and manual start points to same appium source and everything is set in PATH perfectly.

**Comment by padmakarsrinivas** [comment]
@tanumuki If you are running the tests from Eclipse IDE, below steps can solve the problem.

1. Right-click on the test script > Run as > Run Configuration 
2. Select Environment
3. Tap on Select
4. Select PATH
5. Click on Edit and  copy past this: /bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin
6. Apply and Run

**Comment by saikrishna321** [comment]
closing as user-side issue
