### ISSUE TITLE
Java client can't determine Appium server startup

### ISSUE THREAD

**Issue by Qwsafex** [appium/java-client#972]
## Description

Java client doesn't seem to determine running Appium server. After launching Appium server it hangs for two minutes and then says, that server didn't start.

## Environment

* io.appium:java-client:6.0.0
* Appium 1.8.1
* Ubuntu 16.04
* Node 10.6.0

## Details

`curl http://0.0.0.0:4723/wd/hub/status` gives 200 OK, so server clearly does start.

## Code To Reproduce Issue [ Good To Have ]
Code is super simple

```
    @Test
    public void androidTest() {
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setVersion("8.1");
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("deviceName", "android");
        capabilities.setCapability("app", "path/to/my/app.apk");
        AndroidDriver driver = new AndroidDriver(capabilities);
        System.err.println(driver.currentActivity());
    }
```

## Exception stacktraces

The output looks like this:
```
[Appium] Welcome to Appium v1.8.1
        [Appium] Appium REST http interface listener started on 0.0.0.0:4723
            at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:146)
            at io.appium.java_client.remote.AppiumCommandExecutor.lambda$0(AppiumCommandExecutor.java:209)
            at java.util.Optional.ifPresent(Optional.java:159)
            at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:207)
            at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
            ... 11 more

            Caused by:
            org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://0.0.0.0:4723/wd/hub/status] to be available after 120001 ms
                at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)
```

Here is a full stacktrace:
https://gist.github.com/Qwsafex/73aa8742ac1e4a0e0a90dec0b01682eb

**Comment by SrinivasanTarget** [comment]
@Qwsafex Try the URL as `http://127.0.0.1:4723/wd/hub/` while creating driver instance

**Comment by Qwsafex** [comment]
@SrinivasanTarget It helped, thanks a lot!

**Comment by SrinivasanTarget** [comment]
@Qwsafex Glad that it worked. Closing this.
