### ISSUE TITLE
org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement: {stacktrace=NoSuchElementError: An element could not be located on the page using the given search parameters.

### ISSUE THREAD

**Issue by nageshc** [appium/java-client#986]
## Description

Couldn't select any element when running script in real iOS device(iPhone 6s) in a Safari Browser.
Tried updating to latest appium java-client, selenium-java, appium version

## Environment

* java client build version or git revision if you use some shapshot: **6.0.0-BETA5**
* Appium server version or git revision if you use some shapshot: **1.8.0**
* Desktop OS/version used to run Appium if necessary: **MacOS 10.12.6**
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: **4.1.1**
* Mobile platform/version under test: **iPhone 6s iOS 10.1.1** 
* Real device or emulator/simulator: **Real Device**

## Details

appium java-client = **6.0.0-BETA5**
selenium-java = **3.9.1**
appium version = **1.8.0**

Please provide more details, if necessary.

## Ecxeption stacktraces
`org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement: {stacktrace=NoSuchElementError: An element could not be located on the page using the given search parameters.
    at XCUITestDriver.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/lib/commands/web.js:182:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37), error=no such element, message=An element could not be located on the page using the given search parameters.}
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:25:02.294Z'
System info: host: 'Vertiss-Mac-mini-5.local', ip: 'fe80:0:0:0:1c2e:4681:aac5:46f6%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_66'
Driver info: driver.version: IOSDriver`

**Comment by saikrishna321** [comment]
@nageshc please provide server logs and also make sure you have the element in dom your trying to interact.
